### ISSUE TITLE
Why is `css/main.css` hard-coded into the `create-react-app` portal?

### ISSUE THREAD

**Issue by DanEdwards-JM** [liferay/liferay-frontend-projects#1000]
## What is your question?

Hello all, I just have a quick question that is based on a small problem we are having with a React app (made with `create-react-app`) compiled to a Liferay portal using `@liferay/cli`.

I see that `/static/css/main.css` is being added to the application through `com.liferay.portlet.header-portlet-css` in `addCSSPortletHeader.ts` whether or not the file actually exists or there is an existing config in place already.

I guess my question is why this is happening? And is it necessary to hard-code this dependency in? We are using css-in-js for our application so don't have a global `main.css` and we're getting 404's on the network because there's nothing there and we can't remove this option.

**Comment by bryceosterhaus** [comment]
I believe you should be able to remove the `com.liferay.portlet.header-portlet-css` property from your package.json entirely and you should be fine.

**Comment by DanEdwards-JM** [comment]
This is exactly how I found the issue, by not having `com.liferay.portlet.header-portlet-css` present in the `package.json`. `/static/css/main.css` is hardcoded into the portlet in `addCSSPortletHeader.ts`.

**Comment by bryceosterhaus** [comment]
@DanEdwards-JM ah I see, I'll add this to our list of things to look into and to work on so can hopefully have a solution for you soon.

**Comment by bryceosterhaus** [comment]
@DanEdwards-JM can you provide some steps to reproduce your issue? I just tested locally by generating a new project with @liferay/cli and then I removed `"com.liferay.portlet.header-portlet-css"` from the package.json. After building and deploying I don't see any 404s for stylesheets

**Comment by izaera** [comment]
Apparently [we are doing it wrong](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/packages/portal-adapt-base/src/loader/addCSSPortletHeader.ts#L45-L53), so this seems to be a bug.

I'll investigate it.

**Comment by DanEdwards-JM** [comment]
Hello you two, thanks for your time on this. @bryceosterhaus It was a converted `create-react-app` rather than a new application created with `@liferay/cli`. If I have a minute I'll put together a step-by-step to recreate for you 👍

**Comment by izaera** [comment]
> If I have a minute I'll put together a step-by-step to recreate for you

It's not necessary. I'm already fixing it :+1:

**Comment by izaera** [comment]
I've released:

* [portal-adapt-base 1.0.4](https://github.com/liferay/liferay-frontend-projects/releases/tag/portal-adapt-base%2Fv1.0.4)
* [portal-adapt-create-react-app 1.0.2](https://github.com/liferay/liferay-frontend-projects/releases/tag/portal-adapt-create-react-app%2Fv1.0.2)

It should work now :+1:
