### ISSUE TITLE
Liferay/CLI project fails on scss files on Windows

### ISSUE THREAD

**Issue by nitramek** [liferay/liferay-frontend-projects#1049]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :two: v2.x
-   [x] :three: v3.x

### Description
Newly generated project with `liferay new project-name` choosing Portal 7.4 CE, remote app with react.
When I run `liferay build` I get an error. 

```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file
```
I skimmed through the building code and I suspect this has to do with webpack configuration and paths. I suspect it has to do with 
[getWebpackConfiguration](projects/js-toolkit/packages/portal-base/src/util/getWebpackConfiguration.ts) and with the `getScssEntryPoints` function.

On WSL (Windows Subsystem For Linux) it runs fine.

**Desired behavior:**
Build completes.

**Current behavior:**
Build doesnt complete.

**Other information (environment, versions etc):**
Windows 10
Node 16.18.0

**Comment by izaera** [comment]
[NOTE: This bug is being tracked internally at https://issues.liferay.com/browse/LPS-169495]

**Comment by izaera** [comment]
I've been able to reproduce this bug inside `npm run start` (should be equivalent to `npm run build`):

![image](https://user-images.githubusercontent.com/3273630/211275452-3e393228-d26e-489f-a5bb-47abb08bf71b.png)

(Sorry for the screenshot, but I cannot copy text from my virtual machine :-( )

**Comment by izaera** [comment]
The problem is in [this line](https://github.com/liferay/liferay-frontend-projects/blob/55b7b50c9e9d9f249847c8709c4d153306115b25/projects/js-toolkit/packages/portal-base/src/util/getWebpackConfiguration.ts#L64)

It should say:

```javascript
{
    include: project.assetsDir.asNative
}
```

instead.

**Comment by izaera** [comment]
Should be fixed by release https://github.com/liferay/liferay-frontend-projects/releases/tag/portal-base%2Fv1.5.1
