### ISSUE TITLE
Document npm dependency range guidelines

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#106]
Quoting [this comment](https://github.com/liferay/liferay-frontend-projects/pull/105#discussion_r498717798):

> I will document this somewhere, but my thinking is:
> 
> * Projects with a good track record of following semver and which are >= 1.0.0: Use `^` ranges to make updating easier.
> * Projects which are reckless with semver or < 1.0.0: Use `--exact` versions.
> * Projects which are exactly 1.0.0: behavior and policy is undefined 😉
> * Our own internal projects: We can exactly lock these like we're already doing because we control the releases (ie. don't have to worry about duplicates), and because it allows us to do a controlled roll-out to liferay-portal (ie. if I `rm yarn.lock` in liferay-portal, I shouldn't suddenly get a new version of the bundler when I run `yarn install`) — the only way to update those dependencies should be by updating `@liferay/npm-scripts`.
> 
> So Prettier is an interesting example here. We have traditionally locked it because we didn't want the `rm yarn.lock && yarn` scenario to pull in a new version and potentially churn a bunch of files; but at this point in Prettier's lifecycle, it is very stable and moving slowly, and they've shown that they respect semver, so there's no real reason to treat it differently than any other dependency.

And the one I forgot to mention in there are projects like `react` and friends [for which we specify a range of `*`](https://github.com/liferay/liferay-frontend-projects/blob/47887905540322c7ea2042da45ab47586313a34c/projects/npm-tools/packages/npm-scripts/package.json#L56-L58) because we need a local copy in here for testing (ie. a peer dependency won't suffice), but at the end of the day we want the version of React to be determined by frontend-js-react-web in liferay-portal.

---

Now, not sure whether that document goes in here or in liferay-frontend-guidelines. I'm thinking it belongs in here because the recommendations are going to be tailored for the monorepo. (In the future I actually think we should be moving the guidelines repo in here too, so eventually the question may become moot.)

**Comment by izaera** [comment]
This seems to be "fixed", so closing it.
