### ISSUE TITLE
Github issue template outdated link

### ISSUE THREAD

**Issue by DannyMeister** [liferay/liferay-frontend-projects#1079]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [x] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [x] :three: v3.x

### Description

This is a meta-bug-report.  When trying to open an issue related to Liferay JS Toolkit, the issue template contains a link to a non-existant "How-to-troubleshoot-your-setups.md":

> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

**Comment by izaera** [comment]
Fixed. 

Thx :raised_hands:
