### ISSUE TITLE
bs3-bs4-compat: Add Lexicon 1.x mixins that were removed in Clay 2.x / 3.x

### ISSUE THREAD

**Issue by pat270** [liferay/liferay-frontend-projects#1091]
### Issue type (mark with `x`)

-   [x] :bug: Bug report

### Version (mark with `x`)

-   [x] :keycap_ten: v10.x or higher

### Description
Some mixins are missing when upgrading 7.1 themes to 7.4. The bs3-bs4-compat layer should also include Lexicon 1.x mixins that were removed.

**Desired behavior:**

**Current behavior:**

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**

**Comment by izaera** [comment]
Can you please specify how  to upgrade from 7.1 to 7.4 and provide some steps we can follow to reproduce it? 
IINM you need to use several Themes Toolkit versions? :thinking:  I mean, I think you cannot do it with a single step, IIRC...

**Comment by pat270** [comment]
@izaera I'm going off this [thread](https://liferay.slack.com/archives/C03CAD9EF/p1677568273800079). I guess it's not really a 7.1 theme, but one that is currently going through the process of being upgraded. They're running into some issues that could be fixed in the compatibility layer.

**Comment by izaera** [comment]
Mmm, I see...

So, we have two `bs3-bs4-compat` projects in this repo:

1. https://github.com/liferay/liferay-frontend-projects/tree/master/projects/js-themes-toolkit/packages/bs3-bs4-compat
2. https://github.com/liferay/liferay-frontend-projects/tree/master/maintenance/projects/js-themes-toolkit-v10-x/packages/bs3-bs4-compat

One is for the current Themes Toolkit version ([v11](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-themes-toolkit/packages/liferay-theme-tasks/package.json#L82)), the other one is for the v10 series.

- Which one should be changed? Or should both be changed?
- And what is exactly the change being requested (mind that I don't have any idea of what mixins you are referring to and I don't know the internal structure of Clay either)? 
    - Is it just adding a new dep in one (or both) of those two project?
    - Or is changing a version number?
    - ...

**Comment by pat270** [comment]
@izaera probably all of them. I'll send you a pr and you can take a look at it.

**Comment by izaera** [comment]
A PR would be great :+1:  Thx
