### ISSUE TITLE
Do periodic security update (yarn audit)

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#112]
This issue will substitute this currently open dependabot PR:

- https://github.com/liferay/liferay-frontend-projects/pull/111 (eslint-plugin-react)

More context on our policy here: https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/security.md

Last periodic update was: https://github.com/liferay/liferay-frontend-projects/issues/2

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-js-themes-toolkit/pull/520 (npm-keyword)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/148 (`@typescript-eslint/parser`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/197 (`eslint-config-prettier`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/issues/112 (`@typescript-eslint/parser`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/215 (`@typescript-eslint/parser`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/222 (`eslint-plugin-react-hooks`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/230 (`mem-fs-editor`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/238 (`@babel/preset-env`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/247 (`eslint`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/255 (`@types/fs-extra`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/277 (`@types/jest`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/291 (`typescript`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/363 (`jest`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/377 (`sinon`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/381 (`sinon`, again)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/385 (`mem-fs-editor`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/390 (`@types/jest`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/393 (`webpack-cli`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/403 (`@typescript-eslint/eslint-plugin`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/424 (`typescript` again)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/428 (`@types/estree`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/448 (`ts-jest`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/463 (`@babel/preset-env`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/475 (`execa`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/479 (`@types/estree`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/492 (`babel-loader`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/498 (`@types/ejs`)

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/511 `@babel/preset-env`

**Comment by wincent** [comment]
As usual, hitting the wrong button. 😂

**Comment by wincent** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/524 (`webpack-cli`)

**Comment by bryceosterhaus** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/539 (`eslint`)

**Comment by bryceosterhaus** [comment]
Adding: https://github.com/liferay/liferay-frontend-projects/pull/563 (`chai`)

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/572 `eslint-config-prettier`

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/586 `sinon`

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/599 `prettier`

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/601 `mem-fs`

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/615 `eslint-plugin-react`

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/616 `typescript`

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/621 `prettier`

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/632 `typescript-eslint/eslint-plugin`

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/646 `@types/fs-extra`

**Comment by bryceosterhaus** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/651 `@types/yeoman-generator`
