### ISSUE TITLE
A Liferay CLI Tool created portlet cannot be deployed correctly 

### ISSUE THREAD

**Issue by Noro07** [liferay/liferay-frontend-projects#1167]
### Issue type (mark with `x`)

-   [x] :thinking: Question
-   [ ] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [ ] :three: v3.x

### Description
I followed this tutorial to create a project. when I load this widget and load it in the layout, it cannot load the project and display the following config. Did I miss something for displaying this portlet? Thanks in advance

tutorial link 
 https://learn.liferay.com/w/dxp/building-applications/tooling/other-tools/liferay-cli-tool#:~:text=You%20can%20also%20select%20%E2%80%9CLiferay,are%20build%20and%20bundle%20tools.  

command 

<img width="591" alt="image" src="https://github.com/liferay/liferay-frontend-projects/assets/40136071/f616e17c-b592-47cd-be73-389d6f81379a">

**Desired behavior:**
load the vue porlet

**Current behavior:**
display the config 
<img width="1381" alt="image" src="https://github.com/liferay/liferay-frontend-projects/assets/40136071/50ed955d-8c13-4966-a8dc-47d6a4049e44">

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**

**Comment by bryceosterhaus** [comment]
@Noro07 perhaps I am misunderstanding you, but I think what you are looking at is in fact the vue portlet.

We have markup like:
```html
            <div>
                <span class="tag">${Liferay.Language.get('portlet-namespace')}:</span> 
                <span class="value">{{portletNamespace}}</span>
            </div>
```

And then we initialize the Vue app with `new Vue` and pass in a data object that contains `portletNamespace`.


Am I missing something from your comment?

**Comment by bryceosterhaus** [comment]
Note that the cli tool generates a portlet with vue 2

**Comment by Noro07** [comment]
@bryceosterhaus Omg, I thought it was a loading error... Forgive my stupidity. By the way, is there a way to run the a portlet locally? I cannot see it in the script.
```

"scripts": {
    "build": "liferay build",
    "clean": "liferay clean",
    "deploy": "liferay clean && liferay build && liferay deploy"
  }
```

**Comment by Noro07** [comment]
@bryceosterhaus Thanks for your help!
