### ISSUE TITLE
feat: use liferay-npm-scripts to do linting and formatting inside the monorepo

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#128]
So in getting linting to work in the js-toolkit project I'm seeing the classic fight between Prettier and ESLint about how comments should be formatted.

Prettier wants:

```ts
export interface X {
  /**
   * Yo!
   */
  thing: string;
}
```

while ESLint wants:

```ts
export interface X {

  /**
   * Yo!
   */
  thing: string;
}
```

(There's a similar fight for `//` comments as well.)

Now, js-toolkit has a couple dozen of these darn comments, so I either add a suppression or I delete the comments. I'm going to add a suppression, and create this issue to remind me to remove it.

The definitive solution will be to dog-food liferay-npm-scripts and use it in the monorepo to do the formatting. As seen in bf5d84c475fb478bfa3378b9ab54d012e935a063, we don't have this problem in liferay-portal thanks to liferay-npm-scripts (because it runs ESLint + Prettier + post-processing, we can resolve little conflicts like this). Obviously, there's a benefit to dog-fooding anyway, especially now that other projects like liferay-learn are using npm-scripts too (ie. it is useful to us to be dog-fooding it all the time, so that we find out if we ever break the non-liferay-portal use case).

Possibly controversially, this change will bring the "Liferay" `else` formatting into the monorepo, which FWIW, is probably not a bad thing (one less thing for us to think about; just do it the same everywhere.)

**Comment by jbalsas** [comment]
> [...] inside the monorepo

I swear I skimmed over the title in GMail and literally read "inside this monstrosity" 😂

**Comment by jbalsas** [comment]
> The definitive solution will be to dog-food liferay-npm-scripts and use it in the monorepo to do the formatting

I think this is really the only reasonable path to take

**Comment by wincent** [comment]
```js
if (brave) {
    beTheChangeYouWantToSeeInTheWorld();
}
else {
    doNothing();
}
```

![my-eyes](https://user-images.githubusercontent.com/7074/95195493-e61d2e80-07d6-11eb-88ff-7ccf8046a7d1.gif)
