### ISSUE TITLE
refactor: activate TS "strict" mode in js-toolkit

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#134]
We currently have about 80 errors when we add `"strict": true` to our tsconfig.json file in `projects/js-toolkit` (as seen when you `yarn build`).

We have a similar number in `maintenance/projects/js-toolkit`, but it's harder to give an exact count because Lerna gets in the way when you run `yarn build`.

We should really have strict mode on.

- TypeScript compiler without `strict`: a car with airbags.
- TypeScript compiler with `strict`: a car with airbags _and_ seatbelts.

**Comment by izaera** [comment]
This was not done because there are still files that need to be ported from TypeScript to JavaScript. I would first port `.js` files to `.ts`, then become more strict with typing.

**Comment by izaera** [comment]
Since we will be moving to @liferay/cli I don't think we should spend time refactoring the old js-toolkit
