### ISSUE TITLE
chore: update to webpack v5

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#147]
Just something to keep on the radar:

- https://webpack.js.org/blog/2020-10-10-webpack-5-release/
- https://webpack.js.org/migrate/5/

**Comment by jbalsas** [comment]
Specially interesting could be https://webpack.js.org/concepts/module-federation/

**Comment by wincent** [comment]
Closing this one because it's duplicated by https://github.com/liferay/liferay-frontend-projects/issues/224 and that one has more detail.
