### ISSUE TITLE
angular-cli that generated by command `yarn qa` doesn't have any content in it

### ISSUE THREAD

**Issue by zhangyan0701** [liferay/liferay-frontend-projects#149]
**Steps to reproduce:**

1. Run command `yarn qa` to generate and deploy sample projects.
2. After the projects deployed to portal, add portlet angular-cli to page.
3. Assert that no content in angular-cli portlet, and errors in browser console.
![angular-cli](https://user-images.githubusercontent.com/25576873/95744271-a322f580-0cc5-11eb-9976-fdcf6a8f2657.png)

**Comment by izaera** [comment]
I'm closing this one as it is now obsolete.
