### ISSUE TITLE
babel-plugin-normalize-requires removes `.js` extension from folder names under certain circumstances

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#161]
See discussion at https://github.com/liferay/liferay-npm-build-tools/pull/11, and specially the comment https://github.com/liferay/liferay-npm-build-tools/pull/11#issuecomment-314427293.

**Comment by wincent** [comment]
Nope, not closed at all. This happened because we used `Closes: $SOME_NUMBER` instead of using `Closes: $FULL_URL`.

**Comment by izaera** [comment]
I'm going to close this as it was partially fixed and hasn't created any problem in the last 4 years.
