### ISSUE TITLE
Provide a standard way to switch between prod and dev builds

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#163]
Currently the making of dev/prod builds is left to the user and the bundler is agnostic in respect to that.

@yuchi proposes to have a way to tell the bundler which build you are doing and, with that, decide if we turn code like:

```javascript
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

into:

```javascript
'use strict';

module.exports = require('./cjs/react.production.min.js');
```

for production, and leave untouched for dev.

That way, production builds always use production dependencies, while dev builds can branch depending on the value of the `process.env.NODE_ENV`.

**Comment by wincent** [comment]
Nope. Not really closed at all.

**Comment by izaera** [comment]
OK, so we are now relying on NODE_ENV during build time to decide how to build projects (production or dev) and we still don't have any runtime notion of development servers (this is something that would need to be addressed by the Portal itself, not the frontend infrastructure stack). 

So, I'll close this as there's nothing more we can do (from the POV of this repository and the projects it contains).
