### ISSUE TITLE
Provide a way to use .vue files with the npm bundler

### ISSUE THREAD

**Issue by travisrcory** [liferay/liferay-frontend-projects#164]
Developers using Vue would like to make use of single file components. Vue provides [vue-loader](https://github.com/vuejs/vue-loader) as a solution for this, but I am not sure how this would work with our npm-bundler. This is more easily implemented using webpack, and probably using the liferay npm portlet extender would be a good way to accomplish this as well.

**Comment by wincent** [comment]
Given [this comment](https://github.com/liferay/liferay-frontend-projects/issues/164#issuecomment-698418318), going to add the 3.x label here.

**Comment by izaera** [comment]
This should be possible now using custom elements.
