### ISSUE TITLE
Support "page asset contributor"

### ISSUE THREAD

**Issue by dnebing** [liferay/liferay-frontend-projects#166]
As an alternative idea to https://github.com/liferay/liferay-npm-build-tools/issues/283, a compile time solution for relative addressing issues, I'd like to propose a more encompassing portal-based solution.

The crux of the problem with relative addresses is that the derived path comes from the browser address bar, hits MainServlet and results in a 404.

It seems to me that the issue is not on the dev side as much as it is the inability of MainServlet to resolve assets correctly.

I'd like to propose the addition of a "page asset contributor" handling for MainServlet. Instead of returning a 404 right away, MainServlet would give the "page asset contributor(s)" a chance to resolve the asset request. Often this will simply be a matter of stripping the incoming page URL prefix and letting the "page asset contributor(s)" return the file from its own web context.

JS portlets would just declare themselves as "page asset contributors" and MainServlet would need to find the right one(s) for the layout and give it (them) a chance to return the requested asset.

This is not a perfect solution because it does allow asset name collisions to become issues, but I think we could highlight this as a developer concern and put the onus on the developer to use unique asset names that avoid conflicts.

The benefit to this approach is that it will allow Angular, Vue, etc developers to use relative addressing like they are used to using for non-portal development and will even allow the use of many 3rd party modules that rely on relative addressing for their own assets. It will allow unit test frameworks during development because the JS code would not need to use full URLs that are unresolvable by the local testing frameworks.

**Comment by izaera** [comment]
I think this does not longer apply to our new cloud deployment model. Also it hasn't been an issue for anybody since long ago, so I'm closing it.
