### ISSUE TITLE
Liferay AMD Loader attempting to load file with no name

### ISSUE THREAD

**Issue by elycruz** [liferay/liferay-frontend-projects#171]
Hi all,
  I have a javascript portlet (portlet built using 'yo liferay-js') which uses the clarity.design UI library.
In my app there is a package that gets loaded from clarity (`@clr/core`) which doesn't have a "main" or a "module" property in it's package json file (however it indeed does contain a default export 'index.js').  

The bundler packages up the aforementioned package but when I run Liferay, Liferay is trying to load the package up as `http://localhost:8080/o/js/resolved-module/@ps_ng_clarity_yo_no_extender$clr/core@3.1.0/.js?languageId=en_US` (notice the "/.js" file name) the bundler/amd-loader should have a case for taking care of this case as sometimes node packages are required despite not having the ability to update them.

### System config below:
Liferay version: 7.2, 7.1
Bundler version:  2.18.4

### Shortened bundler report:
```
Report of liferay-npm-bundler execution
Executed at:	Wed, 15 Apr 2020 20:19:55 GMT
Execution took:	15s
Warnings
This report is from an incremental build: some steps may be missing (you may remove the output directory to force a full build).
Bundler environment versions
Package	Version
liferay-npm-bundler	2.18.4
liferay-npm-build-tools-common	2.18.4
liferay-npm-bundler-plugin-resolve-linked-dependencies	2.18.4
liferay-npm-bundler-plugin-namespace-packages	2.18.4
liferay-npm-bundler-plugin-inject-imports-dependencies	2.18.4
babel-preset-liferay-standard	2.18.4
liferay-npm-bundler-plugin-replace-browser-modules	2.18.4
liferay-npm-bundler-plugin-inject-peer-dependencies	2.18.4

Bundled packages
Package	Version	
ps_ng_clarity_yo_no_extender	1.0.0	
...
@clr/angular	3.1.0			
@clr/city	1.1.0	
@clr/core	3.1.0	
@clr/icons	3.1.0	
@clr/ui	3.1.0	
...

### Summary of package transformations
Package	        Version	Copy phase	Pre-babel phase	Babel phase	Post-babel phase
ps_ng_clarity_yo_no_extender	1.0.0		1 plugins applied	6 files processed	2 plugins applied
@clr/angular	3.1.0				
@clr/city	        1.1.0	1 plugins applied	1 plugins applied		3 plugins applied
@clr/core	3.1.0	1 plugins applied	1 plugins applied	453 files processed	3 plugins applied
@clr/icons	3.1.0	1 plugins applied	1 plugins applied	27 files processed	3 plugins applied
@clr/ui	        3.1.0	1 plugins applied	1 plugins applied		3 plugins applied
```

Also, this seems to be an issue with AMD Loader.  Will report the issue there, 
though if you guys have any suggestions, they're appreciated.

Thanks,
@elycruz

**Comment by wincent** [comment]
Marking this with the 3.x label because of [this comment](https://github.com/liferay/liferay-frontend-projects/issues/171#issuecomment-617720596).

**Comment by izaera** [comment]
Closing this as it has been answered.
