### ISSUE TITLE
Angular adapted app: Production environment is hardcoded in Liferay builder

### ISSUE THREAD

**Issue by ChrisMayor** [liferay/liferay-frontend-projects#173]
Currently, it is not possible for an Angular adapted app to have a different then production build output from the Liferay builder, because always "ng build --prod" is called.

This is caused by the liferay-npm-build-support npm package, where the production build is hardcoded:

liferay-npm-build-support/src/scripts/build/index.js

```
case ProjectType.ANGULAR_CLI:
			buildWith('build', ['--prod=true']);
			break;
```

It would be very helpful for Liferay installations with multiple environments if the builder would allow different environment builds for adapted Angular apps.

**Comment by izaera** [comment]
Closing this as the OP said they have a workaround for it.
