### ISSUE TITLE
Add support for easily adding jest tests

### ISSUE THREAD

**Issue by allen-ziegenfus** [liferay/liferay-frontend-projects#174]
I have been trying to use the js generator `yo liferay-js` to create a React portlet project with jest tests.

What I tried so far: 

1. `yo liferay-js`
2. `npm i --save-dev liferay-npm-scripts`
3. add ```		"test": "liferay-npm-scripts test"``` to package.json
4. Add some react code in /src/ and test cases under /test/, make sure it builds
5. `npm run test`

Result: 
    Fails with ```Plugin/Preset files are not allowed to export objects, only functions.```

This indicates a mix of babel 6 and 7. 

I had a similar result just adding `jest` directly instead of `liferay-npm-scripts` 

To fix this I updated everything to babel7: 

1. `npx babel-upgrade --write`
2. Update plugins + presets and move .babelrc to babel section of `package.json` (for some reason otherwise jest thinks there are multiple config files): 

```	
       "babel": {
		"presets": [
			"@babel/preset-env",
			"@babel/preset-react"
		],
		"plugins": [
			"@babel/proposal-object-rest-spread"
		]
	}
```

Could we add the results of these steps directly to the generator? I am happy to help with that if need be, but wasn't sure if there was a strategy regarding babel 6 vs 7

**Comment by wincent** [comment]
Adding 3.x label to this because 2.x is in soft maintenance mode at this point (ie. soft in the sense that we don't have a strict "bug fixes only" policy for it, but we do expect most forward-looking development to occur on the 3.x rewrite).

**Comment by izaera** [comment]
Mmm, this is trying to use npm-scripts and js-toolkit in the same project. That's by no means supported outside of the [liferay-portal](https://github.com/liferay/liferay-portal) project.

@allen-ziegenfus I'm closing this. Feel free to discuss it, if still applies, in slack.
