### ISSUE TITLE
lnbs-start does not seem to be able to correctly parse .npmbuildrc 

### ISSUE THREAD

**Issue by allen-ziegenfus** [liferay/liferay-frontend-projects#176]
I was trying to use lnbs-start in a react javascript portlet, so I added these lines to .npmbuildrc:
```
rules: [{
			test: /src\/.*\.js$/, use: {
				loader: 'babel-loader',
				options: {
					presets: ['@babel/preset-env', '@babel/preset-react']
				}
			}
		}],
```
however the script took that and just put "options: [Object]" in the .webpack/webpack.config.js file

is there some other way to configure react with the babel-loader and lnbs-start?

**Comment by izaera** [comment]
We have merged https://github.com/liferay/liferay-frontend-projects/pull/526, so there's no need to extend `npm run start` using .npmbuildrc any more. Closing this, then.

**Comment by DanEdwards-JM** [comment]
See https://github.com/liferay/liferay-frontend-projects/issues/188#issuecomment-1217963936
