### ISSUE TITLE
Widget does not render and JSON error

### ISSUE THREAD

**Issue by amaiorov** [liferay/liferay-frontend-projects#179]
**Description**
Widget generated with yeoman stops rendering after placed on page and "Look & Feel" configuration is updated.

**Steps to reproduce**
 - generate a widget with yeoman
 - making no changes
 - build and deploy to Liferay
 - add widget to page
 - open "Look & Feel" configuration and save with no changes

**Issue**
 - widget stops rendering
 - "SyntaxError: Unexpected token t in JSON at position 59" in console

**Notes**
 - Liferay DXP 7.2

**Comment by izaera** [comment]
This looks like a server side error related to Liferay DXP itself. Have you checked that first? Do you get any error in the server console?

If you are sure this is really an error in the portlet please follow the steps in https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md and provide a detailed stack trace of the error.

Closing this as answered. Feel free to reopen if necessary.
