### ISSUE TITLE
Lint for unwanted capital letters at start of `it()` descriptions

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#18]
This would be a companion rule to [`liferay/no-it-should`](https://github.com/liferay/eslint-config-liferay/blob/master/plugins/eslint-plugin-liferay/docs/rules/no-it-should.md), which is about starting `it()` descriptions with simple verbs instead of the word "should" (technically a "modal verb").

Based on examples like in [this PR](https://github.com/julien/liferay-portal/pull/266):

```js
// Incorrect code:
it('Adds the parameters to the portlet URL', () => {});

// Correct code:
it('adds the parameters to the portlet URL', () => {});
```

Rationale: this DSL is supposed to read like well-structured and formatted English, so we want:

> it adds the parameters...

instead of:

> it Adds the parameters...

**Comment by bryceosterhaus** [comment]
Gonna close as we don't have the capacity for it. Will re-open in future if necessary
