### ISSUE TITLE
How to get a production build with Liferay for react?

### ISSUE THREAD

**Issue by MarcoPortillo** [liferay/liferay-frontend-projects#180]
Hi,

I have been searching on the internet for a few hours, but i cannot find anything about it. I just have [this](https://help.liferay.com/hc/en-us/articles/360029028051-Developing-a-React-Application), which for development is fine, but I need to deploy my portlets as a production build as well, I always use:

> npm run build

but that just keeps building a normal dev .jar file, and I need one for production. If I check my portlets with react developer tools, I have this message:

![image](https://user-images.githubusercontent.com/21960445/87949733-b0ee2380-caa6-11ea-9fbb-ea6f03762794.png)

What to do? Any ideas?

**Comment by izaera** [comment]
If you are not using the [adapt feature](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-adapt-most-popular-frameworks-projects.md) you can tweak your package.json to make any build you like.

I mean, the bundler just wraps whatever you feed it, it doesn't do anything to control if it is development or production...
