### ISSUE TITLE
TypeError: Loader 'undefined' failed: Path must be a string.

### ISSUE THREAD

**Issue by faragos** [liferay/liferay-frontend-projects#181]
When I try to specify a target in the babel loader in the bundler-config it fails with:

TypeError: Loader 'undefined' failed: Path must be a string.

My Config:
```
        {
          "loader": "babel-loader",
          "options": {
            "presets": [
              ["env", {
                "targets": {
                  "browsers": ["last 2 Chrome versions"]
                }
              }]
            ]
          }
        }
```

I try to use async-await in my module. Babel transforms it thats also works in older browsers. Do you have an example where this works? Either with the target or with a plugin to include the regenerator-runtime?

**Comment by wincent** [comment]
GitHub shouldn't have autoclosed this one; reopening.

**Comment by izaera** [comment]
:thinking: Where's that? In what context? It looks like you are trying to configure webpack...?

**Comment by faragos** [comment]
I think it was inside of the `.npmbundlerrc` inside the `rules.use` for `*.js` files.

Was something like this:
``` 
"rules": [
    {
      "test": "\\.js$",
      "exclude": ["node_modules", "node"],
      "use": [
       ...
      ]
    },
]
```

I worked around the issue by using the `vue-cli-service` and building it with babel on my own.

You can close it when you can't reproduce it or aren't further developing v2 when it's not really urgent, because I think for me it isn't relevant anymore.

**Comment by izaera** [comment]
> I think for me it isn't relevant anymore.

Closing it, then. If it reappears we'll create a new issue.
