### ISSUE TITLE
Bundler ignores Vue.config.js runtimeCompiler option

### ISSUE THREAD

**Issue by jtumano** [liferay/liferay-frontend-projects#184]
Hello

"liferay-npm-build-support" starting from version 2.14.0 does not include vue with runtime compiler, even if there is runtimeCompiler = true property in vue.config.js

Older versions complained that babel could not process these dependencies and copied them as is. 

Maybe there is an option for .npmbundlerrc to exclude some deps from processing and to copy them as is?

**Comment by izaera** [comment]
> Maybe there is an option for .npmbundlerrc to exclude some deps from processing and to copy them as is?

There's [this](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/.npmbundlerrc-file-reference.md#ignore) for skipping processing of project files.

And [this](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/.npmbundlerrc-file-reference.md#exclude) for excluding node_modules files.

Perhaps you can use the latter with some custom build step to add any files you want?

Closing as answered, feel free to reopen if necessary.
