### ISSUE TITLE
Update generator-liferay-js vue.js template to make it usable 

### ISSUE THREAD

**Issue by jwanner83** [liferay/liferay-frontend-projects#186]
Hello guys, I was wondering if there is a reason that the yeoman generator-liferay-js vue template requires some major changes (as mentioned here: https://help.liferay.com/hc/en-us/articles/360029028071-Developing-a-Vue-Application) to make it usable. 

Wouldn't it be better to just update the generator to programmatically generate it the way it is described in the documentation so the documentation would become obsolete?

If there is no reason, hit me up. I would like to adapt the template 👍

**Comment by izaera** [comment]
I'm closing this as the conversation seems to be concluded.
