### ISSUE TITLE
Angular 10 not working for sample test

### ISSUE THREAD

**Issue by LidoDev** [liferay/liferay-frontend-projects#191]
I created an angular project with ng new "sample-project", without any modification in angular project. Then i applied the adapt, deploy scripts and i get the same error as liferay/liferay-frontend-projects#190 

**Angular CLI: 10.1.3
Node: 12.18.3**

**Comment by Javaxiss** [comment]
Hi there!

I just followed developer reference from Liferay help center, after generating a sample angular project (ng new). No other customization or dependencies were added in my case. Adapting existing Angular apps, I've never been able to get to work  :expressionless:

I'm having exactly the same problem in this thread, when deploying an adapted angular application:

```
Error: The following problems where detected while resolving modules:
    · Missing dependency 'sample-ng-app@1.0.0/sample-ng-app/polyfills-es5' of 'sample-ng-app@1.0.0/index'
    · Missing dependency 'sample-ng-app@1.0.0/sample-ng-app/runtime-es5' of 'sample-ng-app@1.0.0/index'
    · Missing dependency 'sample-ng-app@1.0.0/sample-ng-app/main-es5' of 'sample-ng-app@1.0.0/index'
```
I even tried to do by downgrading angular version to 8 or 6 but I got the same errors displayed in browser and the widget does not render as well.

Do you confirm this behaviour or have I made a mistake? :thinking:

**Comment by wincent** [comment]
> Do you confirm this behaviour or have I made a mistake?

I'm not sure about 8 or 6, but the last-tested versions can be seen in [the `dependencies.json` file](https://github.com/liferay/liferay-frontend-projects/blob/6252b50e2082f30c6f438cf59a1b2b17d1b1e0b3/maintenance/projects/js-toolkit/packages/generator-liferay-js/src/target-angular-portlet/dependencies.json#L3-L10) (right now, that means 10.2.2).

**Comment by Javaxiss** [comment]
> > Do you confirm this behaviour or have I made a mistake?
> 
> I'm not sure about 8 or 6, but the last-tested versions can be seen in [the `dependencies.json` file](https://github.com/liferay/liferay-frontend-projects/blob/6252b50e2082f30c6f438cf59a1b2b17d1b1e0b3/maintenance/projects/js-toolkit/packages/generator-liferay-js/src/target-angular-portlet/dependencies.json#L3-L10) (right now, that means 10.2.2).

Yes, when generating a new Angular 10  widget all works fine. (even for 6 or 8) :wink:

However, my doubts are over just the subtarget `liferay-js:adapt`. That errors are displayed by the browser even for sample projects as described above. :confused:

btw, I'm using  **generator-liferay-js@2.22.1**

**Comment by izaera** [comment]
Closing this. Angular 10 should be working since [2.24.0](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/CHANGELOG.md#liferay-js-toolkitv2240-2021-03-11). If you have further problems feel free to reopen :-).
