### ISSUE TITLE
Missing version constraints issue when trying to run Angular/PrimeNG app (using primeng table module)

### ISSUE THREAD

**Issue by creativeprogramming** [liferay/liferay-frontend-projects#193]
Liferay AMD Loader: Unhandled failure: Error: The following problems where detected while resolving modules:
Missing version constraints for @csndc-alerting-gui$angular/cdk in package.json of csndc-alerting-gui$primeng@10.0.3/scrolling
    at Loader._getResolutionError (loader.js:384)
    at loader.js:283 while resolving modules: ["csndc-alerting-gui@1.0.0/index"]

**Comment by izaera** [comment]
Please follow the steps [here](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) and reopen providing more info if necessary.
