### ISSUE TITLE
BUG: Loader is loading npm package with no "main" prop as "/.js"!?

### ISSUE THREAD

**Issue by elycruz** [liferay/liferay-frontend-projects#199]
The AMD loader is attempting to load `@clr/core` npm package as: 
```
http://localhost:8080/o/js/resolved-module/@ps_ng_clarity_yo_no_extender$clr/core@3.1.0/.js?languageId=en_US // notice the "/.js" file name 
```
When it should be 
```
http://localhost:8080/o/js/resolved-module/@ps_ng_clarity_yo_no_extender$clr/core@3.1.0/index.js?languageId=en_US
```
The package `@clr/core` doesn't have a `main` (or `module` property) but does indeed have an index.js (and index.ts) file.  IMO the bundler/amd-loader should be able to pick up on this though (or have 'index.js' as a default?)?  Or should we expect all packages that have a default export to specify the export?

Thanks,

**Comment by izaera** [comment]
OK, reproduced it. 

The problem with `@clr/core` is that it is not distributed as a CommonJS/ES5 package, but as ES2015+ with module syntax (see [its index.js file contents](https://cdn.jsdelivr.net/npm/@clr/core)).

Bundler v2 only supports CommonJS/ES5 packages, thus `@clr/core` will never work unless it is first translated into that format prior to its use by the bundler.

That can be done in a previous step of the build, by configuring specific plugins in the bundler or babel to do it, ... 

In any case that is left to the user side for now, until we release a new major version of the JS Toolkit capable of deploying this type of packages.
