### ISSUE TITLE
Error when calling @liferay/npm-bundler with npx

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-projects#217]
### Issue type

-   :bug: Bug report

### Description

(Linked Jira issue https://issues.liferay.com/browse/LPS-122795)
(Reviewed with @izaera)

**Desired behavior:** call `@liferay/npm-bundler` with `npx` (`npx @liferay/npm-bundler`).

**Current behavior:** when the command is run, an error is shown in the console: 
![image](https://user-images.githubusercontent.com/800645/97543749-f20ca280-19c8-11eb-8547-69134b440d76.png)

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**
- Tested on NodeJS 10 on Windows and NodeJS 10 on Linux.
- I checked the same process with `npx @angular/cli` and it works.
- It _might_ be the reference to the binary file in package.json ([bundler](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/packages/npm-bundler/package.json#L4) vs [angular](https://github.com/angular/angular-cli/blob/master/package.json#L11))

**Comment by wincent** [comment]
> * It _might_ be the reference to the binary file in package.json ([bundler](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/packages/npm-bundler/package.json#L4) vs [angular](https://github.com/angular/angular-cli/blob/master/package.json#L11))

Seems like a reasonable guess. In `@liferay/npm-scripts` we [use the dot-relative form](https://github.com/liferay/liferay-frontend-projects/blob/993b70b9fc23165b023b531c6c00118ba9189d2f/projects/npm-tools/packages/npm-scripts/package.json#L4) and it works fine.

**Comment by wincent** [comment]
Just to clarify, @p2kmgcl — I see you tested this on Linux and Windows, but the linked LPS only mentions Windows. Does that mean it works on Linux and not on Windows?

**Comment by p2kmgcl** [comment]
Nope, I tested on Windows for the LPS and then I found that it doesn't work on Linux too (thanks to @izaera). I am going to update the Jira ticket :sweat_smile:

**Comment by izaera** [comment]
I'm getting a different error in Windows:

![image](https://user-images.githubusercontent.com/3273630/97574544-ac150600-19eb-11eb-8c3d-fbbd40be1acb.png)

This has nothing to do with what I tried to fix in [this PR](https://github.com/liferay/liferay-frontend-projects/pull/218), i.e.: it has a different solution. I need to make sure what is really happening: whether this is the real error, or if there are two different errors that need to be addressed separately.

Can you check again @p2kmgcl ?

**Comment by p2kmgcl** [comment]
The steps are:
1. Create an empty directory
2. cd into it and run `yarn init` (yes to everything)
3. Add `yarn add generator-liferay-fragment@next` (which has `@liferay/npm-bundler@3.0.0-pre.1` as dependency)
3. Run `npx @liferay/npm-bundler`

**Comment by p2kmgcl** [comment]
Ok, after testing this on Windows, Linux, different computer and different `npx` versions (6 and 7 to be precise) I think that `npx` is more fragile than what I thought on the first place (too much magic :unicorn:). I just merged [this change](https://github.com/liferay/generator-liferay-fragments/pull/176/commits/2a5751bfb1aea1984a97700d09dffffea39a7d9e) removing the `npx` call and looking for the `liferay-npm-bundler.js` file manually.

@izaera suggested replacing [this `path.resolve`](https://github.com/liferay/generator-liferay-fragments/pull/176/commits/2a5751bfb1aea1984a97700d09dffffea39a7d9e#diff-2582baa03b1aa3bdabb3ac6d3811d724d0be43c1e43225fdcff47a7a5a598c93R23) with a `require.resolve` to better find where the `node_modules` directory is, but that's something I'll do tomorrow (because I'm tired).

Anyway, thanks @wincent and @izaera for your time and sorry for the `npx` headache, I'm closing the issue.

**Comment by izaera** [comment]
See https://github.com/liferay/liferay-frontend-projects/pull/220 too

**Comment by izaera** [comment]
> (because I'm tired).

![sloth](https://media.giphy.com/media/Oi8OF060IDTBC/giphy.gif)
