### ISSUE TITLE
Enforce preference for `getElementById` etc over `querySelector`

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#22]
From [this discussion](https://github.com/liferay/liferay-frontend-guidelines/issues/19) and specifically [this comment](https://github.com/liferay/liferay-frontend-guidelines/issues/19#issuecomment-499469920):

> at least some deviations from this pattern would be straightforward to lint for

This ticket is to remind us to actually set up or create the related lints:

```js
// incorrect code
const element = document.querySelector(`#${id}`);
const otherElement = document.querySelector('#' + id);

// correct code
const correct = document.getElementById(id);
```

May be able to do something similar for [`getElementsByClassName()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName) (might be a bit harder to do safely because the parameter can be a whitespace-separated list of classes, which may not always be statically detectable).

Creating this because we continue to [see this in code review](https://github.com/wincent/liferay-portal/pull/251#discussion_r421986327).

**Comment by bryceosterhaus** [comment]
Gonna close as we don't have the capacity for it. Will re-open in future if necessary
