### ISSUE TITLE
npm package missing version

### ISSUE THREAD

**Issue by smallma876** [liferay/liferay-frontend-projects#228]
### Issue type

-   :woman_shrugging: Other

### Description

Hello I installed jsPdf in my React-Widget then I generated the jar, after of that installed it but this installation fail and appear these errors in browser's console:

Missing dependency ':ERROR:Missing version constraints for pdfproyectoprueba$fs in package.json of pdfproyectoprueba$jspdf@2.1.1' of 'pdfproyectoprueba$jspdf@2.1.1/dist/jspdf.node.min'
· Missing dependency ':ERROR:Missing version constraints for pdfproyectoprueba$path in package.json of pdfproyectoprueba$jspdf@2.1.1' of 'pdfproyectoprueba$jspdf@2.1.1/dist/jspdf.node.min'.

**Desired behavior:**

**Current behavior:**
 -appear these errors when install the react-project in page of site:

Missing dependency ':ERROR:Missing version constraints for pdfproyectoprueba$fs in package.json of pdfproyectoprueba$jspdf@2.1.1' of 'pdfproyectoprueba$jspdf@2.1.1/dist/jspdf.node.min'
· Missing dependency ':ERROR:Missing version constraints for pdfproyectoprueba$path in package.json of pdfproyectoprueba$jspdf@2.1.1' of 'pdfproyectoprueba$jspdf@2.1.1/dist/jspdf.node.min'.

**Repro instructions (if applicable):**
         - Generate project react with "yo liferay-js" > React. 
          -Install jspdf library "npm install jspdf --save"
          -generate jar and deploy "npm run deploy"
           -install react-widget in page of site.

**Other information (environment, versions etc):** Version Liferay liferay-dxp-7.2.10.1-sp1, I generate my project with "yo liferay-js" > React.  Node version 10.15.1, npm version 6.4.1

link repo testcase of portlet react-liferay: 

[https://github.com/smallma876/jspdfLiferay](url)

**Comment by wincent** [comment]
@smallma876: Could you please take a look at ["How to troubleshoot your setups"](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) and let us know whether that sheds any light on your issue?

**Comment by izaera** [comment]
Closing this as solved (since we didn't get any more news from OP).
