### ISSUE TITLE
Missing dependency for moment-timezone 

### ISSUE THREAD

**Issue by AndrewWJordan** [liferay/liferay-frontend-projects#229]
### Issue type

-   [x] :thinking: Question

### Description
I have a missing dependency error for `moment-timezone` being thrown in my React widget.  

![image](https://user-images.githubusercontent.com/15637658/98401676-12c1a180-2034-11eb-9e3e-de7304bcd621.png)

How would I configure my portlet to get moment-timezone to work? 

**Desired behavior:**

Moment-timezone to work as expected without any missing dependency errors. 

**Current behavior:**

The widget does not display and the ☝️ error is displayed in the console. 

**Repro instructions (if applicable):**

Install - `npm i moment-timezone' --save-dev`
`import moment-timezone`
 .npmbundlerrc: 
```
{
  "config": {
    "imports": {
      "portlet-utils": {
        "react": "16.10.2",
        "/": "1.0.0"
      }
    }
  },
  "create-jar": {
    "output-dir": "../../build/docker/deploy",
    "output-filename": "com.liferay.portlets.livewhale-events.jar",
    "features": {
      "js-extender": true,
      "web-context": "/livewhale-events"
    }
  },
  "dump-report": true
}
```

**Other information (environment, versions etc):**

- Liferay DXP 7.2 
- `liferay-npm-bundler": "^2.0.0`

**Comment by wincent** [comment]
@AndrewWJordan: Could you please take a look at ["How to troubleshoot your setups"](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) and let us know whether that sheds any light on your issue?

**Comment by lgdd** [comment]
Hi @AndrewWJordan! If you used the command `npm i moment-timezone' --save-dev`, I believe it shouldn't be present at runtime and would explain your error. Did you try to run `npm i moment-timezone' --save` instead and make sure that it's part of `dependencies` and not `devDependencies`?

**Comment by izaera** [comment]
Good catch @lgdd ;-)

**Comment by izaera** [comment]
Closing this as answered. Feel free to reopen if necessary.
