### ISSUE TITLE
Add minification to build process

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#237]
As per [Design of new JS minification scheme in DXP](https://docs.google.com/document/d/1JYSSSVFQlEwy1CRv1ZD6hfql8AzuXTS39qY5HMnvUe4/edit), the initial goal is to:
- Implement build changes to handle the simple case of independent files
- Implement changes to handle the more complex case of embedded JS

This should be done in the context of a new `Single Build` architecture with the following constraints:
- Minification happens during build time
- Files are minified in place or keep the same name to avoid having to branch off served resources during runtime
- Minification is enabled through `NODE_ENV` variable

**Comment by wincent** [comment]
![groundhog-day](https://user-images.githubusercontent.com/7074/99095321-47ee6680-25d5-11eb-9cb3-c71770feda26.gif)

**Comment by wincent** [comment]
This whole issues smacks of [retcon](https://en.wikipedia.org/wiki/Retroactive_continuity).

**Comment by jbalsas** [comment]
Did we?

**Comment by jbalsas** [comment]
Just for reference, I just enabled Exalate in this repo, which tracks Issues and Milestones, so I kinda created this one to test which created https://issues.liferay.com/browse/IFI-2137 which is already assigned to yourself and `In Progress` in the current episode.

I couldn't directly use https://github.com/liferay/liferay-frontend-projects/pull/233 because we just track issues and not orphaned PRs, but I'm open to add that to the workflow! 😉

**Comment by wincent** [comment]
![noice](https://user-images.githubusercontent.com/7074/99096127-39ed1580-25d6-11eb-9233-580a602e28bf.gif)

**Comment by jbalsas** [comment]
> ![noice](https://user-images.githubusercontent.com/7074/99096127-39ed1580-25d6-11eb-9233-580a602e28bf.gif)

Toight!!

**Comment by wincent** [comment]
Closed by: https://github.com/liferay/liferay-frontend-projects/pull/233
