### ISSUE TITLE
Fully enforce use of spread syntax over Object.assign

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#24]
We added *partial* enforcement of this in https://github.com/liferay/eslint-config-liferay/issues/69 via ESLint's built-in [`prefer-object-spread` rule](https://eslint.org/docs/rules/prefer-object-spread), but that only enforces usage of spread *inside* `Object.assign()` calls (which is not all that useful, to be honest).

This ticket is to add a new rule to enforce use of spread more broadly, seeing as the question of `Object.assign` vs spread came up in [code review](https://github.com/wincent/liferay-portal/pull/309#discussion_r433907312) again, and we don't have documentation that I'm aware of recommending the use of it (and rather than write such documentation, I'd much rather just have a lint rule for it).

The reasons I originally gave back then still apply:

> - We're using Babel everywhere.
> - It is [faster](https://twitter.com/bmeurer/status/1015105293301280768) on engines that support it natively.
> - It is concise.
> - It is already a familiar pattern to people working in the React ecosystem.

And to that I'd add: that we're increasingly using spread to facilitate programming in an immutable style (creating copies of objects, sometimes with involving multiple levels of nesting, rather than mutating), and it would be quite painful to do this without spread, so we just want to do it consistently. Many examples of this in liferay-portal, so here is [just one instance](https://github.com/liferay/liferay-portal/blob/8570edc0382ba6302eaa218697b18c0f49acfa3e/modules/dxp/apps/analytics/analytics-reports-web/src/main/resources/META-INF/resources/js/state/chartState.js#L170-L178) that shows us using spread syntax to construct the next state in the context of a reducer.

Sole exception to this would be inside JSP, where we can't use spread (because of IE). I believe that our JSP linting will complain if you try to use it in JSP, just [like it complains if you try to use arrow functions, `const`, `let` etc](https://github.com/liferay/liferay-npm-tools/blob/2bbcd8ff3e2ab14177c5e6456a6eae77dc9411ac/packages/liferay-npm-scripts/test/jsp/lintJSP.js#L101-L171) in JSP.

**Comment by bryceosterhaus** [comment]
Gonna close as we don't have the capacity for it. Will re-open in future if necessary
