### ISSUE TITLE
Integrate dart-sass in liferay-npm-scripts build process

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#248]
As part of our effort to [Consolidate and improve SCSS compilation process](https://issues.liferay.com/browse/LPS-122900), this task looks to add support for Sass compilation through `liferay-npm-scripts`.

It should include:
- Provide out of the box support for Sass compilation from liferay-npm-scripts
- Update sass build processes to use a JS-based solution like Dart Sass
- Provide RTL conversion support from liferay-npm-scripts

**Comment by bryceosterhaus** [comment]
merged at https://github.com/liferay/liferay-frontend-projects/pull/282
