### ISSUE TITLE
Decide whether to make theme dependencies explicit

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#265]
At the moment "liferay-frontend-theme-styled" depends on "liferay-frontend-theme-unstyled", and one or both of them depend on "liferay-frontend-common-css" (which defines mixins like `media-query` and `respond-to` etc).

This dependency, however, is *not* reflected in the `package.json` files of those packages, which means that we rely on the somewhat brittle guarantee provided by the themes toolkit that generated themes will always have all three dependencies added to their `package.json` (either directly and explicitly, in the case of themes created with v9 of the toolkit, or transitively via the "liferay-theme-deps-7.*" packages, in the case of themes created with v8 of the toolkit).

Historically, the reason we did it this way was because we didn't have a huge amount of control over the release process of "liferay-frontend-theme-styled" etc (they are extracted from the [liferay-portal codebase](https://github.com/liferay/liferay-portal) as part of its build, and the process is quite complicated, effectively synthesizing a `package.json` dynamically by invoking a massive Java-based tool-chain).

So, filing this issue to reflect the open question here: should we make the dependencies explicit, and if so, how do we manage the complexity issues of the build?

**Comment by izaera** [comment]
Closing this as it's been inactive for too long and themes are not being actively maintained since we adopted the cloud model.
