### ISSUE TITLE
Change lx-icons to clay-icons when upgrading from 7.0 to 7.1

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-frontend-projects#268]
Reference liferay/liferay-js-themes-toolkit#359 https://github.com/liferay/clay/commit/850eb0582d1ea808771d9578e195e91f3115e1c0

When upgrading a theme from 7.0 to 7.1, should the upgrade process also update or notify the user about the changes from lx-icon and get-lx-icon to clay-icon and get-clay-icon?

Let me know if more information is needed.
Thank you.

**Comment by izaera** [comment]
Since 8.x is a very old version and this is a feature request (in principle we try to do our best when upgrading, but we don't cover all cases) I'll close this issue as discarded.

Feel free to reopen it if you find it absolutely necessary and we can reevaluate it again.
