### ISSUE TITLE
Provide a way to use eslint-config-liferay with VS Code's eslint plugin

### ISSUE THREAD

**Issue by allen-ziegenfus** [liferay/liferay-frontend-projects#27]
VS Code has a nice eslint plugin that will show any eslint problems in the "Problems" section

This fails with eslint-config-liferay due to how the plugins are bundled directly in the eslint-config-liferay:

```
[Info  - 2:28:22 PM] Failed to load plugin 'liferay' declared in 'liferay/modules/apps/resources/resources-web/.eslintrc.js » eslint-config-liferay/react » /home/allenz/liferay/lfris-www/liferay/modules/apps/resources/resources-web/node_modules/eslint-config-liferay/index.js': Cannot find module 'eslint-plugin-liferay' Require stack: - /home/allenz/liferay/lfris-www/__placeholder__.js
```

If I just copy the eslint-plugin-liferay/ folder from eslint-config-liferay directly to node_modules it will work fine

Could this be somehow fixed so this manual hack isn't needed? it makes for a much better dev experience

![image](https://user-images.githubusercontent.com/16581685/84431958-c3488800-abf1-11ea-85f0-bcaa9c060427.png)

**Comment by bryceosterhaus** [comment]
@allen-ziegenfus, we just repleaced eslint-config with eslint-plugin. You should be able to use that now instead and should work with vscode well
