### ISSUE TITLE
yo liferay-theme:classic should copy Provide-Capability to liferay-plugin-package.properties for language translation.

### ISSUE THREAD

**Issue by ethib137** [liferay/liferay-frontend-projects#273]
Since `yo liferay-theme:classic` copies language.properties files when it's run it should also copy over `Provide-Capability=liferay.resource.bundle;resource.bundle.base.name="content.Language"` in `liferay-plugin-package.properties` so that the translations are available in Liferay.

**Comment by bryceosterhaus** [comment]
Not sure. We can close for now and re-open if it is needed though.
