### ISSUE TITLE
Disallow useless explicit boolean values

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#28]
There are quite a few possible scenarios in which this can come up. Some examples follow.

Bad:

```js
const x = foo ? true : false;
const y = bar ? false : true;
const z = baz === 'thing' ? true : false;

if (boop) {
    return true;
} else {
    return false;
}

// etc
```

Good:

```js
const x = !!foo;
const y = !bar;
const z = baz === 'thing';

return !!boop;
```

We can decide how far we want to go with enforcing/autofixing this. It's clear that the very obvious violations could be fixed, but if we're ensure about how aggressive we want to be we could start small.

Coming here via: https://github.com/bryceosterhaus/liferay-portal/pull/72

**Comment by bryceosterhaus** [comment]
Unfortunately we just don't have the capacity to work on this. Closing for now and will re-open if this comes up again
