### ISSUE TITLE
Enforce "a, b" format for selector lists, when possible

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#29]
Requested [here](https://github.com/brianchandotcom/liferay-portal/pull/90502#issuecomment-648280646).

Copy-pasting my answer below.

---

Yeah, spaces are fine in [selector lists](https://drafts.csswg.org/selectors-4/#grouping) in [CSS](https://drafts.csswg.org/selectors-4/#grouping):

> when several selectors share the same declarations, they may be grouped into a comma-separated list. White space may appear before and/or after the comma.

So most APIs that work with selector lists will work either way. eg. `document.querySelector` etc. You can verify this on pretty much any web page with a demo like:

```
document.querySelectorAll('div,span').length === document.querySelectorAll('div, span').length
```

(evaulates to `true`).

I think in practice people conventionally write these "tight" without whitespace to minimize bytes over the wire (*one whole byte*, pre-gzip), seeing as the contents of strings will never get tampered with by a minifier. But it is probably (pointless) microoptimization.

We could enforce this automatically for the obvious cases (eg. string literal arguments to APIs know to take selectors). Some indirect uses would be harder to enforce because we'd have to trace through, and those are probably rare and not worth dealing with:

```js
let selector = 'a';

if (condition1) {
    selector = 'a, b';
}
else if (condition2) {
    selector = 'c';
}

// ...
const element = document.querySelectorAll(selector);
```

And then there are other places where we don't have enough information to know statically that a string is actually a selector. We could special case some of these (like the `delegate` calls that your `git grep` search turned up), but there will likely always be some that we can't detect; eg.

```js
Liferay.fire('event', {
    target: 'a,b' // This is payload is totally arbitrary, no water-tight way to know what it's for.
});
```

**Comment by bryceosterhaus** [comment]
Unfortunately we just don't have the capacity to work on this. Closing for now and will re-open if this comes up again
