### ISSUE TITLE
Support for generating bridges from AMD to webpack federation 

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#290]
### Issue type

-   :gift: Feature request

### Description

Add a new feature to generate bridges from AMD to webpack federation as the ones included in [this commit](https://github.com/liferay-frontend/liferay-portal/pull/606/commits/47919370022f8ab06b421392b0f43b6fddc0c5e5).

**Comment by wincent** [comment]
> * 🎁 Feature request

![it-is-a-gif](https://user-images.githubusercontent.com/7074/101931704-12d83280-3bda-11eb-9f5d-82f4f15fd63f.gif)

(gif -> gift)

**Comment by izaera** [comment]
> (gif -> gift)

![oh my lord](https://media.giphy.com/media/3ov9jE3YKszddL2ak0/giphy.gif)
