### ISSUE TITLE
Remove fontawesome RTL plugin

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#305]
Doing this [silly thing](https://github.com/liferay/liferay-frontend-projects/pull/304) I realized we still have a [fontawesome plugin](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/r2/liferay-r2/plugins/fontawesome.js) even though we dropped fontawesome support a while ago.

The main goal of the plugin was to swap inlined directional fontawesome icons, so I think we should be able to simply remove it.

This took me down memory lane and made me remember that wanting to add these additional processing steps (plugins) was the main reason why we initially forked the `r2` project.

**Comment by wincent** [comment]
We dropped it from DXP as a baked-in thing, but it still exists in the themes toolkit as an optional add-on. Does that stop us from `rm`-ing the plug-in?

```
? 'Allo Greg! What would you like to do? Liferay Theme

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo liferay-theme



Welcome to the splendid Themes SDK generator!


ℹ️ This version of the Themes SDK (10.0.1) supports Liferay DXP
and Portal CE from 7.2 to 7.3.

For older versions, please use v8 of the toolkit:

> npm install -g generator-liferay-theme@^8.0.0 ↩
> yo liferay-theme:app ↩


? What would you like to call your theme? My Liferay Theme
? What id would you like to give to your theme? my-liferay-theme
? Which version of Liferay is this theme for? 7.3
? Would you like to add Font Awesome to your theme? Yes
```

**Comment by jbalsas** [comment]
> We dropped it from DXP as a baked-in thing, but it still exists in the themes toolkit as an optional add-on. Does that stop us from rm-ing the plug-in?

Mmm... yeah, I'd say it does. It does not stop us from dropping that feature for `7.4`, though 😂 .

**Comment by jbalsas** [comment]
I think it's small enough, though, so let's just kick the can forward.
