### ISSUE TITLE
chore: move js-themes-toolkit packages into liferay named scope

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#306]
### Issue type

-   🏠 Chore

### Description

**Desired behavior:**

- `liferay-theme-tasks` becomes a named-scope package (`@liferay/theme-tasks`).
- `generator-liferay-theme` becomes a named-scope package (`@liferay/generator-theme`).

I'm suggesting we do this only for v10 of the toolkit, not bothering with v9 and v8 (although we could do that if people felt it was worthwhile/necessary). In the case of the `js-toolkit`, we moved the v3 packages into the namespace but left the v2 packages behind, because we mostly only care about current development projects and not maintenance ones. With each passing year, the importance of any grojects in the `maintenance/` folder should taper off...

**Details:**

We've done this (to much rejoicing) for a number of other packages in the repo ([see docs](https://github.com/liferay/liferay-frontend-projects/blob/master/CONTRIBUTING/migrating-an-npm-package-to-the-liferay-named-scope.md)), including `@liferay/generator-js` (formerly `generator-liferay-js`), which shows that we can do it for Yeoman generators just fine.

The only (lame) reason I didn't do it when I imported the liferay-js-themes-toolkit into this repo is that the themes toolkit is one of those projects that many customers use, and we have documentation for it but not currently a technically writer on the team; I would be loathe to make all the documentation stale by changing the name of the packages and not have a way to update the docs. The technical side of the change is straightforward, as shown by our past experience.

Anyway, even if we don't do this straight away, wanted to create this ticket so that we don't forget about it. As [the docs](https://github.com/liferay/liferay-frontend-projects/blob/master/CONTRIBUTING/migrating-an-npm-package-to-the-liferay-named-scope.md) say:

> It is desirable to have our packages under the `@liferay` [named scope](https://docs.npmjs.com/using-npm/scope.html) for a few reasons:
>
> -   Easier discovery (eg. at-a-glance view of all of our packages).
> -   Easier management (eg. centralized access control).
> -   Clear way of distinguishing packages as officially "built-by-Liferay" as opposed to just "has-a-liferay-prefix-but-could-be-built-by-anyone".
> -   Namespace reserved just for us, so we can always secure the package names we want without having to compete with pre-existing registrations.

So I think we should do this when we find ourselves in a place where we have the capability to update the docs.

**Comment by jbalsas** [comment]
@dsanz has been working with the docs team and their priority is the theme story, so he might be able to share some insights.

Considering the existing packages are still published, documentation shouldn't go stale and we'd only need to update the `10.x` series.

Being a bit creative, I think we could maybe add some little thingie to our publish scripts so we do a dual publication? For example, in presence of a flag or something in the `package.json` like `"altName": "liferay-theme-tasks"` we could swap the value of `name` and publish again (or do it in some other way). That way we might not need to worry about existing docs since any updates to `10.x` will continue to be available? (Just a thought)

**Comment by wincent** [comment]
I simultaneously _applaud_ your innovation and _shudder_ at the thought of having the same produce released under two identities.

![shudder](https://user-images.githubusercontent.com/7074/102507154-35f45d80-4084-11eb-8e52-da60ce51247a.gif)

**Comment by jbalsas** [comment]
> I simultaneously applaud your innovation and shudder at the thought of having the same product released under two identities.

![imagination](https://user-images.githubusercontent.com/905006/102508487-5836ad00-407d-11eb-8401-ac8afd61af07.gif)

**Comment by dsanz** [comment]
We can consider this in the docs, it's just a matter of changing the name of the npm package in a couple of places:
* https://help.liferay.com/hc/en-us/articles/360028834632-Installing-the-Theme-Generator-and-Creating-a-Theme
* https://help.liferay.com/hc/en-us/articles/360029147711-Theme-Generator

How will we deal with the fact that now the package exists in its current naming schema for v10? will be push the updates to both names till a new version is released? will we cut updates sharply? That would be something I'd like to document properly
Best

**Comment by wincent** [comment]
> How will we deal with the fact that now the package exists in its current naming schema for v10? will be push the updates to both names till a new version is released? will we cut updates sharply? That would be something I'd like to document properly

What we did with other projects that moved into the named scope (for example, `eslint-config-liferay` → `@liferay/eslint-config`) was:

1. Publish the new package (`@liferay/eslint-config`) with the same version number as the old package.
2. Mark the old package (`eslint-config-liferay`) as "deprecated" with `npm deprecate`, which means that people:
   - See a banner if they look at [the package page on the registry](https://www.npmjs.com/package/eslint-config-liferay) telling them to "Please see `@liferay/eslint-config` instead"
   - See an equivalent text message if they install the old package (ie. with `npm install eslint-config-liferay`).

Note that we can specifically mark the v10 package alone as deprecated by passing a version number to `npm deprecate`; that way people intentionally installing and using v8 and v9 won't be bothered with a deprecation message that shouldn't apply to them.

So I'd just update all the places where we currently say `npm install -g generator-liferay-theme` to instead say `npm install -g @liferay/generator-theme`. Given that `npm` will install the latest version by default in the absence of an explicit version/range/tag, that should give us the desired result (ie. they either get the latest `@liferay/generator-theme`, or they don't read the docs but they see the deprecation message when they install `generator-liferay-theme`).

**Comment by dsanz** [comment]
Well, in that case, I think that we can move forward with this.

Documentation wise, it's just about adding a note stating that during toolkit v10 lifecycle, we deprecated the _naming schema_ to make it scoped to a qualified name (no feature changes). We might provide some of the reasons you mentioned earlier to help users understand this move.

From a package user perspective, all they have to know is that installation instructions for v10 are as follows:

`npm install -g @liferay/generator-theme`

(I'm not sure we shall add the same for theme tasks or they're also installed as a dependency)

For the more curious, we can add some extra details: 
1. The first version published under the new name is the same as last version published with the old name
2. The last version published with the old name has been deprecated
3. This affects to v10 so older releases work the same

I have one last question. In case of having several versions of the tooling installed (I'm not sure if this can happen when package name is the same, but now that they'll be different, then, it may happen), is there any way to run either version at will via command line? I think clarifyin this would be the last bit of information I'd expect to be in the docs

Best

**Comment by wincent** [comment]
> I have one last question. In case of having several versions of the tooling installed (I'm not sure if this can happen when package name is the same, but now that they'll be different, then, it may happen), is there any way to run either version at will via command line? I think clarifyin this would be the last bit of information I'd expect to be in the docs

Excellent question. You can only have one globally installed version of a given package at a time, which means that:

- If you needed to use both v8 and v9, you would remove v8 and install v9 (or vice versa) any time you needed to switch.
- You actually could have a version of v8 or v9 simultaneously installed with v10, because the package names will be different (ie. `@liferay/generator-theme` vs `generator-liferay-theme`). This actually sounds like a bit of a feature for people who need to work with two versions of DXP at a time... (Note that I lied when I said that all we need to do is update the installation instructions; we also need to note that when running the named scope version of the generator you will be running `yo @liferay/theme` instead of `yo liferay-theme`.)

Finally ([via this Pro-Tip™](https://twitter.com/ThatZackHawkins/status/893495424375341058)), it is in theory possible to use the generator without globally installing it, but our docs don't mention it because it's a complicating factor. But the general idea is something like `npx -p yo -p @liferay/generator-theme -c 'yo @liferay/theme'` (ie. `-p` to run/use packages without installating them — `yo` and `@liferay/generator-theme` — and `-c` to specify a command to run in that context: `yo @liferay/theme`). To run an older version without installing anything it would be something like `npx -p yo -p generator-liferay-theme@8.x -c yo 'liferay-theme'`.
