### ISSUE TITLE
Standarize DOM selectors

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-projects#312]
There are many ways to select DOM elements now. The most common one is using `document.querySelector()`, but it's possible to use other methods (like `document.getElementById`.

We should define some preferences when adding/using a selector for getting DOM elements. These are some patterns used inside portal:

```
<div class="el"></div>
<script>document.querySelectorAll(".el");</script>
```

```
<div class="<portlet:namespace />el"></div>
<script>document.querySelectorAll(".<portlet:namespace />el");</script>
```

```
<div id="<portlet:namespace />el"></div>
<script>document.querySelector("#<portlet:namespace />el");</script>
```

```
<div id="<portlet:namespace />el"></div>
<script>document.getElementById("<portlet:namespace />el");</script>
```

**Comment by kresimir-coko** [comment]
I don't think this belongs in the guidelines, if it did it'd probably be very small, like a few lines of text. A linter seems better appropriate, something that checks if the argument for `querySelector` starts with `#`, or similar. Thoughts?

**Comment by bryceosterhaus** [comment]
Closing. Will re-open later if we ever decide to do this.
