### ISSUE TITLE
Define a CSS structure

### ISSUE THREAD

**Issue by edalgrin** [liferay/liferay-frontend-projects#315]
Generally there are 2 main types of structure we should consider:
`A`
- project
    - scss
        - component-a
            - file.scss
        - component-b
            - file.scss
    - js
        - component-a
        - component-b

`B`
- project
    - component-a
        - scss
            - file.scss
        - js
    - component-b
        - scss
            - file.scss
        - js

`A` is based on the type of files (scss, js, html, etc) `B` is based on the modules
At the moment our system is a mix between these 2 methods
In Clay we can see mostly the first example `A`
In Portal we have a macro-division for modules `B` and then a division between type of files inside the specific module `B`, and they don’t actually take advantage of this separation: import the css as module.
what-i-usually-see
`projects/component-b/scss/file.scss`
```
@import ../../clay-atlas
// or @import ../../clay-base
// or @import ../../atlas-variables
// or @import ../../base-variables
// we are importing all the components and/or all the mixins from the library for a single component
@include create-button($vars);
```
what-i-would-prefer-to-see
`projects/component-b/scss/file.scss`
```
@import ../../clay/mixins/create-button
@include create-button($vars);
```

I personally prefer the `B` method, in my opinion it's more modular and it can be exported easily into more projects. But at the same time it's easier to create duplicated code and don't be aware of all its potential (e.g: mixins, variables, functions) but maybe with a complete documentation we won't have any complication

@marcoscv-work @pat270 @jbalsas what do you think ?

**Comment by kresimir-coko** [comment]
@edalgrin hey my dude what's the state of this issue?

**Comment by edalgrin** [comment]
the same of the other one, I think we can close and reopen in the future if necessary

**Comment by kresimir-coko** [comment]
Closing for now but can be opened at a later date when it becomes a priority
