### ISSUE TITLE
Define the right name for CSS files

### ISSUE THREAD

**Issue by edalgrin** [liferay/liferay-frontend-projects#316]
The first problem I want to highlight is the definition of a standard **name-style** for the CSS files in Portal and Clay. At the moment we are using at least 6 ways of create a user-friendly names for our files

`A` `example-of-file-name.scss`
`B` `example_of_file_name.scss`
`C` `_example-of-file-name.scss`
`D` `_example_of_file_name.scss`
`E` `exampleOfFileName.scss`
`F` `ExampleOfFileName.scss`

I think we should define a common convention and my proposal is: `B` and `D`. The `B` system would be used by those CSS files that need to be compiled/built in order to be used separately (e.g.: main.scss, clay.scss, new_css_imported_in_multiple_parts.scss). The `D` for those that don't need to be compiled (e.g.: _mixins.scss, _variables.scss, _new_mixins.scss)

---

The second issue is about the **name-content**. Imaging we are creating a new module "zodiac" (sorry I needed a simple example). We have the following configurations:

`A1`
```
- zodiac
    - fire
        - aries
        - leo
        - sagittarius
    - earth
        - taurus
        - virgo
        - capricorn
```
`B1`
```
- zodiac
    - zodiac_fire
        - zodiac_aries
        - zodiac_leo
        - zodiac_sagittarius
    - zodiac_earth
        - zodiac_taurus
        - zodiac_virgo
        - zodiac_capricorn
```
`C1`
```
- zodiac
    - zodiac_fire
        - zodiac_fire_aries
        - zodiac_fire_leo
        - zodiac_fire_sagittarius
    - zodiac_earth
        - zodiac_earth_taurus
        - zodiac_earth_virgo
        - zodiac_earth_capricorn
```
and if we have a complex name for the module
`D1`
```
- zodiac_sign
    - zodiac_sign_fire
        - zodiac_sign_fire_aries
        - zodiac_sign_fire_leo
        - zodiac_sign_sagittarius
    - zodiac_sign_earth
        - zodiac_sign_earth_taurus
        - zodiac_sign_earth_virgo
        - zodiac_sign_earth_capricorn
```
But there are so many combinations I can't write them all.
Maybe we should keep a simple structure like `A1` but it could generate so many doubts among the teams.
Maybe we should use the `D1` method but I'm afraid it could become hard to read in a deeper indentation and for the a complex-module-name we could apply similar rules used in the BEM system (https://en.bem.info/methodology/css/) but I'm not really a fan.

@marcoscv-work @pat270 @jbalsas What do you think?

**Comment by kresimir-coko** [comment]
@edalgrin is this still something that needs to be defined?

**Comment by edalgrin** [comment]
yes, but it's not something we will do now I guess 😄

**Comment by kresimir-coko** [comment]
Closing for now but can be opened at a later date when it becomes a priority
