### ISSUE TITLE
Create a document with all the mixins, functions and variables available in the Portal and Clay and how to use them

### ISSUE THREAD

**Issue by edalgrin** [liferay/liferay-frontend-projects#317]
One of the problem I encounter during my latest tasks was the lacking (or apparent absence) of a document where to find mixins, variables and functions altogether.

It could be useful to all the developers, to have a Document (in list or table format) where we can gather these values with a short description or instruction about its use.

Of course we can search through the Clay and Portal files but sometimes there are deprecated results that be confusing (compass, bourbon, bs3_compat_layer, etc)

We should also add the simple information about the imported-clay-files
example:
`@import atlas-variables.scss;`
"what does it means?"
"how can I use it?"
"why I should use it instead of `base-variables` or `clay-atlas`?"

@marcoscv-work, @pat270, @jbalsas What do you think?

**Comment by kresimir-coko** [comment]
@pat270 is this done?

**Comment by kresimir-coko** [comment]
@pat270 @edalgrin is this still needed?

**Comment by edalgrin** [comment]
Hey @kresimir-coko, I think this issue can be closed for now, since we have been trying to remove these functions/mixins from DXP and the priority of this is low.
