### ISSUE TITLE
Enforce order of class methods

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#33]
[Example of a PR](https://github.com/brianchandotcom/liferay-portal/pull/92908#issuecomment-676572490) that got rejected for not sorting the methods within a class.

There's no technical barrier to keeping them sorted, so we can make a lint rule to keep them lexicographically sorted. Sole exception to this rule should (probably) be that the `constructor`, if any, always goes first.

One thing to note about this though, is that both [real ES private methods](https://github.com/tc39/proposal-private-methods) (which have names like `#someMethod`) and old-school, private-by-convention-only methods (with names like `_someMethod` sort lexicographically before their public equivalents (ie. `someMethod`). We can discuss whether that's ideal or not (I'm inclined to think that it's fine, as we use simple lexicographical sorting for just about everything else; often these things can seem subjectively wrong and counterintuitive for at first, but after a while you stop noticing and may even forget why you ever cared about them).

**Comment by bryceosterhaus** [comment]
There is an [existing project for this](https://www.npmjs.com/package/eslint-plugin-sort-class-members) that we can use in the future if needed, but as of right now we will close this and re-open as needed
