### ISSUE TITLE
Document best practices when using browser & web APIs

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/liferay-frontend-projects#339]
Document the best practices, advice, and pitfalls in context of DXP when using [browser/web APIs](https://developer.mozilla.org/en-US/docs/Web/API) like Local Storage, Fetch, etc.

**Comment by kresimir-coko** [comment]
This proposal evolved into the Session API docs which can be found [here](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/dxp/session.md). Should we still document the `Storage` API, or rely on the docs found elsewhere on the internet?

**Comment by wincent** [comment]
> This proposal evolved into the Session API docs which can be found [here](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/dxp/session.md). Should we still document the `Storage` API, or rely on the docs found elsewhere on the internet?

Doing nothing sounds like a great default course of action. If we decide we want a specific gap to be filled in the docs, we can create a specific ticket for that.
