### ISSUE TITLE
Document when to use Liferay.publish, Liferay.provide and Liferay.<myCustomFunctionallity/Property>

### ISSUE THREAD

**Issue by diegonvs** [liferay/liferay-frontend-projects#340]
## What is your question?

There are three ways to expose a thing on global `Liferay` object, where I don't know for sure when to use a method or not

**Comment by wincent** [comment]
GitHub seems to have dropped the transfer job on the floor 😢

Most of the comments are visible over on the original (https://github.com/liferay/liferay-frontend-guidelines/issues/192) but not here.
