### ISSUE TITLE
Document aui:input and aui:validator

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#341]
One of the most used features in DXP are `aui:input` and `aui:validator`.

Both tags are massively used and contain many hidden features like:
- Multiple input types
- Model Hints
- Default Validations
- Custom Validations
- ...

The goal of this question is to document all the different features supported by these 2 tags and how they interact with each other.

**Comment by wincent** [comment]
GitHub seems to have dropped the transfer job on the floor 😢

Most of the comments are visible over on the original (https://github.com/liferay/liferay-frontend-guidelines/issues/218) but not here.
