### ISSUE TITLE
Establish security guidelines for Component (React) development

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#345]
As we move forward, it would be good to stablish some basics Security guidelines and best practices like:
- Sanitizing inputs
- Avoiding certain constructions
- Flagging `dangerouslySetInnerHTML` usages
- ...

These are just examples. The goal of this issue is to discuss and document what constitutes a safe baseline that we can automate and check to avoid security issues in our developments.

**Comment by bryceosterhaus** [comment]
Closing. Will re-open later if we ever decide to do this.
