### ISSUE TITLE
Standardize React Form management Strategy

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#348]
As we start to move into React realm, we need to start standardizing some common strategies.

The goal of this ticket is to discuss Form management. Some options out there are:
- [formik](https://github.com/jaredpalmer/formik)
- [react-final-form](https://github.com/final-form/react-final-form)
- [informed](https://github.com/joepuzzo/informed)
- ...

The personalization team is [already using formik](https://github.com/liferay/liferay-portal/blob/master/modules/apps/segments/segments-web/package.json#L5), so that's the one we will start offering, but the moment to decide should be now.

Calling out here in case they want to provide feedback and/or pros/cons lists based on their experience or previous research: @p2kmgcl, @andresfulla, @bryceosterhaus, @sandrodw3, @wincent, @matuzalemsteles, @boton, @brunobasto... feel free to bring in anyone that could offer additional insight

**Comment by kresimir-coko** [comment]
@bryceosterhaus has this been decided?

/cc @rodrigopaulino tagging you because I saw your name as the technically responsible one for the Forms team

**Comment by bryceosterhaus** [comment]
We have formik@2.1.4 support here, https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-react-web/package.json#L6
