### ISSUE TITLE
feat: generate coverage information during test runs

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#35]
@jbalsas was just telling me that @john-co has a PR somewhere (I think it's [this one](https://github.com/jbalsas/liferay-portal/pull/1880)) exploring the generation of coverage information during tests runs.

The proposal is that we:

1. (Via a change in this repo): Do it automatically in every `liferay-npm-scripts test` run.
2. (Via work outside this repo, and possibly inside the liferay-jest-junit-reporter package): Expose this information in CI infra somewhere so that we can have insight into coverage trends over time (and possibly set objectives around desired coverage or deltas — ie. never down, only up etc).

I'd want to see the impact that this has on test run times, but it is unlikely to be prohibitive because we have relatively few tests.

Also want to be cautious about any blanket coverage goals we set (because they distract us from making more targeted improvements to the test infra).

**Comment by kresimir-coko** [comment]
@john-co is this still a thing?

**Comment by bryceosterhaus** [comment]
Closing. Will re-open later if we ever decide to do this.
