### ISSUE TITLE
Standarize JSDoc formatting

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-projects#350]
Prettier does not apply any concrete format to jsdocs. It would be nice to have some linting for:

- Force/disallow new lines between jsdoc tags (add new line after @param? Add new line after description?).
- Prefer some tags over others (ex. @return instead of @returns).
- Describe which tags we must use in order to document components (do/dont add descriptions, etc).
- Force adding `@review` tag to every jsdoc (maybe?).

**Comment by wincent** [comment]
GitHub seems to have dropped the transfer job on the floor 😢

Most of the comments are visible over on the original (https://github.com/liferay/liferay-frontend-guidelines/issues/47) but not here.
