### ISSUE TITLE
Standardize testing strategy for React

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#351]
As the number of React projects grows, we need some common agreement on how to test those components and applications.

We already have some differing examples at:
- [master:segments-web](https://github.com/andresfulla/liferay-portal/tree/master/modules/apps/segments/segments-web/test/js)
- [master-private:portal-workflow-metrics-web](https://github.com/liferay/liferay-portal-ee/tree/master-private/modules/private/apps/portal-workflow/portal-workflow-metrics-web/src/main/resources/META-INF/resources/js/components/__tests__) (already not following our test folder convention which we should document, so I've created https://github.com/liferay/liferay-frontend-guidelines/issues/50 for it)
- [master-private: portal-search-ranking-web](https://github.com/arboliveira/liferay-portal/tree/LPS-89524_Search_Tuning_Result_Rankings/modules/apps/portal-search/portal-search-ranking-web/test/js). @thektan also started a request about [Add @testing-library/react and jest-dom](https://github.com/liferay/liferay-npm-tools/issues/108)

We should have some clear guidelines and common infra that we can recommend to make sure we have reliable and consistent tests across the product.

**Comment by wincent** [comment]
GitHub seems to have dropped the transfer job on the floor 😢

Most of the comments are visible over on the original (https://github.com/liferay/liferay-frontend-guidelines/issues/49) but not here.
