### ISSUE TITLE
Create a way to omit some Object's properties or allow existing without SF error

### ISSUE THREAD

**Issue by pavel-savinov** [liferay/liferay-frontend-projects#357]
Having the Object _selectedItem_:
```javascript
const selectedItem = {
     classNameId: 123,
     classPK: 456,
     editableId: 'abc'
    /* more properties here */
};
```
which represents a selected editable field mapped to some entity(by classNameId and classPK), we want to create new object _unmappedSelectedItem_ with exactly the same properties, but without classNameId and classPK.
The option we use now is creating a new object without those two properties:
```javascript
const unmappedSelectedItem = {
     editableId: selectedItem.editableId
     /* copy more properties here */
};
```
The short option could be something like this:
`const {classNameId, classPK, ...unmappedSelectedItem} = selectedItem;`
but our Source Formatter doesn't allow to do that saying that classNameId and classPK are assigned but never used.

Is there any other option to omit some Object's properties without copying property by property?

Task where this approach could be used to simplify the code: [https://issues.liferay.com/browse/LPS-98957](https://issues.liferay.com/browse/LPS-98957)

**Comment by kresimir-coko** [comment]
Closing because it is a minor issue that has a decent workaround
