### ISSUE TITLE
Update testing-library/jest-dom to latest

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#36]
At the time of writing, that means v4.2.3 (see: https://github.com/testing-library/jest-dom/releases).

Motivation: want to be able to use newer matchers provided by `@testing-library/jest-dom/extend-expect` such as `toBeChecked()` (released in v4.2.0) and such.

We're currently on v4.0.0.

**Comment by kresimir-coko** [comment]
We are using v4.2.4 inside liferay-frontend-projects, and v5.16.4 inside liferay-portal
