### ISSUE TITLE
Discuss mechanisms to patch third-party code used by our tools

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#370]
## What is your proposal?

I'm creating this issue to keep reference to [this slack conversation](https://liferay.slack.com/archives/G3JBR21HA/p1609146048470200).

Sometimes we've had the need to patch a third party software (in the case linked above it was `webpack`) but have never found a good solution that we have adopted as a pattern.

There's a diff-and-patch mechanism set up in `liferay-portal` as mentioned by Brian in [this PR](https://github.com/brianchandotcom/liferay-portal/pull/97237#issuecomment-751292989), but we shouldn't probably use it because it doesn't adapt well to frontend projects and would require quite a lot of overhead for very small profit.

So, in the linked conversation we discussed the pros and cons of:

1. Creating a fork of webpack and publish it with a different it while we use the patched copy
2. Put that fork inside this monorepo using git submodules or any other mechanism
3. Patch webpack on the go from npm-scripts
4. ...

## Why would adopting this proposal be beneficial?

Adopting a mechanism like this could help in unblocking us in the future when we depend on a third party release. But, on the other hand, we have discarded it for now as webpack releases often and we don't know if a blocking problem will appear in the future.

[I have asked](https://github.com/webpack/webpack/issues/12255#issuecomment-751647703), however, what is the release policy of webpack.

## What are the alternatives to this proposal?

A good alternative could be making a two week long travel to Tibet, for example. That's something I would like more than patching webpack, to mention an example.

**Comment by bryceosterhaus** [comment]
Forking seems much more desirable than anything to do with nexus. 

I like this idea the best though..
> A good alternative could be making a two week long travel to Tibet, for example

**Comment by jbalsas** [comment]
I'm doing some spring cleanup, and seeing as this perfectly well exposed issue by @izaera got some ❤️  and 👍  but not specific comments, looks like we might wanna just table this for next time 🤗

**Comment by wincent** [comment]
I know this one was about webpack, but I've had this issue in other contexts too. Sometimes we want/need to make a surgical incision, and instead we end up having to do stuff like [ghastly runtime monkey patching](https://github.com/liferay/liferay-portal/blob/f545e22df83fc6144f0f38cbcb7cea34db15c577/modules/apps/frontend-js/frontend-js-react-web/src/main/resources/META-INF/resources/js/index.es.js#L26-L32), or rolling out the expensive [nuclear option of forking an entire project](https://github.com/liferay/liferay-portal/commit/55848d2cab66e59a9993dd42486dd6061b6fa060) (from [among other unsavory options](https://github.com/liferay/liferay-frontend-projects/issues/394)).

`#NeverForget`
