### ISSUE TITLE
Add guidelines for expressions in conditionals and JSX

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#384]
As seen in threads [like this one](https://github.com/liferay-frontend/liferay-portal/pull/709#discussion_r560758533) (also quoted below) the question sometimes comes up of how to structure expressions in conditionals, especially in the context of conditional rendering in JSX.

We should probably have some lightweight guidelines that:

- Cover the simple cases for basic conditionals in `if` statements (eg. what truthy and falsey mean in JS).
- List some of the options for doing conditional rendering in JSX (ternaries, `if`, `&&` and so on; I don't think we need to lint/enforce any specific pattern, but it is good to make people aware of the options and then let them make a local decision in the name of readability/maintainability).
- Note pitfalls with patterns like `a.length && other`.

---

> Basically, four pieces of relevant info:
> 
> * `!!` is a common idiom for coercing to boolean in JS (and other languages too).
> * Since `0` is falsey in JS, it is "idiomatic" to write condtionals as `if (something.length)` instead of `if (something.length > 0)`; and due to falsiness of `0` we tend not to bother coercing in this case (eg. we don't do `if (!!something.length)`, although if we're writing TypeScript and we have a function that is annotated as returning a `boolean`, we may have to do something like `return !!something.length`).
> * `a && b` evaluates to `a` (not necessarily `false`) when `a` is falsey.
> * [In JSX `false` won't render anything at all](https://react-cn.github.io/react/tips/false-in-jsx.html) but `0` _will_ render, so while you might _want_ to write something like `fields.length && <div>blah</blah>` because it looks like "idiomatic" JS, in JSX it will actually squirt an unwanted `0` into the DOM, so, like @jbalsas said, you want to coerce to boolean with `!!fields.length &&`...

**Comment by wincent** [comment]
Fun fact: just discovered that I previously created [this issue](https://github.com/liferay/liferay-frontend-projects/issues/32) for linting against accidental `a.length && blah` in JSX context.

**Comment by matuzalemsteles** [comment]
Hey @wincent in these cases, we can consider an alternative to `!!` the use of `Boolean(something.length)`, it seems something "healthier" than double negation and we can convert to the more explicit Boolean value in the conditional. In that case, we would not be using the `Boolean` object constructor.

**Comment by wincent** [comment]
Why do you think it is `healthier`? `!!` seems better to me because:

- It avoids the function call overhead of calling `Boolean()`.
- `!!` is a common idiom not only in JS but in other languages with a `!` negation operator.
- `!!` is shorter, which makes it less likely to cause long lines and line-wrapping (which can hurt readability, especially in GitHub).

[The only place I'd use](https://github.com/liferay-frontend/liferay-portal/pull/249#discussion_r470647470)  `Boolean()` personally is in a `filter()` call (eg. `collection.filter(Boolean)` as a shorthand for `collection.filter(item => item)`).

**Comment by matuzalemsteles** [comment]
Well, this can be a bit of an "unfair" comparison but just as we avoid short names or abbreviations (like `cb`, `desc`...) to improve code reading, in this view this is similar to the use of `!!` vs `Boolean()`.

- `!!` is shorter but requires more cognitive reasoning at the time of reading, naturally, you look for the first negation operator `!` and then for the next negation that will adjust the type conversion.
- The use of `Boolean()` allows to provide similar functionality and is more explicit type conversion.

I have used a lot more `!!` in the past but whenever I went through this in the code it takes a little more time for me to understand what is happening I have more recently used the `Boolean` in conditionals, this has removed the confusions of certain way. I'm fine with any decision, but I wish there was more than one alternative for this case 🙂.

> `!!` is shorter, which makes it less likely to cause long lines and line-wrapping (which can hurt readability, especially in GitHub).

Well, that will eventually happen anyway at some point, depending on the nesting of the components 🙂

**Comment by bryceosterhaus** [comment]
A lint rule for `{a.length && blah` would be pretty great for jsx.


As for `Boolean()` vs `!!`. I have no issues with with and I am happy either way.

**Comment by wincent** [comment]
@matuzalemsteles: I think abbreviations of identifiers (eg. `callback` to `cb`) aren't in the same category, in the sense that `callback` vs `cb` is a choice between one identifier vs another; `!!` vs `Boolean()` is a choice between operators and functional calls, so there is a different dimension at play.

Consider a language like Ruby where you actually have a choice: you can write either `&&` or `and` (as well as `!` or `not`, `||` or `or` etc) because they have keyword equivalents for many operators. In the Ruby community the argument is sometimes made that `if this and that` is more "readable" than `if (this && that)` because it reads more like natural (human) language. The keywords have lower precedence too, which Rubyists say is great because it makes the language "more expressive" (ie. you can pick one or the other depending on how you want expressions to bind together... all of this so they can avoid using parens, which, BTW, Ruby also has... 🤦‍♂️).

JS is a very different language, because it comes from the family of C-like, "bracey" languages, where we're generally much more comfortable using operators as a syntactic shortcut. I mean, we could write `add(a, b)` because we think that `add` is "easier to read" than `a + b`, but we don't. And similarly, we could make helpers with names like `bitwiseRightShift(a, amount)` instead of writing `a << amount`, but we don't. In short, the reason JS has operators is because the designers of the language think that — once one becomes accustomed to them — the code actually becomes _more_ readable and expressive because it allows for compact representations using easily-recognized, visually-distinct punctuation marks.

Haskell programmers take this to ridiculous extremes, because you can define your operators (and operators are just functions), so you wind up with code that looks [like this](https://github.com/wincent/docvim/blob/master/lib/Text/Docvim/Parse.hs) 🤦‍♂️:

```haskell
command'          = string "command" >> ws >> CommandAnnotation <$> commandName <*> commandParameters
commandName       = char ':' *> many1 (alphaNum <|> char '!') <* optional ws
commandParameters = optionMaybe $ many1 (noneOf "\n")
```

But I don't think we're anywhere near that with `!!`. In my experience, I've had a few interactions with people when they see it for the first time and it usually goes something like this:

> A: What's that `!!` operator do?
>
> B: It's not a new operator, it's just two `!`: the first one negates the value (and coerces it to a boolean if it isn't already), and the second one undoes the negation, so overall, it's just a shorthand for coercion to boolean.
>
> A: Ah, cool. [Never confused about `!!` ever again.]
