### ISSUE TITLE
Turn off no-for-of-loops rule by default

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#405]
As [noted here](https://github.com/liferay-frontend/liferay-portal/pull/789#discussion_r5762704010), this rule is still on by default and it shouldn't be. We can either turn the rule off in `master`, or turn it off by default and then opt-in on the older branches. I like the latter approach better, even though it is more work, because it sets us up for the long term.

**Comment by bryceosterhaus** [comment]
> turn it on by default and then opt-out on the older branches

^ I like this option

**Comment by wincent** [comment]
Edited for clarity because I am a 🤡 and had the options inverted. Originally had:

> We can either turn the rule off in master, or turn it **on** by default and then **opt-out** on the older branches.

But it's supposed to be:

> We can either turn the rule off in master, or turn it **off** by default and then **opt-in** on the older branches.

**Comment by bryceosterhaus** [comment]
I must've misread because I agree'd with your edited version. So it all works out

**Comment by wincent** [comment]
Closed this issue, but linking to the upstream PRs that turn the rule back on where it's "needed":

- https://github.com/brianchandotcom/liferay-portal-ee/pull/33540
- https://github.com/brianchandotcom/liferay-portal-ee/pull/33541
- https://github.com/brianchandotcom/liferay-portal-ee/pull/33542
- https://github.com/liferay/alloy-editor/pull/1469
