### ISSUE TITLE
Update to support "liferay-npm-bundler.config.js"

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#41]
The new version of the bundler will use "liferay-npm-bundler.config.js" instead of ".npmbundlerrc".

So we'll need to ~update [the list of config files here](https://github.com/liferay/liferay-npm-tools/blob/f5fd94981432bba12b3e63384d55cabbb4c45e48/packages/liferay-npm-scripts/src/config/eslint.config.js#L6-L15), plus~ make sure that we can handle the new config file name elsewhere (will probably want to continue supporting the old file name just in case `liferay-npm-scripts` gets backported to a branch where the new bundler hasn't been backported).

**Comment by bryceosterhaus** [comment]
I don't think this is a thing anymore
