### ISSUE TITLE
Loading JSX in Default React Portlet Template

### ISSUE THREAD

**Issue by sgreco-dev** [liferay/liferay-frontend-projects#422]
## What is your question?

I am attempting to use .jsx files to build my React components.  I am looking for documentation on how to do two different things with the used versions of Webpack and Babel.

1.  I need to be able to have Webpack resolve .jsx files.  I tried adding the following to .npmbuildrc, but I constantly get unexpected token errors

```
"resolve": {
    	"extensions": ['.js', '.jsx']
                 }
```

My current .npmbuildrc is as follows.

```
{
	"liferayDir": "C:\\Liferay",
	"webpack": {
		"rules": [
			{
				"test": "src\\\\.*\\.js$",
				"use": "babel-loader"
			}
		]
	}
}
```

2. Configure babel to load the JSX files, I am getting unexpected token errors for a simple `<div>` tag, with the message that `You may need an appropriate loader to handle this file type`.  

My `.babelrc` is currently configured as follows.

```
{
	"presets": ["env", "react", "babel-polyfill"]
}
```

**Comment by izaera** [comment]
I feel this is related to #423 :thinking: 

I mean, this has to do with webpack configuration. Currently, the JS Toolkit is not passing every configuration you type in `.npmbuildrc` to webpack. Thus, if you need a more complex setup, it won't work OOB.
