### ISSUE TITLE
Importing external CSS into React Module

### ISSUE THREAD

**Issue by sgreco-dev** [liferay/liferay-frontend-projects#423]
## What is your question?

I am trying to determine how to configure the module to allow importing of CSS files into components.  I am following the instructions for the following package

[liferay-npm-bundler-loader-style-loader](https://www.npmjs.com/package/liferay-npm-bundler-loader-style-loader)

I am using version 

I am not really sure what I am doing wrong here.

.npmbundlerc
```
{
	"create-jar": {
		"output-dir": "dist",
		"features": {
			"js-extender": true,
			"web-context": "/component",
			"configuration": "features/configuration.json"
		}
	},
	"rules": [
		{
			"test": "\\.css$",
			"use": ["style-loader"]
		}
	],
	"dump-report": true
}
```

This results in the following error when attempting to import any .css file.

```
You may need an appropriate loader to handle this file type.
```

**Comment by izaera** [comment]
:thinking: That's not too much information to know what could be happening, but AFAIR the error you are referring to is printed by webpack, not the bundler, so you may need to tweak that...

**Comment by sgreco-dev** [comment]
> 🤔 That's not too much information to know what could be happening, but AFAIR the error you are referring to is printed by webpack, not the bundler, so you may need to tweak that...

Is there any documentation on how to modify the webpack config?  Is that something that I should be adding into .npmbundlerc and .npmbuildrc ?

I think that I showed above that I configured the style-loader as shown in the docs, but it is not working correctly.  My understanding was that adding that Liferay style loader package and adding the rule into the .npmbundlerc as shown in the docs would load the style loader, as shown above it is not.

If I add the rule with the style loader into the .npmbuildrc file. then`.webpack/webpack.config.js` is automatically generated as follows.

```
var path = require('path');

module.exports = {
	mode: 'development',
	devtool: 'source-map',
	entry: './index.js',
	output: {
		path: path.resolve(path.join(__dirname, 'build')),
		filename: 'webpack.bundle.js',
	},
	devServer: {
		open: true,
		openPage: '',
		
		proxy: {},
		publicPath: '/o/component/',
	},
	plugins: [new require('copy-webpack-plugin')(['../assets'])],
	module: {
		rules: [
  { test: /src\\.*\.js$/, use: 'babel-loader' },
  { test: /\.css$/, use: [ 'style-loader' ] }
],
	},
	resolve: {
		extensions: [ '.js' ]
	}
};

```

It seems like the docs for liferay-npm-bundler-loader-style-loader are incorrect from what I can tell.

**Comment by izaera** [comment]
OK, the misconception here may be that you are assuming that the webpack execution and the execution when your project is deployed to Liferay will match and that's not totally true.

The npm `start` target that runs webpack is provided as a helping tool to test what you are developing faster, but it was never intended as one to one mapping of what you will get when you deploy your project to Liferay. That means that it can happen that you get it working for Liferay, but not for webpack, the opposite, or make it work in both places. You could even, theoretically make it work different when running webpack and when executing on Liferay. 

For example, the file you are pasting above this comment, if configuring the [style-loader](https://www.npmjs.com/package/style-loader) of webpack to handle `.css` files which is different from configuring the [style-loader](https://www.npmjs.com/package/liferay-npm-bundler-loader-style-loader) of the npm-bundler to handle `.css` files.

Even if they are in the same project, they are two completely independent builds...

**Comment by izaera** [comment]
I'm going to close this one as answered. Feel free to reopen if you have further doubts.
