### ISSUE TITLE
Prepare liferay-changelog-generator for automated releases

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#43]
In https://github.com/liferay/liferay-npm-tools/issues/421 we discussed ways to further streamline the process of releasing packages. I'm creating this to summarize where we landed.

At the moment, the process consists of:

1. Update changelog (using `liferay-changelog-generator`).
2. `git add` the chanelog.
3. Run `yarn version` (which does the actual publish via `liferay-js-publish`).

The fundamental debate in liferay/liferay-npm-tools#421 is whether to strongly couple the tools together, but I think we arrived at a proposal that would enable the tools to work well together without actually coupling them at all.

We've now implemented liferay/liferay-npm-tools#408, which simplifies the task of passing a version to `liferay-changelog-generator` (ie. even in a monorepo that uses tags of the format `package-name/v1.2.3`, you can just pass `1.2.3` and it will infer the right prefix to use).

So the proposed end state is this: we *don't* want `liferay-chanelog-generator` calling `liferay-js-publish`, or vice versa. The desired integration can be achieved by configuration outside of the tools in the `package.json` file:

```json
{
	"scripts": {
		"preversion": "yarn ci",
	        "version": "npx liferay-changelog-generator --git-add",
		"postversion": "npx liferay-js-publish"
	}
}
```

When the package is currently at version `1.1.0` and the user runs `yarn version --new-version=1.2.0` (or `--patch`, `--minor`, `--major`) the following things happen:

- `yarn ci` runs with `npm_package_version` set to `1.1.0` in the environment. At this point, no commit or tag has been created.
- `liferay-changelog-generator` will run with `npm_package_version` set to `1.2.0` in the environment; we'll teach it to take the version from there in the absence of an explicit `--version` string. We'll also teach it to run `git add -p` in the presence of the `--git-add` switch. We can prompt the user for confirmation. At this point, Yarn still hasn't created the tag commit, but when it does, it will include the staged changes to the changelog.
- `liferay-js-publish` runs as before (among other things, pushes to GitHub, runs `yarn publish`). At the time. the commit and tag have been created.

So things to do to make all this work:

- [ ] Teach `liferay-changelog-generator` to read from `process.env.npm_package_version` in the absence of an explicit `--version` switch.
- [ ] Teach `liferay-changelog-generator` to support the `--git-add` switch.
- [ ] Update project configurations as per the `scripts` above.

Two final observations:

1. As I was writing this all out, I wondered whether we might want to make `--git-add` the default (seeing as we'll be prompting for confirmation, and we'll only be `git-add`-ing the `--outfile` (which defaults to `CHANGELOG.md`), this is quite safe). If projects use the recommended configuration people won't need to run `liferay-changelog-generator` explicitly anyway, so maybe it doesn't matter.
2. It bears thinking about what happens if things get interrupted during this flow. The reason I orignally made changelog generation a separate step was to give editors a chance to review the changes and tweak the generated output before committing it if need be. With this new process, the user can abort after generating the changelog (ie. during the `version` script), but it may not be so easy to resume from there afterwards; if they re-run `yarn version`, the changelog generator will re-run and complain like so:

```
error: ./CHANGELOG.md already contains a reference to liferay-changelog-generator/v1.4.0.
Did you mean to regenerate using the --regenerate switch?
Alternatively, proceed anyway by using the --force switch.
```

That error comes from wanting to guard against human error (and we did see this kind of error in liferay-js-themes-toolkit, where people would generate the changelog twice with the same version number). We'd need to think about how we want to handle this now. Options may include:

- Degrading that one from an error to a warning (on the assumption that the generator is mostly going to be invoked from a `version` script as described in this issue).
- Making the confirmation a prompt that runs *before* `git-add` and tells the user to edit the changelog in an external editor (eg. as opposed to just running `git add -p`).
- Getting rid of the confirmation and tolerating that fixes to the changelog may have to come *after* a given release.

Of this, the middle one is probably the best, even though it is rather awkward asking a user to open a file and then report back. I'm envisaged something that:

1.  Prints:
    
    > Changes to to CHANGELOG.md:
    
    and runs `git diff -- CHANGELOG.md` so that the user can see it.

2.  Prints:
    
    > If you want to make changes, edit the file in your editor. Press "y" when finished.
    
    (Pressing any other character would abort the whole business.)

**Comment by izaera** [comment]
It seems we are all happy with the current release process (or at least no one has complained for a long time), so I'm gonna close this.
