### ISSUE TITLE
Update to Babel 7 for JS Generator

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-projects#450]
### Issue type

-   [x] :gift: Feature request

### Description

**Desired behavior:**
The boilerplate generated by `yo liferay-js` when generating a React portlet by default allows usage of newer React syntax to be used and transpiled.

Based on https://github.com/ethib137/liferay-react-example which is a description of what needs to be done to update the necessary dependencies on a newly generated project, **steps 5,6 & 7 should be unnecessary**.

**Current behavior:**
The default set of dependencies is outdated and needs of manual steps to bring it up to date.

**Comment by jonmak08** [comment]
Adding https://issues.liferay.com/browse/IFI-2390 for reference.

**Comment by jonmak08** [comment]
Resolved and published with release https://github.com/liferay/liferay-frontend-projects/tree/liferay-js-toolkit/v2.24.3

**Comment by jbalsas** [comment]
Installation notes have been updated by @ethib137 at https://github.com/ethib137/liferay-react-example/commit/6f255b35051c902880f18473ab30bb52a7e55e1c. I assume they work... 😅 

Thanks @ethib137 for taking care of that! 🙇

**Comment by ethib137** [comment]
It's all working as expected! :) Thanks for the update everyone!
