### ISSUE TITLE
Add checks against devDependencies in liferay-portal

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#48]
We [don't want `devDependencies` to go in anywhere, except via `liferay-npm-scripts`](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/dev_dependencies.md).

Our Java-powered source-formatter is [supposed to stop these from getting in](https://github.com/liferay/liferay-portal/blob/ad9a7eb092afbc7f345a66c4b0202854b4cc9fbb/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/JSONPackageJSONCheck.java#L73), but I just saw it fail to stop [this PR](https://github.com/brianchandotcom/liferay-portal/pull/88585) which adds two items to the `devDependencies` of a module.

I don't know how that got through, because [only two modules have suppressions right now](https://github.com/liferay/liferay-portal/blob/ad9a7eb092afbc7f345a66c4b0202854b4cc9fbb/source-formatter-suppressions.xml#L145-L151).

Purpose of this ticket is to implement the check (even if that means redundantly) in liferay-npm-scripts, which is desirable anyway because it gives us fine-grained control over how we regulate dependencies.

We already have [a check that stops blacklisted `dependencies` from getting in](https://github.com/liferay/liferay-npm-tools/blob/68489aa3fff9e199a5032652852f949a29b765fc/packages/liferay-npm-scripts/src/scripts/check/preflight.js#L97-L142), and [the default blacklist](https://github.com/liferay/liferay-npm-tools/blob/7408f8ed913fc457943906a5a1de8146da53f297/packages/liferay-npm-scripts/src/presets/standard/index.js#L45) stops precisely the kind of unwanted dependency that is at issue in [#88585](https://github.com/brianchandotcom/liferay-portal/pull/88585). Note that we made it a `dependencies` check and not a `devDependencies` check because sneaking it in via `dependencies` is [how it got in last time](https://github.com/liferay/liferay-npm-tools/commit/82585653c2cabd8de999665fc0a9f9a1cf6221a5), and we believed that the Java source formatter was going to handle `devDependencies` for us.

All we have to do then, is broaden this mechanism to check `devDependencies` for us too.

**Comment by bryceosterhaus** [comment]
No longer needed since this is solved with out java SF
