### ISSUE TITLE
Teach `liferay-npm-scripts {check,fix}` about `$INIT_CWD`

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#483]
At the moment if you run `yarn run checkFormat` (or `yarn run format`) in an OSGi module that doesn't have a `package.json` file, `yarn` will walk up to the top-level `modules/` folder and run from there, which means _everything_ in the repo gets checked (slow).

Turns out `npm`/`yarn` both set `$INIT_CWD` so you can figure out where you originally started, which means we can scope our check/fix to that directory. This seems to be an undocumented feature, as far as I can tell (discovered it by logging `process.env` and inspecting), but it seems that we can leverage it if it's there, and degrade gracefully if it isn't.

**Comment by bryceosterhaus** [comment]
> Turns out npm/yarn both set $INIT_CWD

This is a great addition, had no idea that existed
