### ISSUE TITLE
Add lints against unguarded setTimeout/setInterval in React functional components

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#5]
Now that https://github.com/brianchandotcom/liferay-portal/pull/79828 has merged, we have `useTimeout` and `useInterval` hooks. We need a lint to catch unguarded `setTimeout` and `setInterval` and advise people to use the hooks instead.

Example of incorrect code:

```javascript
setTimeout(() => setSomething(true), 100);
```

Example of correct code:

```javascript
const delay = useTimeout();

delay(() => setSomething(true), 100);
```

Need to decide whether we want to allow explicit guards:

```javascript
setTimeout(() => {
    if (isMounted()) {
        setSomething(true);
    }
}, 100);
```

or timeouts which don't include (obvious) side effects:

```javascript
setTimeout(() => {
    strangeFunctionWhichSomehowWeKnowToBeSafeToCallEvenWhenUnmounted(); // 😂
}, 100);
```

(as opposed to just a blanket ban on `setTimeout` in functional components, which would be a simpler check and would force things to be more consistent.)

In the end we're going to need similar hooks and lints for a bunch of async patterns (`then()`, `requestAnimationFrame`, `debounce`, `throttle` etc), but this will be a good start.

**Comment by adamchenwei** [comment]
which PR this lint specifically get added if I may ask since its marked as complete? @bryceosterhaus @izaera @wincent

**Comment by bryceosterhaus** [comment]
@adamchenwei we didn't add this feature
