### ISSUE TITLE
Visual Studio code settings for prettier not working in Liferay workspace

### ISSUE THREAD

**Issue by allen-ziegenfus** [liferay/liferay-frontend-projects#51]
for liferay-npm-scripts there is some description about how to get liferay's prettier settings working in vs code: 

https://www.npmjs.com/package/liferay-npm-scripts?activeTab=readme#visual-studio-code

this however assumes you're working in portal and not in liferay workspace
by making these edit hacks i was able to get it to work for one of my modules in workspace:

```        //const root = getPortalRoot(filepath);
        const root = "/home/allenz/liferay/lfris-www/liferay/modules/apps/resources/resources-web";
        if (root) {
//              const modules = path.join(root, 'modules/node_modules');
                const modules = path.join(root, 'node_modules');
```

could that be built into the prettier wrapper script? that would be awesome!

**Comment by kresimir-coko** [comment]
Hey @allen-ziegenfus I picked this up a couple weeks ago, and then after investigating something else came up, so now I am kinda lost at the progress I made with the task.

So I'm coming at you with a couple questions. 
1. Could you please let me know how to set up the workspace properly (after following the [docs on creating a workspace](https://learn.liferay.com/dxp/latest/en/building-applications/tooling/liferay-workspace/creating-a-liferay-workspace.html#creating-a-liferay-workspace-with-blade-cli)) so that I can test this problem.
2. Please point me to the file you're applying this hack to (I know [where the original is](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/contrib/prettier/prettier.js#L1086), but where is the file that's bundled with the workspace?)

**Comment by bryceosterhaus** [comment]
@kresimir-coko, for setting up a workspace, I think you would just follow those docs you linked. [You also will need to install blade](https://learn.liferay.com/dxp/latest/en/building-applications/tooling/blade-cli/installing-and-updating-blade-cli.html). Once you have a workspace and blade installed, within the workspace directory you create a module with

```
blade create -t js-widget my-cool-module
```

You should then see that module at `your-workspace/modules/my-cool-module`

For the file, [we instruct developers to update their vscode prettier path](https://github.com/liferay/liferay-frontend-projects/tree/master/projects/npm-tools/packages/npm-scripts#visual-studio-code)
![Screen Shot 2022-02-03 at 12 10 13 PM](https://user-images.githubusercontent.com/6843530/152421004-908f6224-9d09-4075-8ef3-5f40161d903a.png)

I believe this is the file Allen is updating.

**Comment by kresimir-coko** [comment]
I made a fresh workspace with a fresh `js-widget` project, and it's pointing to the `prettier.js` file as it should.

Do I have to add `@liferay/npm-scripts` via npm/yarn?


`liferay-npm-scripts check` gives me this error:
```bash
kresimircoko@Kresimirs-MacBook-Pro my-cool-module % yarn check
yarn check v1.22.0
error "gulp-terser#terser#acorn@^8.5.0" doesn't satisfy found match of "acorn@6.4.2"
error "@liferay/js-toolkit-core#terser-webpack-plugin#terser#acorn@^8.5.0" doesn't satisfy found match of "acorn@6.4.2"
error Found 2 errors.
```

Here's the `liferay-npm-scripts build` error (with file setup):
![image](https://user-images.githubusercontent.com/24564752/152508507-fe4f10bf-3c60-4d6a-a27c-3d2c52887f89.png)

**Comment by bryceosterhaus** [comment]
@kresimir-coko [this is the location we are checking for the npm-scipts location](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/contrib/prettier/prettier.js#L1083-L1110). You'll notice we have conditions for both [liferay-portal](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/contrib/prettier/prettier.js#L1083) and also a condition for the [frontend-projects repo](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/npm-tools/packages/npm-scripts/contrib/prettier/prettier.js#L1110). We likely just need to add some logic here to check if it is a workspace and then locate the npm-scripts location.

We can probably assume a few things:
- the node_modules location for npm-scripts in a workspace would be at the root of the workspace. (`./node_modules/@liferay/npm-scripts`)
- There should be a root package.json to a workspace (`./package.json`)
- We know we are in a workspace if we walk up the directories and find a `settings.gradle` file and contains `apply plugin: "com.liferay.workspace"`

So you don't actually need to run any actual scripts. You will just add a package.json to your workspace with a dependency of npm-scripts and ideally when working on files in the workspace, prettier should auto-format in the vscode editor.

**Comment by kresimir-coko** [comment]
So the flow of operations is such:

1. Make a formatting mistake in `liferay-workspace/modules/my-cool-module/index.js`
2. Save triggers the prettier VSC plugin which calls our `~ /bin/prettier.js` config file
3. The prettier config file then looks for the `root` and determines whether the mistake has been made inside `liferay-portal`/`liferay-frontend-projects`/`liferay-workspace`
4. The prettier gets executed calling the script inside the `root/node_modules/@liferay/npm-scripts/src/scripts/prettier.js`

Am I correct @bryceosterhaus ?

I'm trying to figure out why I can't get any logging happening from either the `~ /bin/prettier.js` or the `root/node_modules/@liferay/npm-scripts/src/scripts/prettier.js` file. I have to somehow get the pathing correct, etc. and I'm not sure what's the alternative to console.logging stuff.
