### ISSUE TITLE
npm package for  liferay-frontend-theme-* needs to be updated

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-frontend-projects#513]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :eight: v8.x
-   [x] :nine: v9.x
-   [x] :keycap_ten: v10.x or higher

### Description

**Desired behavior:**
When using 'yo liferay-theme' for 7.3.x, package.json should have the updated following theme package:
"liferay-frontend-theme-styled": "5.0.15",
"liferay-frontend-theme-unstyled": "5.0.20,

**Current behavior:**
When using 'yo liferay-theme' for 7.3.x, package.json has the following:
"liferay-frontend-theme-styled": "5.0.0",
"liferay-frontend-theme-unstyled": "5.0.0"

This results in issues in portal_normal.ftl files

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**

**Comment by jonmak08** [comment]
Adding https://issues.liferay.com/browse/IFI-2450 for reference.

**Comment by izaera** [comment]
Mmm, we think this issue is incorrect per [this table](https://github.com/liferay/clay/wiki/Liferay-Portal-@clayui-css-Versions)

DXP 7.3 uses 5.x versions for those deps...

**Comment by izaera** [comment]
The themes toolkit generator creates projects based on a template that must work for all 7.3 versions of DXP so we should restrict it to the lower version, then it's up to the developer to upgrade his/her project when he needs it.

However, I see that you were targeting 7.3, so I wonder how you came to the conclusion that you needed 6.x versions... :thinking: Can you elaborate more on that taking into account my comments? Thx.

**Comment by fortunatomaldonado** [comment]
@izaera, I have updated the ticket to reflect the conversations and decision that "5.0.15" and "5.0.20" are acceptable for the default.
Thank for the info and https://github.com/liferay/liferay-frontend-projects/issues/516 to better understand what is required.
Let me know if there are any questions or comments about this.

**Comment by izaera** [comment]
This should be fixed by now. Please reopen it if it is not the case.
