### ISSUE TITLE
Some good eslint rules from plugin-unicorn

### ISSUE THREAD

**Issue by diegonvs** [liferay/liferay-frontend-projects#52]
Recently I took a look on this package: https://github.com/sindresorhus/eslint-plugin-unicorn/tree/master/docs/rules

and there are a lot good practices in there like:

## Patterns and Regex:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/better-regex.md (fixable)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/escape-case.md (fixable)

## Preventing side effects:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/consistent-function-scoping.md (not sure if it's fixable)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-array-find.md (This rule is fixable unless default values are used in declaration or assignment.)

## Readability:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/error-message.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-reduce.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-flat-map.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-includes.md
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/filename-case.md 
 (For us, pascal case :) )
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-reflect-apply.md (fixable but Reflect APIs doesn't have support on IE11)

## General JS Good Practices 
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/explicit-length-check.md (partly fixable?)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/new-for-builtins.md (not sure if it's fixable)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-negative-index.md (fixable)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-useless-undefined.md (fixable)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-unreadable-array-destructuring.md (not sure if it's fixable)

## DOM APIs Good Practices
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-modern-dom-apis.md (fixable but `node.replaceWith` doesn't have support for IE11)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-node-remove.md (fixable but `node.remove` doesn't have support for IE11)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-event-key.md (partially fixable and has a limited support on IE11 see https://caniuse.com/#feat=keyboardevent-key)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-text-content.md (fixable)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-dataset.md (fixable)
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-query-selector.md (partly fixable, I'm not sure if this rule can be too useful since getElementById is more faster than iterating over the DOM using querySelector 🤔 )

There are more rules but these ones(left some browser and node env rules) I consider more important to discuss.

From @wincent:

only(?) downside of using a sindresorhus package is he tends to love his dependencies: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/7781c3f3a424a330cbd6c33e8f76fbf651723ba2/package.json#L35-L49

having said that, we like automation and have a few things already in the queue for eslint-config-liferay. we should proceed carefully — if we just go in and turn on a swathe of third-party rules, the autofix ones might be great, but if there are ones that don't have autofixes and require lots of manual edits and verification in portal then the cost of rolling out will be high

**Comment by bryceosterhaus** [comment]
Closing for now, we can re-open if needed in the future
