### ISSUE TITLE
Dependencies issues on commerce-frontend-js module

### ISSUE THREAD

**Issue by garofalog** [liferay/liferay-frontend-projects#525]
### Issue type

-   :bug: Bug report
-   :gift: Feature request

### Description

Hello,
we Frontend Commerce Team and in these days we noticed a lot of errors compiling our frontend module.
The issue seems to due from recent changes on Liferay frontend main dependencies like `@liferay/frontend-js-react-web` and `frontend-js-web`.

We previously imported the liferay dependencies in this way in our `webpack.config.dev.js`:
```javascript
resolve: {
		alias: {
			'@liferay/frontend-js-react-web': path.resolve(
				__dirname,
				'../../../node_modules/@liferay/frontend-js-react-web/src/main/resources/META-INF/resources/js/index.es.js'
			),
			'frontend-js-web': path.resolve(
				__dirname,
				'../../../node_modules/frontend-js-web/src/main/resources/META-INF/resources/index.es.js'
			),
		},
		extensions: ['.js', '.jsx'],
	},
```
but the dependencies changed from javascript to typescript and ouy way to import the dependencies was broken.

Now we have found this way to keep the env works changing the previous code in something like this: 
```javascript
resolve: {
		alias: {
			'@liferay/frontend-js-react-web': path.resolve(
				__dirname,
				'../../../node_modules/@liferay/frontend-js-react-web/src/main/resources/META-INF/resources/js/index.ts'
			),
			'@liferay/frontend-js-state-web': path.resolve(
				__dirname,
				'../../../node_modules/@liferay/frontend-js-state-web/src/main/resources/META-INF/resources/index.ts'
			),
			'frontend-js-web': path.resolve(
				__dirname,
				'../../../node_modules/frontend-js-web/src/main/resources/META-INF/resources/index.es.js'
			),
		},
		extensions: ['.js', '.jsx', '.ts', '.tsx'],
	},
```
but this is a workaround so we see some issues when we use this updated code anyway:
<img width="759" alt="Schermata 2021-05-04 alle 12 32 25" src="https://user-images.githubusercontent.com/67319631/116991403-cac6c300-acd4-11eb-80f5-37ddb11f1a82.png">

The question might be "How we can fix this issue and keep working fluently without seeing this warnings?"

But we are aware about we should collaborate much more and that we built this environment to have a static and flexible way to develop frontend components without deploying everytime changes on liferay portal, while working only on frontend components.

So can we do something to integrate/collaborate better with your works?
Will you deliver for all frontenders a kind of unified static environement? (this will make short-term changes to our module useless)

**Desired behavior:**

**Repro instructions (if applicable):**
* Jump on this [PR](https://github.com/liferay-commerce/liferay-portal/pull/1053)
* Do `yarn && yarn watch` on `/liferay-portal/modules/apps/commerce/commerce-frontend-js`
* See the errors in console

**Other information (environment, versions etc):**
* Yarn 1.13
* Node lts/erbium

**Comment by bryceosterhaus** [comment]
Hey @garofalog I pulled down your PR and was checking it out. I think the issue lies in `ts-loader` and I don't think you actually need it. Check out [my commit here](https://github.com/bryceosterhaus/liferay-portal/commit/2dd4e95f73e1ea5401d888e6e7ffb0c7918576bd) and let me know if that works as expected

**Comment by bryceosterhaus** [comment]
@garofalog feel free to re-open if you are still running into issues.

**Comment by garofalog** [comment]
Hello @bryceosterhaus it worked fine, thank you!
