### ISSUE TITLE
Update @liferay/npm-scripts on older branches 

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#530]
Don't remember if I created an LPS for this somewhere, but dumping this here to flag a "risk" factor.

We have considerable drift in the versions of `@liferay/npm-scripts`/`liferay-npm-scripts` that we are using in different branches. At the time of writing:

- `master` uses `@liferay/npm-scripts` v44.0.1
- `7.3.x` uses `@liferay/npm-scripts` v34.0.0
- `7.2.x` uses `liferay-npm-scripts` v27.0.0
- `7.1.x` uses `liferay-npm-scripts` v12.0.0

This is technical debt, because it means we can't apply the same reasoning process about how build/linting/testing etc works in all places. But it would be very expensive to pay the debt down, because there is a bunch of bit rot due to the way changes get backported (ie. the older branches aren't necessarily very "clean", a lot of the stuff that gets backported is done in a very hasty/hacky/divergent way). There are a lot of major version bumps in there because many changes we make are small but breaking in the technical sense — it could be a new lint rule that is a bit stricter, or a small change to how config works... either way, updating on older branches doesn't mean backporting/cherry-picking but rather performing the update by hand, after very carefully studying the corresponding changelog.

So, it's a sticky situation. With this ticket, I just want to make sure it's on the radar as something that we may eventually have to tackle. In an ideal world, all branches would be _identical_, but in the real world we should note that in general keeping at least the _previous_ release branch (ie. 7.3.x right now) reasonably up-to-date is one of the cheaper things we could do, and simultaneously delivers the most benefit.

**Comment by izaera** [comment]
I doubt we will ever do this, given how much npm-scripts and eslint rules have changed lately and how long we have been unaligned. So, I will close this and we will backport things as needed, I guess.
