### ISSUE TITLE
css files under any node_modules directory not supported in jest

### ISSUE THREAD

**Issue by carloslancha** [liferay/liferay-frontend-projects#534]
We have a module where we're importing cropperjs and its css import `cropperjs/dist/cropper.css` and when we try to run the tests we get this error
```
This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html
    Details:
    /Users/carloslancha/Proyectos/liferay/portal/master/portal/modules/node_modules/cropperjs/dist/cropper.css:11
    .cropper-container {
    ^
    SyntaxError: Unexpected token .
```
I'm not sure where to place that config (and what would be the best one). Does any of you faced a similar problem before and could give me some guidance?

Failing in https://github.com/liferay-lima/liferay-portal/pull/1802/files

`yarn test` in `/modules/apps/item-selector/item-selector-taglib`

**Comment by bryceosterhaus** [comment]
I think you can mock it via jest config in  your package.json, something like...

```json
		"jest": {
			"moduleNameMapper": {
				"\\.(css)$": "<rootDir>/test/__mocks__/cssMock.js"
			}
		}
```

And then you would add the `./test/__mocks__/cssMock.js` file and it would just be an empty export

```js
module.exports = {};
```


Or, you might also be able to mock it just in that specific test file. I'm not sure if this is the exact syntax, but I think its something like this.
```js
jest.mock("cropperjs/dist/cropper.css", () => jest.fn());
```

**Comment by bryceosterhaus** [comment]
I just tested on your PR and adding the inline mock at the top of the test file seemed to get rid of the error (though another error appeared from the Liferay global).

**Comment by carloslancha** [comment]
Is there no other option? I mean, can't we support css files instead of having to mock them?

**Comment by izaera** [comment]
Why do you want to support anything? Are you really using the CSS content from JS code?

**Comment by izaera** [comment]
However, I would add [the proposed code](https://github.com/liferay/liferay-frontend-projects/issues/534#issuecomment-840017543) to `npm-scripts` so that we don't have different configurations lying around in liferay-portal. I think it makes sense as an OOB feature...

**Comment by carloslancha** [comment]
> Why do you want to support anything? Are you really using the CSS content from JS code?

To not having to mock it everytime we have a case like this one.

Anyway, after testing the solution I'm getting this two new errors (that wasn't happening before)

```
 FAIL  test/__mocks__/cssMock.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (../../../node_modules/@jest/core/build/TestScheduler.js:173:18)

 PASS  test/item_selector_preview/Footer.es.js
 PASS  test/item_selector_preview/Header.es.js
 PASS  test/item_selector_preview/Carousel.es.js
 FAIL  test/item_selector_preview/ItemSelectorPreview.es.js
  ● Test suite failed to run

    TypeError: Cannot read property 'UPLOAD_SERVLET_REQUEST_IMPL_MAX_SIZE' of undefined

      547 | 	maxFileSize: Config.oneOfType([Config.number(), Config.string()])
      548 | 		.setter('_convertMaxFileSize')
    > 549 | 		.value(Liferay.PropsValues.UPLOAD_SERVLET_REQUEST_IMPL_MAX_SIZE),
          | 		                           ^
      550 |
      551 | 	/**
      552 | 	 * The return type for the uploaded item.

      at Object.<anonymous> (src/main/resources/META-INF/resources/repository_entry_browser/js/ItemSelectorRepositoryEntryBrowser.es.js:549:30)
      at Object.<anonymous> (src/main/resources/META-INF/resources/index.es.js:16:1)
      at Object.<anonymous> (src/main/resources/META-INF/resources/item_selector_preview/js/ItemSelectorPreview.es.js:16:1)
      at Object.<anonymous> (test/item_selector_preview/ItemSelectorPreview.es.js:18:1)
```

**Comment by izaera** [comment]
`Liferay.PropsValues` needs to be mocked too, since it is an API from the portal

**Comment by carloslancha** [comment]
But why it's failing now? (that's code from 2 years ago)

**Comment by izaera** [comment]
The problem with the CSS transform is [this line](https://github.com/liferay/liferay-frontend-projects/blob/f97ae3e0a79b7f9e583bf48294a37539d6e8cdfc/projects/npm-tools/packages/npm-scripts/src/config/jest.config.js#L27) that is disabling transforms for any file coming from `node_modules`.

I don't know why we do that so I'm going to investigate it...

**Comment by carloslancha** [comment]
nice, thx @izaera !

**Comment by izaera** [comment]
[Here](https://github.com/liferay/liferay-npm-tools/commit/12d9bc435bb522e19755ecb45c2047c04eaf30ff#diff-c99ffb3236953a6159ea099c2345c9ffdde98884b5e1488bc35e930145c1eebc)'s the reason why we added that `transformIgnorePatterns`:

> Note also that I had to set up `transformIgnorePatterns` because once we
> have rewritten own-project references, we want to make sure that we
> require the files that we actually built (with `buildSoy`) rather than
> falling through to our `transformSoy` stub).

So it's apparently a restriction to avoid using invalid files. I will try to move that restriction to the transformer so that we can remove the `transformIgnorePatterns` :crossed_fingers:

**Comment by carloslancha** [comment]
Greg's shadow is long

**Comment by izaera** [comment]
Apparently the `/node_modules/` transform ignore pattern is part of [jest's default](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring) so I will try to fix it with a resolver instead (to be safer)...

**Comment by bryceosterhaus** [comment]
> Is there no other option? I mean, can't we support css files instead of having to mock them?

It is pretty common to mock thing in jest tests, especially static assets and [they even recommend mocking them manually](https://jestjs.io/docs/webpack#handling-static-assets).

I think it is good idea to mock css imports at the npm-scripts level, but I think it is also pretty common and good practice to manually mock modules that are specific to a given test suite. For example, we wouldn't want to mock cropperjs at the npm-scripts level if it is only really used in 1 or 2 modules.
