### ISSUE TITLE
Provide some way for the `bundler` to infer a preset based on the configured target plaform

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#542]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [X] :two: v2.x
-   [ ] :three: v3.x

### Description
Based on:

- https://issues.liferay.com/browse/LPS-132149
- https://github.com/izaera/fat-jar-sample/issues/1

We need to provide some way for the `bundler` to infer a preset based on the configured target plaform.

A possible way would be to make the bundler scan all direct dependencies of the project and, if one of them is a preset, use it if nothing else is configured in `.npmbundlerrc`. We should, of course, fail the build if more than one target platform is found.

That would allow us to implement points 1 and 4 of https://github.com/izaera/fat-jar-sample/issues/1

**Comment by izaera** [comment]
At first glance I though that scanning direct project dependencies for presets would be enough, but that could be a breaking change because now we are applying the default preset when nothing is specified even if the project has preset dependencies.

I know it's very strange that a project has preset dependencies that it doesn't use, but I prefer to be correct than break things outside. We never know what users are doing with the tools, so it's not fair to break things.

For that reason, we will need something to tag autopreset projects so that `liferay-npm-bundler` knows when it is safe to auto-apply them on absence of any preset configuration. Following the same pattern we use in themes, I'll use the `keywords` in `package.json` for that purpose so that only presets tagged as `liferay-npm-bundler` + `autopreset` are taken into account.

I've run a [search for autopreset in npmjs.com](https://www.npmjs.com/search?q=autopreset) and it yields nothing, so it looks like a good tag for this.

**Comment by izaera** [comment]
:thinking: There may be a better way to detect if a preset is an autopreset: if a project has a direct dependency that is itself a preset and that dependency has a direct dependency to `liferay-npm-bundler` (i.e: it brings `liferay-npm-bundler` to the project's build as our target platforms do) then it's an autopreset :tada: .

That doesn't break anything of what we've already released (because our current presets don't have dependencies to `liferay-npm-bundler`) and it's also (almost) impossible that anyone is doing such thing outside, because it would lead to cyclic dependencies. Also, in case they are doing it, chances are that they do it for the same purpose.

So, implementing the autopreset like this :point_up: would be -technically and theoretically- a breaking change, but not then, in Real Life :tm: .

I think I'll go this way instead of using keywords...

**Comment by bryceosterhaus** [comment]
🎉  I like this solution much better than relying on keywords.

**Comment by izaera** [comment]
See https://github.com/liferay/liferay-frontend-projects/pull/576#discussion_r647403461 where this feature is slightly modified
