### ISSUE TITLE
Use Babel 7 in target platforms

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#543]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [X] :two: v2.x
-   [ ] :three: v3.x

### Description
Based on:

- https://issues.liferay.com/browse/LPS-132149
- https://github.com/izaera/fat-jar-sample/issues/1

Create a new loader to invoke Babel 7 similar to [the current one for babel 6](https://github.com/liferay/liferay-frontend-projects/tree/109e64d1a0394b3262faa61adb991ad224bc8373/maintenance/projects/js-toolkit/packages/liferay-npm-bundler-loader-babel-loader).

But this time create it in `liferay-npm-build-support` as we do for adaptations, to stop extending the number of packages in the JS Toolkit.

**Comment by izaera** [comment]
We may as well invoke babel from the target platform script [just before the bundler](https://github.com/liferay/liferay-frontend-projects/pull/546/files#diff-8cbe038698a422a3fbb09f05c95e2c11d84cf9b9cdf7c1903d66b1f876475d3dR31) if we don't want to add another loader.

In that case, we would change the target script and [remove this rule](https://github.com/liferay/liferay-frontend-projects/pull/546/files#diff-88aa9e0cf5efff761ae7035c7f3a73af7844e64cbd2b3b3dadad63d0061b8ec6R182-R194)

**Comment by bryceosterhaus** [comment]
I agree, I think we should invoke it within the platform script, that way we align closer to npm-scripts for a potential future merge.

**Comment by izaera** [comment]
I have changed the description of the task based on the previous comment.

**Comment by nhpatt** [comment]
+1 to @bryceosterhaus comment, I would call it from the platform script.
