### ISSUE TITLE
Add Liferay.Util.sub() to default mocks in test environment

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#55]
As per [this thread](https://liferay.slack.com/archives/CNBG06JS3/p1594204672332000).

To replace local mocks like [this one](https://github.com/liferay/liferay-portal/blob/3994ec2ec702175c32939899392b6159acc423f3/modules/apps/layout/layout-content-page-editor-web/test/page_editor/app/plugins/comments/components/MappingSelector.test.js#L126-L128).

**Comment by kresimir-coko** [comment]
Related to #947
