### ISSUE TITLE
Decide possible layouts of config files for the JS Toolkit

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#551]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Description

Based on [this conversation](https://github.com/liferay/liferay-frontend-projects/pull/547#pullrequestreview-663309228) we should decide what the final structure of a JS Toolkit project should be.

Specifically, we need to know:

1. If we want to have a `liferay-cli` tool 
2. What standard configuration files (babelrc, eslint, etc) will be standalone, which will be embedded in our tools (and how), which will be inferred
3. Will he have the same layout for different developer roles: portal, pure js portlets, blade, etc? Or different ones?

**Comment by izaera** [comment]
[This conversation](https://github.com/liferay/liferay-frontend-projects/pull/546#discussion_r634759875) may be related too.

**Comment by bryceosterhaus** [comment]
1. Would love to see a cli tool in the future, but I don't think it is necessary quite yet. We can let our tools stabilize a bit before deciding to create a more global tool. Plus we got to remove gulp first 🙏 

2. I think we should allow config files for any 3rd party (babel, eslint, etc). However, we shouldn't require that they have it. We should have defaults for those and then they only use them if they want to override. And then for our own tooling, I think if we can get to a single config file for all liferay js related things, that would be great. Not sure how doable that is, but it seems ideal to only have to look at one place.

3. If we can unify them all, that would be great. But we may want to first aim for two cases, internal and external. Once we reach some stability with those two cases, we can analyze how much they really need to differ and then aim to merge at some point.

**Comment by bryceosterhaus** [comment]
And from your comments on the other PR.

> from the portal's POV, the bundler is something we want to hide, but from the customers' POV the bundler is really a tool. 

For those that use the bundler directly, are those always more advanced use cases or do we just hide it in portal because of npm-scripts?

> In the worst case scenario we could always generate the current bridges we have in portal, check them into git and delete the bridge creator tool forever.

Removing the necessity of the bridge file would be a nice win for us. Plus I ❤️  deleting things forever.

**Comment by izaera** [comment]
> 1. Would love to see a cli tool in the future, but I don't think it is necessary quite yet.

:+1: 

> 2. if we can get to a single config file for all liferay js related things, that would be great

That was the idea behind the refactor I did in the JS Toolkit to have [the Project class](https://github.com/liferay/liferay-frontend-projects/tree/master/maintenance/projects/js-toolkit/packages/liferay-npm-build-tools-common/src/project). 

That package (liferay-npm-build-tools-common) was supposed to be a common library to be able to deal with all our different types of projects (themes, toolkit, and possibly future projects). In fact, we introduced dependencies to it from npm-scripts and themes-toolkit, but then the bundler 3 effort came into scene and everything was left in an undetermined state because we didn't know what exactly was going to happen. Now that we know we won't be using webpack federation, we may want to revisit this again in the future.

In any case, as I was saying, that package is a common library-only interface to our projects so that we (and customers, for example, though that was not the main goal) may read config files agnostically. That is: the bundler interfaces with the Project class to obtain its configuration and that class reads and normalizes (sets defaults and puts values in canonical forms) the npmbundlerrc file. So, as it is now, we may change the Project class and point it to any other file (or feed it in-memory values from an umbrella tool) and the bundler will get its configuration transparently.

If we had another class like this for the Themes Toolkit we would be able to (for example):

1. Have a single file (f.e: npmscripts.config.js) with all liferay related config in portal (then we would point the bundler and themes Project classes to read from it) and still use npmbundlerrc or the package.json+liferay-theme.json in themes in customer's projects.
2. Move everything to package.json (I argued against this already, but just to show it's a possibility with the Project architecture)
3. Create umbrella tool(s) that read the config from other place and inject it to the bundler, themes, whatever, as it is possible to do with tools like Babel now. This would allow, for example, customers to do their own tools with their workflows.
4. Create smart Project implementations that infer configuration values from the environment (imagine, for example, generating imports on-the-fly for Liferay portal, based on some other file, or reading the yarn.lock, or something like that).

In general, I think that, as long as we decouple configuration retrieval/normalization from the tools execution we are good to go. 

Also, this model has the benefit that, if we make the Project class read/write, we may also use it from yeoman generators to create new projects. And customers could also use them, too.

> 3. If we can unify them all, that would be great....

I agree. I think we won't be ever be able to unify them because of how different the lifecycles are (in portal it is much faster and driven by Java, for customers we sure want more stability and adhere to frontend standards), but let's hope :sweat_smile: . We have the middle way, though: make agnostic tools like the bundler that are then used in slightly different ways in different places (bundler is now used from blade, portal and js toolkit and something similar happens with themes). It's just a matter of having a sensible architecture for this.

**Comment by izaera** [comment]
> For those that use the bundler directly, are those always more advanced use cases or do we just hide it in portal because of npm-scripts?

Not sure what you mean... :thinking: As I see it, there are 5 types of user:

1. People using bundler from blade: usually more backend guys that have some needs to bundle JS, but it's not their main goal. Sometimes it can be also due to some specific need from the backend (exotic configuration dialogs or things like that) that the frontend guys may need.
2. People using the bundler itself (JS Toolkit) to develop template projects (as we offer them in the generator)
3. People using the bundler in [custom workflows they've made](https://github.com/liferay/liferay-frontend-projects/issues/541) (I linked one example, but I think there are a few more IINM)
4. Portal using the bundler inside npm-script
5. People developing React fragments: very specific use case where the fragments toolkit invokes the bundler under the hood, but the user doesn't care (at least yet) about bundler things (transparent).

We may want to hide the bundler as much as possible for cases 1, 4 and 5

We may want to put an umbrella tool over the bundler in case 2 (liferay cli, or something like that) because a typical build is more than the bundling alone (think of eslint, soy, scss, etc). In the past I used to think that we would be able to do everything from the bundler (the bundler would be the tool to drive the whole build and, in addition, bundle the things) but now I think it's a bad idea. It's better to let each tool do its things and then compose from bottom to top IMO.

We definitely want to expose the bare bundler for 3, whether as a CLI tool or -better- as a small library like babel does.

> Removing the necessity of the bridge file would be a nice win for us. Plus I :heart:  deleting things forever.

![like and follow](https://media.giphy.com/media/3o6nUXaNE4wdhq8Foc/giphy.gif)

**Comment by bryceosterhaus** [comment]
I'm not really sure what I meant either after re-reading that comment... 🤷‍♂️ 

-----

> In general, I think that, as long as we decouple configuration retrieval/normalization from the tools execution we are good to go.

👍  👍  Agreed.

> We may want to hide the bundler as much as possible for cases 1, 4 and 5

Totally agree.

> We may want to put an umbrella tool over the bundler in case 2 (liferay cli, or something like that) because a typical build is more than the bundling alone (think of eslint, soy, scss, etc)

This makes sense to me. I think we can defer eslint and formatting type stuff to whoever consumes it. For example, in`@liferay/npm-scripts`, we need to include eslint, ts, prettier etc because it's aimed at a single use case (dxp) and so we can just leverage the bundler from npm-scripts.  And then for something like blade or external use, we probably only want to provide bundling of js and sass and not the extra js utilities.


Overall, I think we are on the same page and headed in the right direction.

**Comment by izaera** [comment]
I'm closing this. We may revisit file layout in the future if/when it is needed.
