### ISSUE TITLE
Create a project generator for target platforms

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#556]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [X] :two: v2.x
-   [ ] :three: v3.x

### Description
We need to decide if we are going to add target platforms to the current Liferay JS Generator, or create the new `@liferay/cli` tool and start migrating things from Liferay JS Generator to it.

Note that, we may also want to stop using Yeoman in `@liferay/cli`, which seems logical. Given that the current Liferay JS Generator was written to avoid excessive coupling with Yeoman, this shouldn't be very difficult.

**Comment by nhpatt** [comment]
I would create a new @liferay/cli instead of adding it.

-- comments link to this same issue

**Comment by bryceosterhaus** [comment]
I'm fine with either migrating the js generator to a new package, or we could also just use the js generator from our new package. The benefit of migrating it over would be less publishing and versions to worry about and since it is a generator, I don't think people are really going to be leveraging it in a custom way like they would the bundler.

**Comment by izaera** [comment]
What do you think is better?

1. A single command, like `liferay new my-app`, to create a new project with sensible defaults (for now we would only use the one and only platform we have)
2. One command per different target, like `liferay new react my-app`, as our generator currently does

I would go with 1 and then -maybe- provide another command in `@liferay/cli` to switch target platforms, so that the user can, for example, say:

```sh
$ liferay new my-app
...
Created a new JS project for target platform 7.4-GA1

$ liferay target 7.3
Switched target platform to 7.3

$ liferay target react
Switched target platform to React
```

However, I don't know how difficult it would be to switch from -say- `7.4-GA1` to `react` because the configuration of the project can be quite different.

Also, it maybe doesn't make too much sense to create a project for `7.4-GA1`, then switch it to `react`, then switch it to `angular`.

An option that comes to mind is to simply refuse to switch to an invalid/incompatible target platform, or something like that. But still we have the case where the user may want to use Angular instead of React and `liferay new` is creating a React based project.

**Comment by izaera** [comment]
OK, maybe there's another simple option: make it a wizard, like the current generator, and ask the user what she wants to do.

That way `liferay new` would be the only way to run it, and it would let the user create anything she likes (like the current `yo liferay-js`).

**Comment by bryceosterhaus** [comment]
I like the wizard approach + allowing sub-commands if it's not too much of a hassle to maintain. Benefit of the wizard is that it guides people through, and they typically won't be creating multiple modules every day so they won't use the cli often. And then the benefit of having subcommands, people can copy/paste from docs directly or we can offer better support by saying "run this command ..." instead of helping them through the wizard.

I'm not sold on my example below, but maybe something like it. I trust your judgement with this though

```bash
# wizard
$ liferay new
[x] - app
    Target:
    [] - 7.4-GA1
    [x] - 7.3-GA4
    [] - React
    [] - Angular
[] - theme
    [] - 7.4
    [] - 7.3


# sub commands
$ liferay new app react
$ liferay new app 7.4
$ liferay new theme 7.4


# Future commands
$ liferay build
$ liferay deploy


# This is a stretch but I thought it could be interesting
# "7.4" would grab the latest target release on that platform
# The path would be the bundle you are deploying the jar to
$ liferay deploy 7.4 /my/path/to/my/bundle
```

**Comment by nhpatt** [comment]
The switching in the single command solution seems complicated and error prone, because there will be invalid switches and you can't easily know/inform them in advance and looks that can have a lot of edge case.

I'll also like wizard + sub commands, that's basically what most CLI do.

**Comment by bryceosterhaus** [comment]
Yeah, I would also say let's not worry about upgrading their target version quite yet. That can get complicated quickly.
