### ISSUE TITLE
Liferay Bundler/Babel doesn't understand the spread-operator

### ISSUE THREAD

**Issue by faragos** [liferay/liferay-frontend-projects#565]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [ ] :three: v3.x

### Description
I'm trying to use [Recoil ](https://recoiljs.org/docs/introduction/getting-started) for State-management. Now recoil uses the spread operator and babel fails then when it tries to add the Liferay.bundler.define around it, because it doesn't know the token.

**Desired behavior:**
The liferay-bundler can parse files with the spread-operator

**Current behavior:**
The liferay-bundler ignores these files

**Repro instructions (if applicable):**

1. install recoil
2. import it
3. build it
4. check the builded files. there should be no Liferay.Loader.define around it.

**Other information (environment, versions etc):**
Liferay 7.3.6
![es6-fail](https://user-images.githubusercontent.com/10152106/120434972-6a7f7b80-c37d-11eb-886b-63640facfbc4.png)

Maybe there are more ES6 features that would also be nice that babel understands it, but at the moment I think the spread-operator is the important one.

**Comment by izaera** [comment]
That fixes it :point_up:

**Comment by izaera** [comment]
We will try to release a new version with this fix next week.

**Comment by izaera** [comment]
This should be fixed in version 2.25.0 of the toolkit (already released).
