### ISSUE TITLE
Documentation for bundler version 3

### ISSUE THREAD

**Issue by jwanner83** [liferay/liferay-frontend-projects#570]
### Issue type

-   [x] :thinking: Question
-   [ ] :bug: Bug report
-   [x] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version

-   [x] :two: v2.x
-   [x] :three: v3.x

### Description
I tried migrating a portlet from npm bundler 2 to 3 and got the message that the file `.npmbundlerrc` isn't supported anymore. I was searching for a documentation on how to use the new liferay npm bundler (@liferay/npm-bundler) but couldn't find any documentation whatsoever. 

**Desired behavior:**
It would be nice to have a page or a readme where the new functionalities are described, and it is explained how to use it. Or maybe even have a migration guide (as it exists for v1 to v2: https://learn.liferay.com/dxp/latest/en/developing-applications/tooling/other-tools/liferay-npm-bundler/bundler_migration_guide.html?highlight=npm%20bundler)

**Current behavior:**
I couldn't find any readme or any page where it is documented on how to use it.

**Comment by izaera** [comment]
Bundler 3 is not officially released, we are only using it internally, but its development was stopped to investigate webpack federation and it's unclear when we will retake it (though it looks like we will mid-term).

So, until that happens there won't be any official support or docs, sorry.

**Comment by izaera** [comment]
I'm closing this as answered to remove it from the pending issues list, but feel free to add more comments if necessary :+1:

**Comment by jwanner83** [comment]
Okay, thanks for the clarification. 👍
