### ISSUE TITLE
Dependency vulnerability Fix Request - dot-prop and merge

### ISSUE THREAD

**Issue by AndrewWJordan** [liferay/liferay-frontend-projects#571]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [ ] :gift: Feature request
-   [x] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [ ] :three: v3.x

### Description
Dependabot alerted us to two high severity vulnerabilities related to the `liferay-npm-bundler` and the `dot-prop` and `merge` dependencies. The bundler is currently used as a dev dependency so I am wondering if these issues are even relevant in the context of the frontend. If someone could confirm this, that would be great!

dot-prop info:
- Path: `liferay-npm-bundler > insight > conf > dot-prop`
- More info: `https://npmjs.com/advisories/1213`

merge info:
- Path: `liferay-npm-bundler > liferay-npm-build-tools-common > merge`
- More info: `https://npmjs.com/advisories/1666`

**Desired behavior:**
Resolve high severity vulnerabilities 

**Current behavior:**
npm audits result in a couple high severity vulnerabilities 

**Repro instructions (if applicable):**
`npm audit`

**Other information (environment, versions etc):**
We are currently using version 2 of the npm bundler.

**Comment by izaera** [comment]
> The bundler is currently used as a dev dependency so I am wondering if these issues are even relevant in the context of the frontend. If someone could confirm this, that would be great!

Not really, because `liferay-npm-bundler` is not used in production (if that's your question :thinking: ). Any issue in this package could only affect the developer using it.

Of course you could think of an scenario where the developer machine is attacked to inject something in production by modifying the build, but the risk of that happening is probably extremely low and the motivation needed to forge such type of attack would need to be huge.

**Comment by AndrewWJordan** [comment]
Thanks! I think that answers my question. I see now that my question could have been posed better. Sorry for any confusion.

**Comment by izaera** [comment]
>  I see now that my question could have been posed better. Sorry for any confusion.
No worries :raised_hands:
