### ISSUE TITLE
Liferay Bundler doesnt wrap built code inside Liferay.Loader when certain packages are used

### ISSUE THREAD

**Issue by rv-clavis** [liferay/liferay-frontend-projects#573]
Recently I used a few packages for my vue-typescript project and it so happens that sometimes, when certain packages are used such as vee-validate, it will build my project but cant wrap it inside this Loader:

`Liferay.Loader.define('my-component/index.common'....`

For example, try building TS / Vue project using the following Package....
https://www.npmjs.com/package/vee-validate

**Comment by izaera** [comment]
Can you please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

And if it keeps failing, can you attach the resulting report file from step 2 of the linked troubleshooting guide? It will probably show why the bundler is failing to do its duties.

Thx.

**Comment by izaera** [comment]
I've edited the comment above to remove the `before reporting anything` part. I copied it from other place and forgot to edit it.

Looked quite harsh :grimacing: . Sorry about that.

**Comment by izaera** [comment]
@rv-clavis Just in case you didn't get notified :point_right: https://github.com/liferay/liferay-frontend-projects/issues/573#issuecomment-855677653

**Comment by rv-clavis** [comment]
Oh hey zaera. Thanks for your response (a lot was going on at work). I will send you the report today :)
Im curious what the reason may be.

**Comment by kresimir-coko** [comment]
Hi @rv-clavis, is this still an issue?

Here's the [gist of the report](https://gist.github.com/kresimir-coko/4655f05e1d8eee762895f6bf78c0ea7e) I got generated,  and [here's the content ](https://gist.github.com/kresimir-coko/afe1bd9792e854457ccdf6f9ff657bb3)of the `index.js` file inside the generated JAR, which indicates the fact that it is being properly wrapped by `Liferay.Loader`.

If it's still an issue, feel free to reopen 👍
