### ISSUE TITLE
Investigate using a plugin for sorting interface keys

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#579]
liferay-portal is pretty picky on sorting keys in an object and so we might want to investigate keeping consistency here by adding an eslint plugin for sorting objects and type definitions. Below is the type of code we want to sort.

```ts
interface PresetInfo {
    name: string;
    isAutopreset: boolean; // this should be before "name"
}
```

**Comment by izaera** [comment]
Please see [this comment](https://github.com/liferay/liferay-frontend-projects/pull/576#discussion_r647992354). AFAIK we already have a lint for sorting keys (it's not very friendly, though, but it does the trick).

However, linting is disabled for JS Toolkit v2.

**Comment by brunofernandezg** [comment]
Test comment. Ignore
