### ISSUE TITLE
License checker for dependencies

### ISSUE THREAD

**Issue by diegonvs** [liferay/liferay-frontend-projects#58]
While navigating thru open source code this weekend I found this documentation and the implementation for a "dependency-linter-like" script.

From script docs:

```
<rootDir>/licenses-to-fail-config.js
This file can export a list of allowed licenses for your project in addition to the default allowed set of this tool. (See licenses-to-fail documentation)

/* allowedLicenses.js */
module.exports = ['MIT-X']
```

### See: 

Docs: https://github.com/microsoft/essex-alpha-build-infra/blob/main/packages/scripts/docs/audit.md#license-to-fail
Code(?): https://github.com/microsoft/essex-alpha-build-infra/blob/main/packages/steps/audit/src/index.ts (It may took some time to see what can be done)

**Comment by bryceosterhaus** [comment]
Will re-open if this becomes and issue for us
