### ISSUE TITLE
Enforce import of "atlas-variables", not "atlas"

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#59]
Came up in Slack again (sorry, private links) [yesterday](https://liferay.slack.com/archives/G3JBR21HA/p1596609554431100?thread_ts=1596541545.375900&cid=G3JBR21HA) ([previously](https://liferay.slack.com/archives/G015CFV9U5C/p1592398480006400), which references discussion in [other](https://liferay.slack.com/archives/C25TXMD63/p1591263042012900) [places](https://liferay.slack.com/archives/CNBG06JS3/p1590482533121400)).

The most common pattern in liferay-portal (`git grep 'import.+atlas'`) is to import just the variables. If you import `'atlas'`, you are probably doing it wrong, because it is effectively including Clay twice (once from the theme, then again in your local module):

- [modules/apps/adaptive-media/adaptive-media-web/src/main/resources/META-INF/resources/adaptive_media/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/adaptive-media/adaptive-media-web/src/main/resources/META-INF/resources/adaptive_media/css/main.scss#L1)
- [modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/css/main.scss#L1)
- [modules/apps/calendar/calendar-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/calendar/calendar-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/change-tracking/change-tracking-web/src/main/resources/META-INF/resources/dynamic_include/ChangeTrackingIndicator.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/change-tracking/change-tracking-web/src/main/resources/META-INF/resources/dynamic_include/ChangeTrackingIndicator.scss#L1)
- [modules/apps/contacts/contacts-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/contacts/contacts-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/css/components/_multi_panel_sidebar.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/css/components/_multi_panel_sidebar.scss#L1)
- [modules/apps/depot/depot-web/src/main/resources/META-INF/resources/css/Languages.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/depot/depot-web/src/main/resources/META-INF/resources/css/Languages.scss#L1)
- [modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/ddm.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/ddm.scss#L1)
- [modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/document_library_preview.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/document_library_preview.scss#L1)
- [modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/main.scss#L1)
- [modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/image_gallery_display/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/image_gallery_display/css/main.scss#L1)
- [modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/css/main.scss#L1)
- [modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/FragmentEditor.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/FragmentEditor.scss#L1)
- [modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/FragmentPreview.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/FragmentPreview.scss#L1)
- [modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/Fragments.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/Fragments.scss#L1)
- [modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/SourceEditor.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/SourceEditor.scss#L1)
- [modules/apps/frontend-compatibility/frontend-compatibility-ie/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/frontend-compatibility/frontend-compatibility-ie/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/main.scss#L1)
- [modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/portal/_item_selector_preview.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/portal/_item_selector_preview.scss#L1)
- [modules/apps/frontend-image-editor/frontend-image-editor-web/src/main/resources/META-INF/resources/ImageEditor.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/frontend-image-editor/frontend-image-editor-web/src/main/resources/META-INF/resources/ImageEditor.scss#L1)
- [modules/apps/frontend-theme/frontend-theme-admin/src/css/_imports.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/frontend-theme/frontend-theme-admin/src/css/_imports.scss#L1)
- [modules/apps/frontend-theme/frontend-theme-admin/src/css/clay.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/frontend-theme/frontend-theme-admin/src/css/clay.scss#L1)
- [modules/apps/frontend-theme/frontend-theme-classic/src/css/_imports.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/frontend-theme/frontend-theme-classic/src/css/_imports.scss#L1)
- [modules/apps/frontend-theme/frontend-theme-classic/src/css/clay.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/frontend-theme/frontend-theme-classic/src/css/clay.scss#L1)
- [modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/clay/atlas/_variables.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/clay/atlas/_variables.scss#L1)
- [modules/apps/headless/headless-discovery/headless-discovery-web/src/js/App.es.js:17](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/headless/headless-discovery/headless-discovery-web/src/js/App.es.js#L17)
- [modules/apps/invitation/invitation-invite-members-web/src/main/resources/META-INF/resources/invite_members/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/invitation/invitation-invite-members-web/src/main/resources/META-INF/resources/invite_members/css/main.scss#L1)
- [modules/apps/journal/journal-web/src/main/resources/META-INF/resources/css/ddm_form.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/css/ddm_form.scss#L1)
- [modules/apps/journal/journal-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/css/common.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/css/common.scss#L1)
- [modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/css/miller_columns/DragPreview.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/css/miller_columns/DragPreview.scss#L1)
- [modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/css/miller_columns/MillerColumns.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/css/miller_columns/MillerColumns.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/AllowedFragments.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/AllowedFragments.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/DisabledArea.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/DisabledArea.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/DragPreview.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/DragPreview.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/DropZone.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/DropZone.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Layout.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Layout.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/LayoutViewport.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/LayoutViewport.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/NetworkstatusBar.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/NetworkstatusBar.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/PreviewModal.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/PreviewModal.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Sidebar.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Sidebar.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Toolbar.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Toolbar.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Topper.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Topper.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Translation.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/Translation.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/floating-toolbar/ContainerStylesPanel.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/floating-toolbar/ContainerStylesPanel.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/floating-toolbar/RowStylesPanels.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/floating-toolbar/RowStylesPanels.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/fragment-content/FragmentContent.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/fragment-content/FragmentContent.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/layout-data-items/RowWithControls.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/layout-data-items/RowWithControls.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/undo/UndoHistory.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/undo/UndoHistory.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/common/components/Collapse.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/common/components/Collapse.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/common/components/ColorPalette.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/common/components/ColorPalette.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/common/components/InlineConfirm.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/common/components/InlineConfirm.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/comments/components/FragmentComment.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/comments/components/FragmentComment.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/contents/components/ContentsSidebar.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/contents/components/ContentsSidebar.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/experience/components/ExperienceToolbarSection.scss:2](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/experience/components/ExperienceToolbarSection.scss#L2)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/fragments-widgets/components/FragmentsSidebar.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/fragments-widgets/components/FragmentsSidebar.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/fragments-widgets/components/SearchResultsPanel.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/fragments-widgets/components/SearchResultsPanel.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/fragments-widgets/components/TabItem.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/fragments-widgets/components/TabItem.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/fragments-widgets/components/TabsPanel.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/fragments-widgets/components/TabsPanel.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-design-options/components/PageDesignOptions.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-design-options/components/PageDesignOptions.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-structure/components/ItemConfiguration.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-structure/components/ItemConfiguration.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-structure/components/PageStructureSidebarSection.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-structure/components/PageStructureSidebarSection.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-structure/components/StructureTree.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-structure/components/StructureTree.scss#L1)
- [modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-structure/components/StructureTreeNode.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-structure/components/StructureTreeNode.scss#L1)
- [modules/apps/layout/layout-seo-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/layout/layout-seo-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/login/login-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/login/login-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/css/main.scss#L1)
- [modules/apps/monitoring/monitoring-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/monitoring/monitoring-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/portal-settings/portal-settings-web/src/main/resources/META-INF/resources/users_admin/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/portal-settings/portal-settings-web/src/main/resources/META-INF/resources/users_admin/css/main.scss#L1)
- [modules/apps/portal-workflow/portal-workflow-task-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/portal-workflow/portal-workflow-task-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/product-navigation/product-navigation-applications-menu-web/src/main/resources/META-INF/resources/css/ApplicationsMenu.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-applications-menu-web/src/main/resources/META-INF/resources/css/ApplicationsMenu.scss#L1)
- [modules/apps/product-navigation/product-navigation-control-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_control_menu.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-control-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_control_menu.scss#L1)
- [modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/AddPanel.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/AddPanel.scss#L1)
- [modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/App.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/App.scss#L1)
- [modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/Collapse.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/Collapse.scss#L1)
- [modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/ContentOptions.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/ContentOptions.scss#L1)
- [modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/DragPreview.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/DragPreview.scss#L1)
- [modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/TabItem.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/TabItem.scss#L1)
- [modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/TabsPanel.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/css/TabsPanel.scss#L1)
- [modules/apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_product_menu.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_product_menu.scss#L1)
- [modules/apps/product-navigation/product-navigation-product-menu-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-product-menu-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/product-navigation/product-navigation-simulation-theme-contributor/src/main/resources/META-INF/resources/css/simulation_panel.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/product-navigation/product-navigation-simulation-theme-contributor/src/main/resources/META-INF/resources/css/simulation_panel.scss#L1)
- [modules/apps/questions/questions-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/questions/questions-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/ratings/ratings-taglib/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/ratings/ratings-taglib/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/redirect/redirect-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/redirect/redirect-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/css/SiteNavigationMenuEditor.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/css/SiteNavigationMenuEditor.scss#L1)
- [modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/staging/staging-configuration-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/staging/staging-configuration-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/style-book/style-book-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/style-book/style-book-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/subscription/subscription-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/subscription/subscription-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/user-groups-admin/user-groups-admin-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/user-groups-admin/user-groups-admin-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/css/main.scss#L1)
- [modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/css/main.scss#L1)
- [modules/dxp/apps/segments/segments-experiment-web/src/main/resources/META-INF/resources/css/_click-goal.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/dxp/apps/segments/segments-experiment-web/src/main/resources/META-INF/resources/css/_click-goal.scss#L1)
- [modules/sdk/gradle-plugins-css-builder/src/gradleTest/compileClayCssWithRuby/src/main/resources/css/main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/sdk/gradle-plugins-css-builder/src/gradleTest/compileClayCssWithRuby/src/main/resources/css/main.scss#L1)
- [modules/util/sass-compiler-jni/src/test/resources/com/liferay/sass/compiler/jni/internal/dependencies/clay-css/atlas-variables.scss:5](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/util/sass-compiler-jni/src/test/resources/com/liferay/sass/compiler/jni/internal/dependencies/clay-css/atlas-variables.scss#L5)
- [modules/util/sass-compiler-jni/src/test/resources/com/liferay/sass/compiler/jni/internal/dependencies/clay-css/atlas.scss:5](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/util/sass-compiler-jni/src/test/resources/com/liferay/sass/compiler/jni/internal/dependencies/clay-css/atlas.scss#L5)
- [modules/util/sass-compiler-jni/src/test/resources/com/liferay/sass/compiler/jni/internal/dependencies/clay-css/site/site-atlas-font-awesome.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/util/sass-compiler-jni/src/test/resources/com/liferay/sass/compiler/jni/internal/dependencies/clay-css/site/site-atlas-font-awesome.scss#L1)
- [modules/util/sass-compiler-jni/src/test/resources/com/liferay/sass/compiler/jni/internal/dependencies/clay-css/site/site-main.scss:1](https://github.com/liferay/liferay-portal/blob/9b5ee1b6d26d8/modules/util/sass-compiler-jni/src/test/resources/com/liferay/sass/compiler/jni/internal/dependencies/clay-css/site/site-main.scss#L1)

**Comment by kresimir-coko** [comment]
There are no more usages of `import 'atlas'`
