### ISSUE TITLE
Notify users of new versions of `@liferay/cli`/platforms

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#590]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [X] :two: v2.x
-   [X] :three: v3.x

### Description
Notifiy users of new versions of `@liferay/cli`/platforms (as per [this conversation](https://github.com/liferay/liferay-frontend-projects/pull/584#issuecomment-861316722)).

**Comment by nhpatt** [comment]
Mmm... you mentioned in the other thread to recommend people updating the CLI. I would go the same path as the blade tool is currently doing (that I don't really know)

**Comment by izaera** [comment]
>  I would go the same path as the blade tool is currently doing (that I don't really know)

It has an update command (and uses `jpm` under the hood):

```sh
ivan@baco:~ $ blade
Usage: blade [command] [command options]
  Commands:
    extension install      Installs an extension into blade.
      Usage: extension install [options] [path]

    extension uninstall      Uninstalls an extension from blade.
      Usage: extension uninstall [options] [name]

    help      Get help on a specific command
      Usage: help [options] [name]

    init      Initializes a new Liferay workspace
      Usage: init [options] [name]

    open      Opens or imports a file or project in Liferay IDE.
      Usage: open [options] [file | directory]

    samples      Generate a sample project
      Usage: samples [options] [name]

    sh      Connects to Liferay and executes gogo command and returns output.
      Usage: sh [options]

    update      Update blade to latest version
      Usage: update [options]

    version      Show version information about blade
      Usage: version [options]

To see more command options, run "blade init" to create a workspace
```

So, basically we would be doing the same thing but in a frontend friendly manner: suggesting to use `npm` to update (or maybe even running it from `@liferay/cli` if possible...)

**Comment by nhpatt** [comment]
👍 I would go the easy path with just suggesting.

**Comment by izaera** [comment]
Yup. 

> The easy path is the only path (for me)

![fire](https://media.giphy.com/media/e5kbmb3wX3J1S/giphy.gif)

**Comment by izaera** [comment]
I've been evaluating alternatives to do the update check and I think I will go with [update-check](https://www.npmjs.com/package/update-check).

@bryceosterhaus proposed [update-notifier](https://www.npmjs.com/package/update-notifier) which is the one we already used before, but based on Greg's teachings :sweat_smile: , I think we may use the other one because `update-notifier` has 14 direct dependencies (some of them, like `chalk`, `is-ci`, `is-yarn` and `xdg-basedir` not really so needed), whereas `update-check` has only 2 (both for fetching the data).

Also, `update-check` is implemented in one single file and license is MIT, so we can always copy-paste it in our project (if we ever need it), then evolve.

What do you think?

**Comment by bryceosterhaus** [comment]
> based on Greg's teachings

Let us open up to page 234 in the 4th volume of "The Book of Greg on Dependencies"™️  


`update-check` looks great to me. Vercel is pretty great so I ~blindly~ trust most things they make

**Comment by nhpatt** [comment]
Update-check FTW! 2 is better than 14 in almost all the areas :P

**Comment by bryceosterhaus** [comment]
I'd rather have 14 candies than 2. just saying..

**Comment by nhpatt** [comment]
![](https://media.giphy.com/media/l3q2IGmSdIMKaW1J6/giphy-downsized.gif)
