### ISSUE TITLE
Add `deploy` support to `@liferay/cli` projects

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#591]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [X] :two: v2.x
-   [X] :three: v3.x

### Description
We need some way to deploy projects for target platforms as we did before with `liferay-npm-build-support` for the other project types.

My initial proposal is to put this auxiliary code inside `@liferay/js-toolkit-core` and keep it as simple as possible to avoid the problems we had in previous versions of the JS Toolkit (we even had code to translate labels which AFAIK, nobody ever used and could have been extracted to a different tool).

I suggest using `@liferay/js-toolkit-core` because it will be our toolkit library/API so all shared code should go there. We attempted doing these things in a modular fashion in JS Toolkit v2 but it never proved more benefitial than the monolythic approach, so this time we may start putting everything there and extract afterwards if necessary (for example, for deprecation purposes). In any case, things in `@liferay/js-toolkit-core` should be cohesive (that rules out the possibility to include translation for labels) so that it makes sense as an API and shared dependency.

We will need to find a balance.

**Comment by izaera** [comment]
As per [this conversation](https://github.com/liferay/liferay-frontend-projects/pull/584#discussion_r651324868) it is possible that we may need to move the `build` process to the same place, too.

**Comment by izaera** [comment]
Turns out that we also had [js-toolkit-scripts](https://github.com/liferay/liferay-frontend-projects/tree/master/projects/js-toolkit/packages/js-toolkit-scripts) that was an attempt to migrate [liferay-npm-build-support](https://github.com/liferay/liferay-frontend-projects/tree/master/maintenance/projects/js-toolkit/packages/liferay-npm-build-support) to Toolkit v3.

Thus, we now have:

1) `@liferay/cli`
2) target platform embedded scripts (`build`, `deploy`, ...)
3) `@liferay/js-toolkit-core`
4) `@liferay/js-toolkit-scripts`
5) `liferay-npm-build-support`

Which all serve the same purpose :roll_eyes: 

It would be great to ~add six or seven more parallel projects~ leave just one, but while we shift from v2 to v3 (whatever it might be) and from the yeoman generator to `@liferay/cli` we will need to have at least:

3) `@liferay/js-toolkit-core`
5) `liferay-npm-build-support`

However, for the rest, we may simply:

1) `@liferay/cli`: *delegate to `@liferay/js-toolkit-core`*
2) target platform embedded scripts: *delegate to `@liferay/js-toolkit-core`*
4) `@liferay/js-toolkit-scripts`: *remove it*

**Comment by nhpatt** [comment]
looks sensible to me :)

**Comment by izaera** [comment]
Turns out it's not that sensible :shrug: 

For example: if we move the current [build script](https://github.com/liferay/liferay-frontend-projects/blob/master/target-platforms/packages/portal-7.4-ga1/build.js) to `@liferay/js-toolkit-core` we will need to introduce dependencies to `@babel/core` inside the latter.

Maybe babel is not so bad, but think what can happen if we add eslint, jest, or whatever to the mix. Potentially we may need to add functionally-duplicate dependencies as we begin to support specific builds for Angular, Vue, etc.

That would mean that any tool in the JS Toolkit would end up depending on a bunch of disparate dependencies where most of them are not even used.

So, what's the alternative? :thinking: Probably modularize (as I said in first term, and argued against)...

The truth is that each type of project we generate will have different needs and, potentially, different builds. And the thing that characterizes the project is the "target platform", so that's probably the best place to place these tasks.

Maybe we can create "target platforms" like react, angular, vue, etc. in the future for the old react/angular/vue portlet projects and extract any common code to proper shared places which we evolve as the code evolves (but outside of `@liferay/js-toolkit-core`). These places would be opaque to the user, so we can refactor them as much as we like, because the only touch point the user sees is the target platform package.

----

There's also a consideration we have to make: there are tasks that are project target dependent (build may not be the same for portal, angular, or vue), and others that may be applied to any project type (deploy is always the same). So it is clear (to me) that at least we need:

1) a package for platform agnostic tasks (this could really go in `@liferay/js-toolkit-core` if we wanted)
2) one package per target platform with specific needs
3) maybe some packages which can be applied to subsets of target platforms (in case there's something that applies to vue and react, but not angular, for example).

However 3 can be deferred, I guess... Maybe it is not even needed because everything is exclusively platform specific or generic.

Going to give this another thought after lunch... :shallow_pan_of_food:

**Comment by bryceosterhaus** [comment]
> There's also a consideration we have to make: there are tasks that are project target dependent (build may not be the same for portal, angular, or vue)

We could possibly delegate to the npm script first, meaning if `build` exists in the package.json then run that. That way we could generate react, angular, etc portlets with specific build scripts.

But overall, I trust your direction with this and the amount of thought you've put into it.

![](https://media.giphy.com/media/WOTy1eGhHMezIllLD8/giphy.gif)
