### ISSUE TITLE
Format hex color codes in JSON files

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#61]
Brought up here: https://github.com/liferay-frontend/liferay-portal/pull/368#discussion_r484553713

Context from thread:

> > @wincent, I thought we had a rule for this? This is of course a json file, so it won't apply here, but wondering if the rule is all lowercase now as seen in the .scss in this same PR.
> 
> You basically said it:
> 
> * We don't enforce anything like this inside JSON.
> * "We" do enforce it in SCSS, by which I mean, Prettier enforces it (to lowercase).
> 
> I think we could pretty easily do this in JSON using liferay-npm-scripts, at least for the obvious case; ie:
> 
> * Strings exactly matching `/^[a-f0-9]{3,6}$/i`.
> 
> I mean, you might end up formatting something you don't meant to format (eg. a hashtag ... 🤦‍♂️) but we could always ignore such edge case if it ever came up.
> 
> Created [liferay/liferay-npm-tools#494](https://github.com/liferay/liferay-npm-tools/issues/494) to track this.

**Comment by izaera** [comment]
Closing this as OP thinks it's not so important.
