### ISSUE TITLE
eslint rule for avoiding AUI

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#617]
### Issue type (mark with `x`)

-   [x] :gift: Feature request

### Description

We should create a set of rules that disallows the use of common AUI utilities that are now available in browsers. For example, `A.one` vs `document.querySelector`. Another example would be a default Liferay API, `Liferay.Util.openModal` instead of AUI modal.

First step is coming up with a list of AUI utils to lint against.

**Comment by kresimir-coko** [comment]
### List of AUI utils to lint against

- `A.one` => `document.querySelector`
- `A.Array` => use the [native Array class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array)
- `A.getBody` => this is a shortcut to `A.one('body')`, use `document.querySelector`
- `A.Object` => use the [native Object class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)
- `A.DataType.DateMath` => use the [native Date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
- `A.Node` => use native methods, mostly found inside the `Document` interface
- `A.Date` => [native Date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
- `A.each` => use Array methods to iterate over items
- `A.io.request` => use the [native Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
- `A.all` => use `document.querySelectorAll`
- `A.merge` => use `Object.assign`
- `A.Lang.sub` => use `String.replace`
