### ISSUE TITLE
CSS format: Require SCSS files starting with "_" are being imported in some SCSS file

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-frontend-projects#63]
If an SCSS file starts with an underscore is not going to be compiled, other SCSS file has to load it by an `@import '_filename'`.

> This rule prevents the possibility to have files what actually are not in use

Require SCSS files starting with "_" are being imported in some SCSS local file by `@import '_filename'`

Examples of **correct** code:

```
_file_to_import.scss exist.
main_file.scss :
- @import 'file_to_import';
```

Examples of **incorrect** code:

```
_file_to_import.scss exist.
main_file.scss :
- No file import';
```

**Comment by bryceosterhaus** [comment]
Closing. Will re-open later if we ever decide to do this.
