### ISSUE TITLE
Enforce new line after imports

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#649]
We should make sure to enforce a new line after import declarations.

Valid
```js
import * as foo from 'foo'

const FOO = 'BAR'
```

```js
import * as foo from 'foo'
import * as baz from 'baz'

const FOO = 'BAR'
```

Invalid
```js
import * as foo from 'foo'
const FOO = 'BAR'
```

A rule may already exist for this somewhere

**Comment by kresimir-coko** [comment]
This rule exists ([sourcecode](https://github.com/import-js/eslint-plugin-import/blob/main/src/rules/newline-after-import.js) & [docs](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/newline-after-import.md). But it's not a native eslint rule. Should we make our own or perhaps use this one?

**Comment by bryceosterhaus** [comment]
I think we can try the existing plugin and then run some metrics to see how slow the plugin is. If it adds a considerable about of time for linting, then we can write our own. I think it might be fine though to add.

In order to check metrics I think you just add an env variable. [See this issue for some previous metrics I ran](https://github.com/liferay/liferay-frontend-projects/issues/705)

**Comment by bryceosterhaus** [comment]
Gonna close as this isn't super important and we don't have the capacity for it
