### ISSUE TITLE
Custom HTML while bootstrapping Angular app

### ISSUE THREAD

**Issue by JaviManteiga** [liferay/liferay-frontend-projects#658]
### Issue type (mark with `x`)

-   [x] :thinking: Question
-   [ ] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [ ] :three: v3.x

### Description

I have a portlet written in Angular and it takes a little bit of time to load so I would like to add a loading animation or similar (like the one is tipically added in the main tag of the index.html file) because a user will not see anything while the app is bootstraping. I have been searching through the docs but I couldn't find anything related to this. Am I missing something? Is there a way to achieve this already?

Thanks in advance

**Comment by bryceosterhaus** [comment]
@JaviManteiga unfortunately I don't think we currently provide a way to do this via our generated js portlets.

cc @izaera my guess is that you have looked into this before, any recommendations?

**Comment by izaera** [comment]
Nope. I think someone mentioned it long ago, but I don't remember what was the conclusion...

However, if it is a regular portlet (not an adapted one), maybe tweaking the CSS or adding code in the entry point so that a GIF or something like that is rendered from the very moment the function is invoked may do it. Though, in any case, you would have a lag at least between the HTML is rendered and the entry point in invoked.

Other than that, you may try to create a mixed Java/JavaScript portlet with `blade`, which gives you full control over what you can do inside portlet's lifecycle.

I'm closing this as answered, but feel free to keep the conversation going on if needed :+1:

**Comment by JaviManteiga** [comment]
Thank you for the answers. My project has been developed using the generator-liferay-js library and I've already tried the first option @izaera mentioned but the problem is that most part of the lag still exists. As for the second option, I'm not familiar with blade, is "mixed Java/JavaScript portlet" a template? 

Since yesterday, I've been looking for alternatives and I came up with a workaround (I haven't tested it yet) I think It could work but any comment would be appreciated:

- Create a page fragment with the loading animation
- Include the portlet as a widget
- Write some JS code in the fragment that checks periodically if a HTML tag id exists. This tag id was included in the widget code, obviously. Once is found, remove the loading animation.

I know this means a link between the widget internal code and the page fragment itself but I couldn't find any other alternatives.

**Comment by nhpatt** [comment]
> blade, is "mixed Java/JavaScript portlet" a template?

Yes, you have several templates like:

10: npm-angular-portlet
11: npm-react-portlet
12: npm-vuejs-portlet

Documentation is here: https://help.liferay.com/hc/en-us/articles/360018164591-Blade-CLI

**Comment by izaera** [comment]
> I know this means a link between the widget internal code and the page fragment itself but I couldn't find any other alternatives.

It's a coupling yes, but it sounds reasonable, as long as you (the developer) fully control the page design.

**Comment by JaviManteiga** [comment]
I've been testing the blade CLI npm-angular-portlet and the problem would still be the same because It's loading de Angular app through the main.ts file. The only advantage would be that I could use my workaround directly in the view.jsp file and I wouldn't need to create the fragment. By the way, I tested my idea and It works as expected.

Thanks for the help!

**Comment by izaera** [comment]
@JaviManteiga Yep, when I said to try the blade approach I was referring exactly to that: take advantage of the JSP to render the placeholder, then remove it from JavaScript.

But as you said, placing a coupled fragment next to the pure JavaScript portlet would do it too :+1: .
