### ISSUE TITLE
We should warn when a wrong version of `node` is used in DXP

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/liferay-frontend-projects#659]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [x] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Description

**Desired behavior:** When running `yarn` inside `liferay-portal/modules` with a wrong Node version, the task should be terminated and an error explaining why it happened should be printed out.

**Current behavior:** When running `yarn` inside `liferay-portal/modules` with a wrong Node version, the task is completed unsuccessfully with a lot of not useful errors being thrown and `yarn.lock` not being generated.

**Repro instructions (if applicable):** Use node version 12+ when running `yarn` inside `liferay-portal/modules`.

**Comment by bryceosterhaus** [comment]
I'm not sure if it is possible to check against anytime `yarn` is run. One thought would be to add a simply message in npm-scripts that checks the node version and says "You are using Node version YOUR_VERSION, DXP uses DXP_VERSION" if there is a version difference.

**Comment by izaera** [comment]
There's this :point_right:  https://yarnpkg.com/features/plugins, but it's for yarn 2 :-(

Not sure if there's an equivalent for yarn 1...

**Comment by kresimir-coko** [comment]
We can do whatever, I know that I have fallen into a trap of using the latest version of `node` without even knowing, because `nvm` defaulted to it. I've since then changed my default version, but to avoid someone in the future falling into the same trap we should warn somehow.

I don't know how that whole thing (running yarn and our control over it) works yet, but if we can add a warning at the end of the yarn log of which node version was used and which one we recommend would be enough.

**Comment by izaera** [comment]
I think we can close this since there's no way we can implement it because we would have to wrap `yarn` to first do the check :shrug:

**Comment by izaera** [comment]
What do you think @kresimir-coko @bryceosterhaus ?

**Comment by kresimir-coko** [comment]
Makes sense, lets close. It would be a good feature, but as you said - not easily implemented
