### ISSUE TITLE
CSS format: ~Disallow~ Advice about using of shorthand

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-frontend-projects#67]
~Disallow~ Advice about using of [shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties)

> **Rationale**: It can help to avoid the unuseful rewrite of properties, typical example like:
> - `padding: 5px; padding-down: 0;`
> - It can help to create a more configurable CSS by variables

Examples of **correct** code:

```
.example {
   padding-top: 5px;
   padding-right: 2px;
}
```

Examples of **incorrect** code:

```
.example {
   padding: 5px 2px 0 0;
}
```

**Comment by kresimir-coko** [comment]
I see we've decided to go for a written documentation in our guidelines. @eduardolundgren can you perhaps tackle this?

**Comment by bryceosterhaus** [comment]
@kresimir-coko I think you meant to tag @eduardoallegrini

**Comment by bryceosterhaus** [comment]
And I think @eduardoallegrini is now @edalgrin

**Comment by kresimir-coko** [comment]
Oh, probably autocomplete yea, good catch!

**Comment by edalgrin** [comment]
Yeah sure, actually we might be able to upgrade to the new logical properties at once https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties 👍

**Comment by kresimir-coko** [comment]
Any updates on this @edalgrin?

**Comment by edalgrin** [comment]
Sorry, I've been stuck on another task and on PTO so I couldn't advance on this. I can start working on a draft next week but are we sure that's what we need now? (priority)

**Comment by kresimir-coko** [comment]
Probably not a priority @edalgrin, I'll keep the issue open then. I just wanted to see if it was closeable 👍

**Comment by bryceosterhaus** [comment]
Closing. Will re-open later if we ever decide to do this.
