### ISSUE TITLE
CSS format: Disallow using !important

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-frontend-projects#68]
CSS format: Disallow using !important

> **Rationale**: !important have a very strong proposal and when it is used the final user is forced to add  !important to his CSS to be able to overwrite the propertie, so its a very useful property for final customers but not for who is trying to create a modular and customizable CSS code.
> In order to create a really customizable CSS we can disallow the use of !important

Examples of **correct** code:

```
.example {
   color: red;
}
```

Examples of **incorrect** code:

```
.example {
   color: red !important;
}
```

**Comment by kresimir-coko** [comment]
@marcoscv-work what do we wanna do with this one?

**Comment by bryceosterhaus** [comment]
Closing. Will re-open later if we ever decide to do this.
