### ISSUE TITLE
CSS format: Alert if a variable not exist

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-frontend-projects#69]
Check if the variable exists, if not and it is a new variable it has to be written with “!default”. 

> **Rationale**: New variables should be configurable by adding `!default`. which allows developers to overwrite our variables at the very top instead of somewhere in the middle.
> If the variable has not !default we will assume the variable is already declared.

Examples of **correct** code:

```
`$new-variable: true !default;`
`$exist-variable-to-overwrite: true;`
```

Examples of **incorrect** code:
```
`$new-variable: true;`
`$exist-variable-to-overwrite: true;`
or
`$new-variable: true;`
`$exist-variable-to-overwrite: true !default;`
```

**Comment by kresimir-coko** [comment]
@marcoscv-work is this still a thing?

**Comment by bryceosterhaus** [comment]
Closing. Will re-open later if we ever decide to do this.
