### ISSUE TITLE
Lint against explicit use of default npm bundler preset in liferay portal

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#7]
Just like we did in https://github.com/liferay/eslint-config-liferay/issues/130 to stop redundant instances of `@babel/preset-react`/`@babel/preset-env` in liferay-portal, we should do the same for `.npmbundlerrc` and the default preset ("liferay-npm-bundler-preset-liferay-dev"), which applies — unless configured otherwise — wherever we use the bundler via [this config file in liferay-npm-scripts](https://github.com/liferay/liferay-npm-tools/blob/fd5b7f51151bdeb8280f2c2edd0de7c0f5c88f26/packages/liferay-npm-scripts/src/config/npm-bundler.json).

As was the case with `.babelrc` and `.eslintrc`, we need to force the usage of `.npmbundlerrc.js` instead of just `.npmbundlerc` (JSON) so that ESLint can actually process the config. If we do this, we get this and any other linting/formatting "for free". I don't know whether the bundler is currently equipped to read ".js" files though, so changes may be needed there in order for this to happen.

**Comment by bryceosterhaus** [comment]
Gonna close as we don't have the capacity for it. Will re-open in future if necessary
