### ISSUE TITLE
CSS format: Alert using BEM directive

### ISSUE THREAD

**Issue by marcoscv-work** [liferay/liferay-frontend-projects#70]
Warning if we are using BEM directive, we should use Bootstrap/Clay convention
Uses of: `--` or `__`

> **Rationale**: BEM is great but we are not following it, it can build a (from my point o view) more complex structure, and we have decide follow the Boostrap convention.

Examples of **correct** code:

```
.block {
   &__element {
      ...
   }

   &--modifier {
      ...
  }
} 
```

Examples of **incorrect** code:

```
.block {
   .element {
      ...
   }
} 

.block-modifier {
      ...
}
```

**Comment by kresimir-coko** [comment]
@marcoscv-work do we still want to lint against this?

**Comment by bryceosterhaus** [comment]
Closing. Will re-open later if we ever decide to do this.
