### ISSUE TITLE
Upgrade node-sass to make it work for node LTS (14) and current (16)

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#700]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [X] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :eight: v8.x
-   [ ] :nine: v9.x
-   [X] :keycap_ten: v10.x or higher

### Description

**Desired behavior:**

We are committed to make tooling work for at least LTS and, when possible, current versions of node.

**Current behavior:**

Right now the Themes Generator is failing to install for node 16 because we depend on node-sass 14.4.1 (determined running `yarn why node-sass` in this repo) which is intended to be used from node 14 (as shown in [the package description](https://www.npmjs.com/package/node-sass)).

**Repro instructions (if applicable):**

See [LPP-42803](https://issues.liferay.com/browse/LPP-42803)

**Comment by bryceosterhaus** [comment]
> we are removing node-sass from liferay-portal

![](https://media.giphy.com/media/3o6Mbolqx8Ses8KXoQ/giphy.gif)

**Comment by brunofernandezg** [comment]
Test comment (ignore)
