### ISSUE TITLE
CDN access issue

### ISSUE THREAD

**Issue by dev-mamun** [liferay/liferay-frontend-projects#734]
https://cdn.lfrs.sl/alloyui.com/combo/combo.php is not accessible on UK

**Comment by izaera** [comment]
@dev-mamun Can you please elaborate a bit more? 

Why do you use that URL for? Why do you know it is blocked...?

Thx :-)

**Comment by dev-mamun** [comment]
i did not use that URL directly its in-built within a WordPress plugin datetime picker. previously it was accessible from UK but plugin was not working on UK recently. i check and find out plugin code try to load data from this CDN url.

**Comment by izaera** [comment]
I see...

So, what's the WordPress plugin?

And why do you think that URL is related to this GitHub project?

I'm trying to find out if it is related to us or not... :thinking:

**Comment by izaera** [comment]
Closing this as more than 15 days without response passed. Feel free to reopen :-)

**Comment by vidurbharany** [comment]
he combo.php file seems to be unavailable on https://cdn.lfrs.sl/alloyui.com/combo/combo.php

Where else can I access it as it's part of my application? Thanks.

**Comment by bryceosterhaus** [comment]
@vidurbharany you'll have to contact the maintainer of the wordpress plugin you are using, they need to update their code to use a different CDN. See https://liferay.dev/blogs/-/blogs/notice-repository-cdn-url-change for details

**Comment by vidurbharany** [comment]
Thank you @bryceosterhaus . It's actually being used in a PHP application that a developer did for me a few years back and he cannot be contacted now. I just need to know where can I access this file again, so with my limited programming skills I can update the old path with the new one for the combo.php file. This will be a big help to me if you can share the new path or point me in the direction of the developer of this combo.php file please. Thank you again!

**Comment by izaera** [comment]
It's explained in the linked blog entry, right? :thinking: 

> The old one is of the form:
>
> https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/...
>
> Recently though Liferay switched to a new CDN provider and are using a newer URL. You might have seen this if you have upgraded your blade or have started working with 7.1.
>
> The new one is of the form:
>
> https://repository-cdn.liferay.com/nexus/content/groups/public/...
