### ISSUE TITLE
Create target platforms for 7.4, 7.3, 7.2, and 7.1 versions

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#749]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :two: v2.x
-   [X] :three: v3.x

### Description
Create target platforms for 7.4, 7.3, 7.2, and 7.1 versions, as discussed in points 2 and 3 of #740.

See PR at #750

**Comment by izaera** [comment]
<table>
<tr>
	<td>DXP Version
	<td>NPM Package
	<td>NPM Version
<tr>
	<td> 7.4.3.4-ga4
	<td> portal-7.4
	<td> 4.0.0
<tr>
	<td> 7.4.2-ga3
	<td> portal-7.4
	<td> 3.0.0
<tr>
	<td> 7.4.1-ga2
	<td> portal-7.4
	<td> 2.0.0
<tr>
	<td> 7.4.0-ga1
	<td> portal-7.4
	<td> 1.0.0
</table>

**Comment by izaera** [comment]
https://github.com/liferay/liferay-frontend-projects/pull/750

**Comment by brunofernandezg** [comment]
Test comment - Ignore

**Comment by izaera** [comment]
<table>
<tr>
	<td>DXP Version
	<td>NPM Package
	<td>NPM Version
<tr>
	<td> 7.3.7-ga8
	<td> portal-7.3
	<td> 8.0.0
<tr>
	<td> 7.3.6-ga7
	<td> portal-7.3
	<td> 7.0.0
<tr>
	<td> 7.3.7-ga6
	<td> portal-7.3
	<td> 6.0.0
<tr>
	<td> 7.3.7-ga5
	<td> portal-7.3
	<td> 5.0.0
<tr>
	<td> 7.3.7-ga4
	<td> portal-7.3
	<td> 4.0.0
<tr>
	<td> 7.3.7-ga3
	<td> portal-7.3
	<td> 3.0.0
<tr>
	<td> 7.3.7-ga2
	<td> portal-7.3
	<td> 2.0.0
<tr>
	<td> 7.3.7-ga1
	<td> portal-7.3
	<td> 1.0.0
</table>

**Comment by izaera** [comment]
<table>
<tr>
	<td>DXP Version
	<td>NPM Package
	<td>NPM Version
<tr>
	<td> 7.2.1-ga2
	<td> portal-7.2
	<td> 2.0.0
<tr>
	<td> 7.2.0-ga1
	<td> portal-7.2
	<td> 1.0.0
</table>

**Comment by izaera** [comment]
<table>
<tr>
	<td>DXP Version
	<td>NPM Package
	<td>NPM Version
<tr>
	<td> 7.1.2-ga4
	<td> portal-7.1
	<td> 4.0.0
<tr>
	<td> 7.1.2-ga3
	<td> portal-7.1
	<td> 3.0.0
<tr>
	<td> 7.1.2-ga2
	<td> portal-7.1
	<td> 2.0.0
<tr>
	<td> 7.1.2-ga1
	<td> portal-7.1
	<td> 1.0.0
</table>

**Comment by izaera** [comment]
This is merged :rocket:

**Comment by bryceosterhaus** [comment]
It might be helpful to include a large table of versions and packages in a README in the target-platforms directory

**Comment by izaera** [comment]
Yep. I will add that in the documentation task, along with the "user manual". :+1:
