### ISSUE TITLE
Investigate creating a simple docs site for our tooling

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#758]
I imagine a simple static site would be sufficient that we can easily search. 

We can start with documenting the `@liferay/cli` tool.

High focus should be easily searchable

Inspiration:
[Create React App](https://create-react-app.dev/docs/getting-started)

**Comment by kresimir-coko** [comment]
I'd be up for spearheading the work on this one.

It could be a static site using [Next.js](https://nextjs.org/) for the architecture and [Clay](https://clayui.com/) for the UI components. I've got experience with Next (Lugbot, and I've been making a website for my own thing in my spare time using it) and Clay is the best component library. 

It can follow the same layout as the linked Create React App or clayui.com as it's a tried and true design that works for this type of site.

**Comment by bryceosterhaus** [comment]
@kresimir-coko good to know!

We probably aren't ready to build something out quite yet and would want to make sure we can keep it updated and in sync before commiting to it. I would hate to create another one-off docs project, only not to update it.

I think `Next.js` might be a bit overkill here, as we would want just something really minimal and static. We might try looking into https://docusaurus.io/docs/installation. Or perhaps we go super simple and start with a basic HTML site with some minimal docs for the cli tool.

Would you be up for adding some thoughts on a simple approach for this, as well as adding to our confluence Ideation page?

**Comment by kresimir-coko** [comment]
Docusaurus seems perfect for a project like this, it's cute as hell and it has dark mode 👍

**Comment by bryceosterhaus** [comment]
Closing. Will re-open later if we ever decide to do this.
