### ISSUE TITLE
Deprecate liferay-frontend-common-css in favor of liferay-frontend-css-common

### ISSUE THREAD

**Issue by jwanner83** [liferay/liferay-frontend-projects#773]
### Issue type (mark with `x`)

-   [x] :thinking: Question
-   [ ] :bug: Bug report
-   [ ] :gift: Feature request
-   [x] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :eight: v8.x
-   [ ] :nine: v9.x
-   [x] :keycap_ten: v10.x or higher

### Description
I was trying to upgrade a theme of ours to Liferay 7.4. While upgrading, I changed the `liferay-theme-tasks` version to 11+ and tried to build it, but it didn't work. After trial and error I managed to find out, that the [`liferay-frontend-common-css`](https://www.npmjs.com/package/liferay-frontend-common-css) has not been updated for more than 6 years and has been replaced with the [`liferay-frontend-css-common`](https://www.npmjs.com/package/liferay-frontend-css-common) package. Unfortunately, the old `liferay-frontend-common-css` doesn't display a deprecation message on install and also doesn't link to the new package inside the readme. And because the names are that similar, it was really hard to find this error. It would be great, if it was more clear that the package name has changed and it is required for the `liferay-theme-tasks` package in version 11+ to use the new [`liferay-frontend-css-common`](https://www.npmjs.com/package/liferay-frontend-css-common).

**Comment by bryceosterhaus** [comment]
Hey @jwanner83! Thanks for bring this to our attention, the naming of the packages is definitely confusing and seems like a good idea to use the newer package in our theme-tasks. Let me chat with the team and see how we want to address this.

**Comment by bryceosterhaus** [comment]
Also, when you say "tried to build it, but it didn't work", what exactly broke when you tried to build it? Was there specific errors regarding these packages? And are you actually using either of those css-common packages in your theme?

**Comment by jwanner83** [comment]
Hey @bryceosterhaus I tried and actually didn't manage to reproduce the error that I got. 🙃 I guess it happened because of a weird constellation of package versions between the `liferay-theme-tasks` and the `liferay-frontend-common-css` package, but I really don't know...

**Comment by bryceosterhaus** [comment]
No worries! It is at least helpful to have pointed out the package naming discrepancies. I am going to close this issue, but if anything else comes up, don't hesitate to reach out and bother us. Happy to help in any way we can.
