### ISSUE TITLE
Add an option to `liferay new` to create TypeScript projects

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#776]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :two: v2.x
-   [X] :three: v3.x

### Description
Add an option to `liferay new` to create TypeScript projects.

**Current behavior:**
We only generate JavaScript + Babel now.

**Comment by bnheise** [comment]
How about adding a configuration question to each of the project types.
The CLI asks "Would you like to add TypeScript"? and the user enders y/n.

**Comment by izaera** [comment]
Not sure if all frameworks let you choose :thinking: .

Angular is TypeScript.
React lets you choose, IIRC.
Vue.js no idea.

Then, we have the `Plain JavaScript` project, but I feel it doesn't make much sense to name it plain javascript and then ask if you want typescript :sweat_smile: . That's why a said a new type of project...

Another option could be renaming `Plain JavaScript` to something like `No framework` (or similar) then ask for:

1. nothing
2. babel
3. typescript

**Comment by bryceosterhaus** [comment]
> Another option could be renaming Plain JavaScript to something like No framework (or similar) then ask for:

+1 for this

**Comment by izaera** [comment]
Apparently, we want `@liferay/cli` to be more opinionated than its predecessor `generator-liferay-js`, so we won't add TypeScript support unless we find it necessary. I will close this for now, then.
