### ISSUE TITLE
Investigate moving theme-tasks away from using gulp as a primary build tool

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#783]
Currently we primarily rely on gulp for handling our theme tasks. Ideally we would be able to move away from gulp as the primary build tool and possible migrate into our liferay-cli tool or something similar. Not much is known about how challenging this would be at the moment, but we need to investigate.

**Comment by izaera** [comment]
>  migrate into our liferay-cli tool

That is a good idea, since we have now a lot of duplicate code for doing similar things. In the end 90% of the things our tooling does are creating/copying files and transforming them, whether it is to create a theme, a JS library, or generate a project...

**Comment by izaera** [comment]
Themes are a thing of the past (they won't be evolved and with the cloud based approach you can't even use them any more) so closing this.
