### ISSUE TITLE
Support Yarn

### ISSUE THREAD

**Issue by dnebing** [liferay/liferay-frontend-projects#796]
If a Liferay Gradle Workspace is configured to use Yarn via the `liferay.workspace.node.package.manager=yarn` property, the Liferay CLI should not be showing NPM commands to run.

**Comment by izaera** [comment]
We will do #798 for now: liferay-cli is not integrated into Liferay Gradle Workspace yet (AFAIK) and it doesn't even know where it is being run, so I think this should be "fixed" first in Liferay Gradle Workspace, then we modify the liferay-cli accordingly.
