### ISSUE TITLE
Add DXP target platforms

### ISSUE THREAD

**Issue by dnebing** [liferay/liferay-frontend-projects#797]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [ ] :bug: Bug report
-   [X] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :two: v2.x
-   [X] :three: v3.x

### Description

Where are the DXP target versions?

**Desired behavior:**

Selecting a target platform should support DXP.

**Current behavior:**

Only CE versions are listed

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**

**Comment by izaera** [comment]
For the record: it seems that we can get the info we need to create the target platform from the same repo as CE versions (given that the source tree is the same). However we will need to know which commit corresponds to which DXP version, so I'm going to find out how to get that info.

Stay tuned.

**Comment by izaera** [comment]
So, apparently git tags for DXP releases can be found in the [liferay-portal-ee](https://github.com/liferay/liferay-portal-ee) repo.

The look like this:

- For 7.4: https://github.com/liferay/liferay-portal-ee/tree/fix-pack-base-7413
- For <7.4: https://github.com/liferay/liferay-portal-ee/tree/fix-pack-dxp-1-7310 (where `dxp-1` stands for fixpack 1, and `7310` for `7.3...`)

**Comment by izaera** [comment]
I've merged the PR but I cannot release to npmjs because of some permissions issues. Will need to delay it for next week, most probably.

**Comment by izaera** [comment]
Released:

- https://www.npmjs.com/package/@liferay/dxp-7.4/
- https://www.npmjs.com/package/@liferay/dxp-7.3/
- https://www.npmjs.com/package/@liferay/dxp-7.2/
- https://www.npmjs.com/package/@liferay/dxp-7.1/

So, this is finished :tada:
