### ISSUE TITLE
Enforce usage of standard hooks

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#8]
For example, we want people to use the `usePrevious` hook from `frontend-js-react-web` instead of rolling their own. I am testing a PR that removes some instances in https://github.com/wincent/liferay-portal/pull/123, but we should enforce this at the lint level, kind of like we do with the "liferay-portal/no-metal-plugins", "liferay-portal/no-react-dom-render" and "liferay-portal/no-side-navigation" rules, which all steer the developer away from UIs that we want to deprecate.

A dumb version of the check would just detect something like:

```js
// error
import {usePrevious} from 'anything-except-frontend-js-react-web';

// error
function usePrevious(...) { /* ... */ }

// error
const usePrevious = // ...
```

**Comment by bryceosterhaus** [comment]
Gonna close as we don't have the capacity for it. Will re-open in future if necessary
