### ISSUE TITLE
babel-preset-liferay-standard throws Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by AlonKapi** [liferay/liferay-frontend-projects#803]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md **<- this link is broken**) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [ ] :three: v3.x

### Description

Creating a new react widget using the following steps:
- npm install -g generator-liferay-js
- yo liferay-js - Choose react project without sample code, without language and configuration, with local liferay bundled with tomcat.
- npm run deploy and the widget is deployed and working.
- Update react and react-dom to version ^17.0.2.
- npm run deploy again
- build fails with error message:

```
C:\Users\USER\x\x\x>npm run deploy

> x@1.0.0 deploy C:\Users\USER\x\x\x
> npm run build && lnbs-deploy


> x@1.0.0 build C:\Users\USER\x\x\x
> babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler

Successfully compiled 2 files with Babel (4081ms).

> x@1.0.0 copy-assets C:\Users\USER\x\x\x
> lnbs-copy-assets

Project assets copied.


Error: EMFILE: too many open files, open 'C:\Users\USER\x\x\x\node_modules\babel-preset-liferay-standard\package.json'
    at Object.openSync (fs.js:498:3)
    at readFileSync (fs.js:394:35)
    at loadpkg (C:\Users\USER\x\x\x\node_modules\resolve\lib\sync.js:129:20)
    at loadAsFileSync (C:\Users\USER\x\x\x\node_modules\resolve\lib\sync.js:94:19)
    at loadAsDirectorySync (C:\Users\USER\x\x\x\node_modules\resolve\lib\sync.js:174:16)
    at loadNodeModulesSync (C:\Users\USER\x\x\x\node_modules\resolve\lib\sync.js:186:25)
    at Function.resolveSync [as sync] (C:\Users\USER\x\x\x\node_modules\resolve\lib\sync.js:85:17)
    at Project.resolve (C:\Users\USER\x\x\x\node_modules\liferay-npm-build-tools-common\lib\project\index.js:228:34)
    at Project.toolResolve (C:\Users\USER\x\x\x\node_modules\liferay-npm-build-tools-common\lib\project\index.js:282:25)
    at Project.toolRequire (C:\Users\USER\x\x\x\node_modules\liferay-npm-build-tools-common\lib\project\index.js:261:29)
```

I also tried to update the other dependencies in the project so my package.json looks like:
```
{
	"name": "x",
	"version": "1.0.0",
	"description": "x",
	"devDependencies": {
		"liferay-npm-bundler": "^2.28.2",
		"liferay-npm-build-support": "^2.28.2",
		"copy-webpack-plugin": "10.2.0",
		"webpack": "5.65.0",
		"webpack-cli": "4.9.1",
		"webpack-dev-server": "4.7.2",
		"@babel/cli": "^7.16.7",
		"@babel/core": "^7.16.7",
		"@babel/preset-env": "^7.16.7",
		"@babel/preset-react": "^7.16.7"
	},
	"dependencies": {
		"react": "^17.0.2",
		"react-dom": "^17.0.2",
		"react-scripts": "4.0.3"
	},
	"scripts": {
		"build": "babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler",
		"copy-assets": "lnbs-copy-assets",
		"deploy": "npm run build && lnbs-deploy",
		"start": "lnbs-start"
	},
	"portlet": {
		"com.liferay.portlet.display-category": "category.sample",
		"com.liferay.portlet.header-portlet-css": "/css/styles.css",
		"com.liferay.portlet.instanceable": true,
		"javax.portlet.name": "x",
		"javax.portlet.security-role-ref": "power-user,user",
		"javax.portlet.display-name": "x"
	},
	"main": "index.js"
}
```

**Desired behavior:**
Jar is created and widget deployed to local liferay server.

**Current behavior:**
Build fails and no jar is created.

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**
**Windows 10 pro version 21H2**
**Node version ^14.17.3**
**Npm version 6.14.13**
**liferay-ce-portal-7.3.1-ga2**

**Comment by izaera** [comment]
I would try to play with this setting -> https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/docs/reference/dot-npmbundlerrc.md#max-parallel-files

This is a typical problem in Windows when too many async processes cause too many files to be opened. The only way to mitigate it is to open less files, AFAIK.

**Comment by izaera** [comment]
I'll close this issue since, theoretically, the proposed solution would do.

Feel free to reopen or continue posting if needed :+1: .
