### ISSUE TITLE
Cannot adapt a React App with react-scripts@5.0.0

### ISSUE THREAD

**Issue by crcarlo** [liferay/liferay-frontend-projects#809]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] :two: v2.x
-   [ ] :three: v3.x

### Description

Cannot adapt a new React app.

A React app generated with `react-scripts@5.0.0` cannot load once deployed.

I verified that `react-sctipts@5.0.0`'s build process generates the following js files:

- `main.<hash>.js`
- `787.<hash>.chunk.js`

while the generated `index.js` file inside `build.liferay` folder requires the following:

- `"runtime-main"`
-  `"2.chunk"`
- `"main.chunk"`

The problem can be solved by changing `react-scipts` to 4.x version in `package.json`'s dependencies.

You can verify this behavior by simply generating a new app with `npx create-react-app` and making sure you have `react-scripts@5.0.0` as a dependency.

I verified this problem with:
- `generator-liferay-js@2.28.2`
- Node `v14.15.0`

**Comment by izaera** [comment]
Thanks for the report. We need to update the adaptation scripts to this new version :+1:

**Comment by pandeytanmay** [comment]
It seems fix to this issue has broken vue-cli adaptation. Here is what I'm getting when trying to run npm run build:liferay on an adapted vue-cli project

`internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '<projectBaseDir(redacted)>\build\static\js'
    at Object.readdirSync (fs.js:955:3)
    at buildWith (<projectBaseDir(redacted)>\node_modules\liferay-npm-build-support\lib\scripts\build\index.js:63:14)
    at Object.default_1 [as default] (<projectBaseDir(redacted)>\node_modules\liferay-npm-build-support\lib\scripts\build\index.js:42:13)
    at Object.<anonymous> (<projectBaseDir(redacted)>\node_modules\liferay-npm-build-support\bin\lnbs-build.js:8:40)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '<projectBaseDir(redacted)>\\build\\static\\js'
}`
@izaera I hope you'd be able to help. This has become a blocker for my team.

**Comment by izaera** [comment]
> This has become a blocker for my team.

@pandeytanmay I would say, first upgrade your project to the latest vue versions. We normally test each release with the latest version available at that moment. If that doesn't work, downgrade the js-toolkit version (to workaround the error) and open an issue in this project specifying the versions you are using and the above error, so that we can fix it.

The problem with adaptations is that we cannot support every version of vue-cli, react-scripts, or angular, out there, so we restrict ourselves to the latest one (formally). It may happen though, from time to time, that some of the three supported frameworks release a new version and we don't catch up, but in the end we always want to guarantee to work only with the latest version of each framework.

**Comment by pandeytanmay** [comment]
> first upgrade your project to the latest vue versions. We normally test each release with the latest version available at that moment. If that doesn't work, downgrade the js-toolkit version (to workaround the error) and open an issue in this project specifying the versions you are using and the above error, so that we can fix it.

@izaera Thank you for responding promptly. We are using vue@2.6.14, which is the latest version of Vue (not vue3). I have downgraded the js-toolkit version and it builds. I hope there wouldn't be any issue with functionality. As suggested, I'm going to open an issue on this project. Thank you.
