### ISSUE TITLE
Theme's gulp build fails with liferay-font-awesome 3.5.0

### ISSUE THREAD

**Issue by mikke-alekstra** [liferay/liferay-frontend-projects#818]
For some reason gulp build fails when using liferay-font-awesome 3.5.0.

Steps to reproduce:

npm install -g generator-liferay-theme
npm install -g yo gulp
yo liferay-theme
```
...
! This version of the Themes SDK (10.2.0) supports Liferay DXP 
and Portal CE from 7.2 to 7.4.
...
? Which version of Liferay is this theme for? 7.4
? Would you like to add Font Awesome to your theme? Yes
...
```
gulp build
```
...
[14:50:51] Starting 'build:copy:fontAwesome'...
[14:50:51] 'build:copy:fontAwesome' errored after 1.11 ms
[14:50:51] Error: Cannot find module 'liferay-font-awesome'
Require stack:
- /home/mikke/my-liferay-theme/node_modules/liferay-theme-tasks/lib/util.js
- /home/mikke/my-liferay-theme/node_modules/liferay-theme-tasks/theme/index.js
- /home/mikke/my-liferay-theme/gulpfile.js
...
```
The build completes successfully if I change the liferay-font-awesome version to 3.4.2 in package.json. With 3.5.0 it fails.

node.js v16.13.2
npm 8.1.2
gulp CLI 2.3.0 Local 4.0.2
yo 4.3.0

**Comment by bryceosterhaus** [comment]
@mikke-alekstra thanks for reporting this! We will try to take a look at this soon and see what is going on.

**Comment by kresimir-coko** [comment]
Verified that it behaves the same for me, gonna investigate!

**Comment by kresimir-coko** [comment]
@Alec-Shay yes, #855 it does fix it, I tested it. We should get it merged soon.
