### ISSUE TITLE
Verify and document rules and external libraries we consume in eslint README

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#832]
We need to verify and update our README in our [eslint plugin](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/eslint-plugin/README.md). I don't think we currently have all rules listed, for example [no-anonymous-exports](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/eslint-plugin/rules/general/lib/rules/no-anonymous-exports.js) is not listed in our README.

**Comment by brunofernandezg** [comment]
Comment to force sync. Ignore
