### ISSUE TITLE
npm ERR! notarget No matching version found for @liferay/js-toolkit-core@^5.0.1.

### ISSUE THREAD

**Issue by 0xAnakin** [liferay/liferay-frontend-projects#848]
-   [ ] :thinking: Question
-   [X] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

I was trying to adapt a newly created angular(v13) app.
After entering `yo liferay-js:adapt` the process started and while the npm install was running I got the following dependency error: 

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @liferay/js-toolkit-core@^5.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**node version**: `16.14.0`

**packages installed globally**:

├── @angular/cli@13.2.3        
├── corepack@0.10.0
├── generator-liferay-js@2.28.3
├── npm@8.3.1
└── yo@4.3.0

**Comment by 0xAnakin** [comment]
It seems you haven't published version 5.0.1 on npm

**Comment by izaera** [comment]
@0xAnakin I've fixed it. You are too fast :sweat_smile:

**Comment by izaera** [comment]
Let me know if some other issue arises. Thanks :-)

**Comment by 0xAnakin** [comment]
@izaera did you upload `js-toolkit-core@5.0.1` on npm registry cause I don't see a new version? 😅 
Maybe I should uninstall and re-intall `generator-liferay-js`?

**Comment by izaera** [comment]
Nope, @liferay/js-toolkit-core has version 5.0.0, but the wrong dependency reference was in portal-base.

What package is requesting @liferay/js-toolkit-core 5.0.1 in your case? :thinking:

**Comment by izaera** [comment]
This is the commit -> https://github.com/liferay/liferay-frontend-projects/commit/380e149b2b312aa2d3d6f0e64c53805b05b95e22

**Comment by izaera** [comment]
I wonder why you are experiencing this error, in any case, because these packages I'm talking about are not related to the generator (the generator is from the JS Toolkit v2, and the new packages are for the next version of JS Toolkit) :thinking:

**Comment by 0xAnakin** [comment]
Also I've uninstalled `generator-liferay-js` globally and re-installed it just in case...

**Comment by izaera** [comment]
OK, so the problem must be in one of those deps. Let me check.

**Comment by izaera** [comment]
I've copied your package.json and run `yarn install` on it and it works.

Have you tried to delete the node_modules folder of your project and the package-lock.json file? Some of those must be holding a bogus reference...

**Comment by izaera** [comment]
If I `cd` to `angular-app` and run `npm install` again, it does work :shrug: (so it's not a matter of yarn vs npm, but simply running the install again; quite strange...)

Then, I've been able to find out what uses `js-toolkit-core`:

```sh
$ npm ls @liferay/js-toolkit-core
angular-app@0.0.0 /home/ivan/Temporal/issue-850/angular-app
└─┬ liferay-npm-bundler-preset-angular-cli@2.28.3
  └─┬ @liferay/portal-adapt-base@1.0.1
    └─┬ @liferay/portal-base@1.1.1
      └── @liferay/js-toolkit-core@5.0.0
```

**Comment by izaera** [comment]
We have the "old" code from JS Toolkit v2 pointing to the "new" code in `liferay-cli`, because we don't want to maintain two versions in parallel. For some reason, because I published a wrong version of `portal-base` (1.1.0) pointing to an invalid `js-toolkit-core` (5.0.1) it looks like your setup is trying to use that one instead of (1.1.1).

I'm going to unpublish the incorrect `portal-base` version to avoid problems like this in the future, but I suspect you will be getting the same problem over and over because there's something in your system caching the wrong version.

Have you tried cleaning the npm cache? Or maybe look for files like `*js-toolkit-core*` in your whole system...

Another test you can do is what I did. Let it fail, then cd to angular-app and run npm install again, then the npm ls to see the dependency path.

The difference between npm and yarn may also be due to npm caching different things than yarn (as each tool uses its own cache).

**Comment by izaera** [comment]
Also, regarding the error I got (with `webpack-cli@^4.9.1`) there must be something wrong in npm, because that version exists :point_right: https://www.npmjs.com/package/webpack-cli/v/4.9.1 :thinking:

**Comment by izaera** [comment]
I'll wait for the tests suggested here :point_right: https://github.com/liferay/liferay-frontend-projects/issues/848#issuecomment-1035950452 to take place before closing this issue.

**Comment by izaera** [comment]
@0xAnakin If you will be doing this :point_right: https://github.com/liferay/liferay-frontend-projects/issues/850#issuecomment-1035960221 and it works, just forget about my suggestions and close this issue :+1:

**Comment by 0xAnakin** [comment]
Yeap the new tool seems to work better, has some minor issues still tho, see #850 for more. I'm closing this one
