### ISSUE TITLE
Angular app adaptation fails 

### ISSUE THREAD

**Issue by 0xAnakin** [liferay/liferay-frontend-projects#850]
Tried to adapt an angular app and it failed firstly when using npm as a dependency manager see #848 and after that when trying to locate the path `build/static/js` which does not exist in an out of the box angular app. Use the exact node version mentioned below and npm as a package manager. See reproduction steps listed at the end.

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

**node version**
- v16.14.0

**packages installed globally**

├── @angular/cli@13.2.3
├── corepack@0.10.0
├── generator-liferay-js@2.28.3
├── npm@8.3.1
└── yo@4.3.0

**Steps**

- install nodejs LTS (16.14.0)
- type & hit enter: `npm install -g yo generator-liferay-js @angular/cli`
- type & hit enter: `ng new angular-app`
- type & hit enter: `cd angular-app`
- type & hit enter: `yo liferay-js:adapt`

**Comment by izaera** [comment]
Hey @0xAnakin , can you try to use the new `liferay-cli` tool to adapt your project? Sooner than later we will deprecate the yeoman generator and the `liferay-cli` tech stack is leaner and simpler so it should be less error prone.

I tested it yesterday for this version of `@angular/cli` :point_right: https://github.com/liferay/liferay-frontend-projects/blob/f59673a585bf1143cdf07130fe5628629d32344e/projects/js-toolkit/scripts/qa/util.js#L30 and it worked perfectly, so that should work for you too.

You can check `liferay-cli` documentation here :point_right: https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/docs/manuals/liferay-cli.md

If for some reason you need to keep using the old stack (yeoman generator) I think you are experiencing the same problem(s) listed here -> https://github.com/liferay/liferay-frontend-projects/issues/613

**Comment by 0xAnakin** [comment]
Hey @izaera I had no idea you had a new tool out 😮 but I get the following error about a `.liferay.json` file missing?

![image](https://user-images.githubusercontent.com/5445023/153598309-8b1299dd-8508-4d68-9537-6f04d6269f5b.png)

**Comment by 0xAnakin** [comment]
I created a `.liferay.json` myself and added the following:
```json
{
	"liferayDir": "C:/Development/liferay/liferay-dxp-7.3.10.1-sp1-ethniki"
}
```

Then I tried `npm run deploy:liferay` but I got an error that it requires building first, so I did `npm run build:liferay` and then `npm run deploy:liferay` and it worked

**Comment by izaera** [comment]
> · the file should be automatically created

Yep. That one was working, so it probably broke with the last update :-(.

> · deploy:liferay should also build and not just move the jar file

Not so sure about that. I know it did that in previous versions of the JS Toolkit, and I know it's handy, but on the other side, building usually tooks very long and it isn't always needed before deployment... :thinking:

We may unify those targets again in the future, when we optimize the build times, but for now, I feel it is better to separate them...

In any case, I'd like to hear more opinions on this, so I'm mentioning some more people to see what they think: @bryceosterhaus  @pablo-agulla @dsanz @kresimir-coko

**Comment by 0xAnakin** [comment]
bump

**Comment by dsanz** [comment]
> I know it did that in previous versions of the JS Toolkit, and I know it's handy, but on the other side, building usually tooks very long and it isn't always needed before deployment

This is handy yeah, but at the same time, forces a build for each deployment, so if you want to deploy to more than one target, that will slow down things. Couldn't this be somehow configurable with a sensible default? For simple use cases it may make sense to tie both tasks. Maybe having a separate entry under `scripts`?

**Comment by izaera** [comment]
I like the idea of having two entries on the package.json :+1: 

How about:

- `deploy` : to build & deploy
- `deploy:only`: to only deploy

Or is it better to have the opposite? :thinking: :

- `build-deploy` : to build & deploy
- `deploy`: to only deploy

**Comment by pablo-agulla** [comment]
For me it's more clear the second option, however if in the portal, deploy always builds & deploys, I'll go for option 1

**Comment by izaera** [comment]
Hey, I'm not going to release a new version specifically for this, but if you need it @0xAnakin just ask for it.
