### ISSUE TITLE
Create a status page to easily check if the GH-Jira sync is down

### ISSUE THREAD

**Issue by brunofernandezg** [liferay/liferay-frontend-projects#867]
Can you think of an easy way to know if the app is down? Because right now we can only know it if the sync doesn't work or connecting to the server and checking the logs or the running processes. Not saying that we need to get a notification, but maybe a very simple status web that says "I'm up"?

Asked Victor about this possibility and he says it makes sense. Right now the server is accesible without the VPN
https://github-jira-synchronization.liferay.org.es/
Maybe it would be possible to create
https://github-jira-synchronization.liferay.org.es/system_status
And this could be a very simple page that says "up and running" or "error, not found"

**Comment by brunofernandezg** [comment]
How does it work?

**Comment by brunofernandezg** [comment]
Deployed the new version and it's working here
https://github-jira-synchronization.liferay.org.es/status

**Comment by bryceosterhaus** [comment]
> Is it deployed? How does it work?

@brunofernandezg did you get some proper steps for this?

**Comment by brunofernandezg** [comment]
@bryceosterhaus It's documented here (Victor did it)
https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1954447876/Github+to+Jira+synchronization+tool#How-to-deploy-a-new-version
(and linked in the project's readme)

added an additional step if you find conflicts on the config file
