### ISSUE TITLE
SCSS lint error: unknown property "aspect-ratio"

### ISSUE THREAD

**Issue by p2kmgcl** [liferay/liferay-frontend-projects#878]
It looks like the list of valid CSS properties is outdated, I am getting this error when trying to use the "aspect-ratio" property in a .scss file:

![image](https://user-images.githubusercontent.com/800645/157413990-90a91d56-0c7d-45d7-b953-73d9cd7f4cc2.png)

**Comment by izaera** [comment]
We will release a new version of npm-scripts with this fix, by the end of the week, most probably.
