### ISSUE TITLE
Wrong date in case the year format is four digit but the value is two digit

### ISSUE THREAD

**Issue by rolandpakai** [liferay/liferay-frontend-projects#879]
The issue is related to the **aui-datepicker**.

Reproduction steps:

0. Set a four digit year mask like %m/%d/%Y
1. Type today's date in the date field like 03/10/22 

**Actual result:**
The date becomes 03/10/1922

**Expected result:**
It should be 03/10/2022

https://issues.liferay.com/browse/LPS-149012

**Comment by izaera** [comment]
This is apparently fixed, so closing.
