### ISSUE TITLE
React and Liferay documentation?

### ISSUE THREAD

**Issue by daxz1** [liferay/liferay-frontend-projects#884]
Hi,

Is there documentation anywhere regarding setting up React with Liferay?

We have a working adhoc solution but recently came across this repo, but I couldn't find anything guides/documentation.

Any help would be appreciated.

**Comment by izaera** [comment]
Hi there :wave: 

There's [the technical documentation](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/docs/README.md) and I believe there has to be something more in [the official DXP documentation](https://learn.liferay.com/)

**Comment by daxz1** [comment]
Thank you very much
