### ISSUE TITLE
Investigate eslint rule for to disallow reaching deeply into clay packages "import '@clayui/button/lib/SomeComponent'

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/liferay-frontend-projects#887]
See https://github.com/liferay-frontend/liferay-portal/pull/2013/files#diff-e5684e484cfedf9ec256f1001bd1cb3e8bc5d3e5b33ca8920f133c0fc92894c2L17 for reference

**Comment by izaera** [comment]
We won't really need this once [the webpack build](https://github.com/brianchandotcom/liferay-portal/pull/116007) is fully in place (because it will simply fail if people tries to do it :sweat_smile: ). So I wouldn't bother with doing anything in eslint...
