### ISSUE TITLE
Liferay's Global Event Bus Example Proposal

### ISSUE THREAD

**Issue by sergiojimcos** [liferay/liferay-frontend-projects#888]
## What is your proposal?

This issue is related to the [Liferay's Global Event Bus](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/dxp/liferay_global_event_bus.md#liferay.on) section with the aim of adding a series of examples that may be useful for the use of this library and that will allow any user to understand this library in a much clearer way.

The only propose is to add some examples that can be profitable for the users (for those who doesn't know the concepts of Custom Events) who wants to use this section.

**Comment by bryceosterhaus** [comment]
Hey @sergiojimcos! Did you have specific examples in mind? I was looking at the document and did see code examples for events, so I wasn't sure if maybe I am missing or misunderstanding something here.

**Comment by sergiojimcos** [comment]
Hi @bryceosterhaus! Sorry for not being clear. As you said, there are some code examples but individually, I mean each section has got an individual code example. What I want to propose is to make a code example which includes some individual sections, i.e: the communication between `Liferay.on` and `Liferay.fire` using both, how you can publish a Custom Event with `Liferay.fire` and how `Liferay.on` subscribes the Custom Event.

**Comment by bryceosterhaus** [comment]
Ah I see, so you were hoping to see a full working example?

Something like

```jsx
// Module A
Liferay.on('my-custom-event', (data) => {
    alert(data);
});

// JSX in Module B 
<button onClick={() => Liferay.fire('my-custom-event', 'Hello!')}>
	Say Hello!
</button>
```

And then a gif showing the alert pop up for module A?

**Comment by sergiojimcos** [comment]
Yeah! that's it. It will a nice example to understand how to use Custom Events in different modules.
