### ISSUE TITLE
Allow npm-scripts to format .md and .yml files

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-projects#92]
### Issue type

-   :gift: Feature request

### Description

**Desired behavior:**

As per https://github.com/liferay/liferay-frontend-projects/issues/91 — they want to format YAML and Markdown too using `@liferay/npm-scripts`.

**Current behavior:**

We only support [a hard-coded list of file extensions](https://github.com/liferay/liferay-frontend-projects/blob/fda8587ef8268bcf423e4adb0ae00392e754716d/projects/npm-tools/packages/npm-scripts/src/scripts/format.js#L23) for the reasons discussed in the linked issue.

**Comment by jbalsas** [comment]
Just quick comment, in `liferay-portal` we have
- Lots of `.md` files
- Few `.yml` files
- Several `.yaml` files

I'm assuming we don't want to format those in the `liferay-portal` repo but allow them to be formatted through `@liferay/npm-scripts` in other projects?

**Comment by wincent** [comment]
Correct. My idea is to *allow* them to be formatted, but not to change the default globs in liferay-portal itself (because they are already handled there by the Java Source Formatter; we could look at handing over responsibility for those filetypes to Prettier in the future, but that would be a separate thing).
