### ISSUE TITLE
Liferay CLI can not correctly process some fields in btach config file.

### ISSUE THREAD

**Issue by simonjhy** [liferay/liferay-frontend-projects#930]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [X ] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [X ] :two: v2.x
-   [ X] :three: v3.x

### Description 

**Desired behavior:** #Liferay CLI can correctly handle some filelds in batch model configuration file.
**Current behavior:** 
#Liferay CLI  did not correctly handle addConfigurationSupport, addLocalizationSupport, createInitializer, useShadowDOM, outputPath. 

**Repro instructions (if applicable):**

{
    "addConfigurationSupport": "false",
    "addLocalizationSupport": "false",
    "projectType": "Shared bundle",
    "description": "aa34",
    "category": "category.sample",
    "platform": "dxp-7.4",
    "target": "Liferay Platform Project"
}

**Other information (environment, versions etc):**

Linux Unbuntu 2204

**Comment by bryceosterhaus** [comment]
Hey @simonjhy I just tested this out locally, and I think you are running into issues because you are passing a string(`"false"`) instead of a boolean(`false`). When javascript picks these values up, it is essentially checking 
```
if ("false") {}
```
instead of
```
if(false) {}
```

**Comment by bryceosterhaus** [comment]
Going to close, feel free to reopen if you have other issues
