### ISSUE TITLE
Including font awesome using js themes toolkit fails to build the theme

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-frontend-projects#934]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :eight: v8.x
-   [ ] :nine: v9.x
-   [x] :keycap_ten: v10.x or higher

### Description
Including font awesome using js themes toolkit fails to deploy the theme

**Desired behavior:**
gulp deploy, deploys liferay theme successfully

**Current behavior:**
gulp build/deploy errored out when copying fontAwesome
https://gist.github.com/john-co/3fcfc35fc219ba6a1e4f02182db5b3a6

**Repro instructions (if applicable):**
run yo liferay-theme > select 7.4 > yes for FontAwesome
run gulp deploy

**Other information (environment, versions etc):**
Note: there were also multiple deprecation warnings during gulp build ie:

```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(($r * 299) + ($g * 587) + ($b * 114), 1000) or calc((($r * 299) + ($g * 587) + ($b * 114)) / 1000)
More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
470 │     $yiq: (($r * 299) + ($g * 587) + ($b * 114)) / 1000;
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    build/_css/clay/functions/_global-functions.scss 470:8  color-yiq()
    build/_css/clay/variables/_buttons.scss 327:10          @import
    build/_css/clay/_variables.scss 11:9                    @import
    build/_css/clay/base-variables.scss 7:9                 @import
    build/_css/_imports.scss 3:9                            @import
    build/_css/main.scss 1:9                                root stylesheet

```

**Comment by izaera** [comment]
Regarding the warnings, they are due to the contents of the base theme, which is managed outside of the Themes Toolkit (it is inside liferay-portal) so better create an LPS for that, maybe...
