### ISSUE TITLE
AlloyUI Aui-Tree rendered bottom to top

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-frontend-projects#936]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] 3.1.0-deprecated.92
This is an Alloy-ui issue. 

### Description
The aui-tree is being rendered bottom to top.
https://issues.liferay.com/browse/LPS-153679

**Desired behavior:**
The tree should be rendered top to bottom
![expected_order](https://user-images.githubusercontent.com/31672551/169151952-7d39d0ce-4ce2-45c4-a0c4-8b1092a4d867.png)

**Current behavior:**
The aui-tree is being rendered bottom to top.
![actual_order](https://user-images.githubusercontent.com/31672551/169151974-86b1fd58-cbc2-412b-a19d-fe86309cf546.png)

**Comment by bryceosterhaus** [comment]
@fortunatomaldonado do you have an example of creating the tree? And if possible, a codesandbox example?

**Comment by fortunatomaldonado** [comment]
Hello @bryceosterhaus, unfortunately I'm having trouble building alloy-ui using gulp. I have been using Liferay to reproduce this behavior.

From my testing, I believe it was [3.1.0-deprecated.82](https://github.com/liferay/alloy-ui/releases/tag/3.1.0-deprecated.82) that caused this issue. I have been updating the alloy-ui version in Liferay 7.3 and found 3.1.0-deprecated.81 working as expected.
I am having trouble testing in Master since I am not sure how to use the un-minified alloy-ui files.

Any advice on how to test alloy-ui is much appreciated so I can debug this issue and future issues.
Thank you.

**Comment by bryceosterhaus** [comment]
Hmm, from 81 -> 82, it looks like [this was the only change which could be related](https://github.com/liferay/alloy-ui/commit/8a2b8f1b07f8304431ed9748cdd9976b851ccfda). @georgel-pop-lr maybe you would know more about this?

**Comment by fortunatomaldonado** [comment]
Hello @georgel-pop-lr,

This issue is reproduced in the latest version [3.1.0-deprecated.92](https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/webjars/com.liferay.webjars.alloy-ui/3.1.0-deprecated.92/)
I was able to find that [this change causes the issue. ](https://github.com/liferay/alloy-ui/commit/8a2b8f1b07f8304431ed9748cdd9976b851ccfda#diff-72d248517d0ec24d3f3b33e7be9475c2eb8598e1ee576dd0dae997f1f9c0114bR572) I am able to see the issue with the wiki page tree in Liferay.

Truly appreciate all the help with debugging!

**Comment by georgel-pop-lr** [comment]
> Hello @georgel-pop-lr,
> 
> This issue is reproduced in the latest version [3.1.0-deprecated.92](https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/webjars/com.liferay.webjars.alloy-ui/3.1.0-deprecated.92/) I was able to find that [this change causes the issue. ](https://github.com/liferay/alloy-ui/commit/8a2b8f1b07f8304431ed9748cdd9976b851ccfda#diff-72d248517d0ec24d3f3b33e7be9475c2eb8598e1ee576dd0dae997f1f9c0114bR572) I am able to see the issue with the wiki page tree in Liferay.
> 
> Truly appreciate all the help with debugging!

Hi  @fortunatomaldonado,

Testing with this case https://issues.liferay.com/browse/LPS-135540 seems to work just fine in master with latest version.

I could see your pull https://github.com/liferay/liferay-frontend-projects/pull/937 you should be sure that https://issues.liferay.com/browse/LPS-127457 is not being reproduced after your changes.

What do you mean by wiki page tree, could you provide some steps? 

Regards.

**Comment by bryceosterhaus** [comment]
@georgel-pop-lr we should probably still create the AUI tickets because I believe those mostly go through support, and then if we need to spawn a issue or discussion here, that works too.

**Comment by georgel-pop-lr** [comment]
> Hello @georgel-pop-lr,
> 
> I will double check that no issue is being reproduce with my fix and let you know.
> 
> I apologize for now being clear. Following the reproduction steps in https://issues.liferay.com/browse/LPS-153679, the wiki page tree orders from bottom to top. Let me know if clarification is needed for my pull and if a AUI ticket is needed.
> 
> Thank you.

Hi @fortunatomaldonado,

I have tried to reproduce this on master with steps provided in https://issues.liferay.com/browse/LPS-153679

But doesn't look like they are painted in reverse order:
![image](https://user-images.githubusercontent.com/59687465/169491926-a3c1469d-7767-4ff6-af04-479de9e17e4b.png)
![image](https://user-images.githubusercontent.com/59687465/169492246-eeac04d9-a60d-467f-801d-e98d96a03d2e.png)

Have you tried to reproduce this on master, or affects only 7.3?

Regards.

**Comment by fortunatomaldonado** [comment]
Hello @georgel-pop-lr,

From my investigation, when rendering elements with the example you sent, the tree is built without having to go through [`_createFromHTMLMarkUp`](https://github.com/liferay/liferay-frontend-projects/blob/master/third-party/projects/alloy-ui/src/aui-tree/js/aui-tree-view.js#L310).

The Wiki Tree is built using [`_createFromHTMLMarkUp`](https://github.com/liferay/liferay-frontend-projects/blob/master/third-party/projects/alloy-ui/src/aui-tree/js/aui-tree-view.js#L230) and I found that this is the issue. Since this tree will result in not having any ["ChildNodes"](https://github.com/liferay/liferay-frontend-projects/blob/master/third-party/projects/alloy-ui/src/aui-tree/js/aui-tree-node.js#L576), the tree is not properly built.

**Comment by georgel-pop-lr** [comment]
Hi @fortunatomaldonado,

Could you check if the solution for expand button could work here, see: https://github.com/liferay/alloy-ui/pull/176/files

Basically, the solution is to add the `nodeContainer` dynamically when we press expended, maybe you could do something similar inside _createFromHTMLMakrUp and like this have the child nodes needed on https://github.com/liferay/liferay-frontend-projects/blob/master/third-party/projects/alloy-ui/src/aui-tree/js/aui-tree-node.js#L576.

What I find strange is that in this Tree Menu widget, we still have one empty UL list at the end of the tree: 
![image](https://user-images.githubusercontent.com/59687465/169785437-bdd55825-667e-4b7f-ac95-b4599e71b338.png)

Not sure why this empty container exists there but if possible should be eliminated.

If you need extra help, let me know.

Regards.

**Comment by georgel-pop-lr** [comment]
Hi @fortunatomaldonado,

I had another look into it and seems that inside [_createFromHTMLMarkUp](https://github.com/liferay/liferay-frontend-projects/blob/50bdae2ab3fda014831cdafc239e485176be5343/third-party/projects/alloy-ui/src/aui-tree/js/aui-tree-view.js#L239) we don't set any children to this instance, so it can't identify the condition we have on [if (instance.hasChildNodes())](https://github.com/liferay/liferay-frontend-projects/blob/50bdae2ab3fda014831cdafc239e485176be5343/third-party/projects/alloy-ui/src/aui-tree/js/aui-tree-node.js#L576). 

What we can do for this case as is interpreting the HTML, we can get the child nodes directly from nodeContainer, changing the condition to `if (instance.hasChildNodes() || nodeContainer.get('children')._nodes.length)`

With this change, I think it will work for the case specified by you, you can test it.

The strange this is that we have an empty UL list inside FrontPage tree (the one that comes by default), seems that this [condition](https://github.com/liferay/liferay-frontend-projects/blob/50bdae2ab3fda014831cdafc239e485176be5343/third-party/projects/alloy-ui/src/aui-tree/js/aui-tree-node.js#L722) is true for this node for some strange reason (still investigating...).

Hope it helps.

Regards.

**Comment by fortunatomaldonado** [comment]
Hello @georgel-pop-lr,

That fixes the issue. Thank you for taking a look at this and for all your help!

**Comment by georgel-pop-lr** [comment]
Released and fixed under [d43911ee2de74](https://github.com/liferay/liferay-portal/commit/d43911ee2de74) LPS-154813 - Update alloy-ui to 3.1.0-deprecated.95
