### ISSUE TITLE
AUI ImageViewer does not attach keydown eventListener on the instance

### ISSUE THREAD

**Issue by NemethNorbert** [liferay/liferay-frontend-projects#958]
The issue is related to aui-image-viewer.

https://issues.liferay.com/browse/LPS-156230

Reproduction steps:

1. login in DXP 7.3 as admin and go to Content & Data → Web Content → Structures
2. create a structure with at least 2 ddm-image fields
3. create a web content that uses this structure
4. on the web content creation form, choose one image for each field
5. click on the "Preview" button of the 1st image: image is displayed using image-preview layer
6. hit the "escape" key: image preview is closed
7. click on the "Preview" button of the 2nd image: image is displayed using image-preview layer
**Actual behavior:**
hitting the "escape" key has no effect
**Expected behavior:**
hitting the "escape" key closes the image preview

The image-viewer is attaching the event listener on the doc, and its causing this issue with multiple instances

**Comment by bryceosterhaus** [comment]
fixed by https://github.com/liferay/liferay-frontend-projects/pull/959
