### ISSUE TITLE
Minify output (code and CSS) in @liferay/cli projects

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-projects#976]
See [this comment in a PR](https://github.com/liferay-frontend/liferay-portal/pull/2537#discussion_r924086700) for the motivation.

**Comment by izaera** [comment]
Portal (npm-scripts) seems to do it right according to what's in `NODE_ENV` variable.

I'm going to check `liferay-cli` too...

**Comment by bryceosterhaus** [comment]
Minifying with npm-scripts is relatively new, just added [last month](https://github.com/liferay/liferay-frontend-projects/pull/964)

I think we need to add the same [here](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/packages/portal-base/src/util/runSass.ts#L42-L47) for liferay-cli

**Comment by izaera** [comment]
> I think we need to add the same [here](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-toolkit/packages/portal-base/src/util/runSass.ts#L42-L47) for liferay-cli

Not only for SASS, but also for JS too. AFAIK we are not minifying JavaScript code...

**Comment by bryceosterhaus** [comment]
I think for JS we minify here, https://github.com/liferay/liferay-frontend-projects/blob/5deb730f13c1d2cd357275f535da504f7d719728/projects/npm-tools/packages/npm-scripts/src/scripts/build.js#L242

**Comment by izaera** [comment]
Mmm, I see. But that's for `npm-scripts`, so I need to move/copy that to `liferay-cli` because if the portal is not going to minify anything any more, I guess customers will want to get their output minified by default...

**Comment by izaera** [comment]
My plan is to minifiy for production builds, and leave everything untouched for dev ones (in liferay-cli). Then, if someone complains, we may add a flag to disable it (for example, in case someone wanted to use their own minifier). Does that make sense?

**Comment by izaera** [comment]
I'll use `terser`, like [we do in npm-scripts](https://github.com/liferay/liferay-frontend-projects/blob/5deb730f13c1d2cd357275f535da504f7d719728/projects/npm-tools/packages/npm-scripts/src/utils/minify.js#L150).

**Comment by bryceosterhaus** [comment]
@izaera you actually might be able to take advantage of something like babel-minify instead if that is easier. I think we terser was added to npm-scripts because of handling JS in jsp's as well

**Comment by izaera** [comment]
Yeah, that's what I was seeing now: it makes more sense to simply minify inside babel, instead of running an extra process :+1:
