### ISSUE TITLE
AUI Critical Accessibility Issue: Calendar does not display owner's name

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-frontend-projects#978]
> 👀 Please check the [troubleshooting guide](https://github.com/liferay/liferay-frontend-projects/blob/master/maintenance/projects/js-toolkit/docs/How-to-troubleshoot-your-setups.md) before reporting anything. It contains important information on how to fix or diagnose errors.

### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [x] 3.1.0-deprecated.97

### Description
The calendar event card does not contain the owner's name for accessibility.

**Desired behavior:**
The event card should contain the owner's name so that it meets accessibility.

**Current behavior:**
The event card does not contain owner's name, making it hard for a person with color deficiency would be able to take a look at the calendar and identify which event correlates with users calendar.

**Repro instructions (if applicable):**

**Other information (environment, versions etc):**

**Comment by bryceosterhaus** [comment]
@fortunatomaldonado I don't think deprecated.99 is even in master, is this the right version?

**Comment by fortunatomaldonado** [comment]
Hello @bryceosterhaus, you are right current master is using deprecated.97. I have updated the version.
This is still an issue in deprecated.99 and should have a solution for it out soon.
Let me know if there are any more questions or comments about this.
Thank you!

**Comment by bryceosterhaus** [comment]
fixed by #979

**Comment by bryceosterhaus** [comment]
released https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/webjars/com.liferay.webjars.alloy-ui/3.1.0-deprecated.100/

**Comment by fortunatomaldonado** [comment]
Thank you @bryceosterhaus for your help on this!
